### ISSUE TITLE
[Help Wanted] Difference between archive and trash

### ISSUE THREAD

**Issue by johnbillion** [standardnotes/forum#1003]
**Describe the issue**

In Standard Notes there's the option to archive a note or move it to the trash.

* What's the functional difference between these two options?
* Does the trash get emptied periodically like many other apps?
* Is there an option to manually empty the trash?
* Notes in the archive and the trash can still be edited (at least partly, it's a bit buggy). Is this intentional?

I checked the FAQ and searched the GitHub issues for answers but couldn't find anything.

**Comment by JaspalSuri** [comment]
Hello John,

> What's the functional difference between these two options?

They technically work the same way, but one major difference is that you can only fully delete a note that is in the Trash. Deleting a note from the Archive would move it to the trash.

Generally the Archive is for notes you're not worried about having to review later and want to filter out of your search results whereas the Trash is for note you really want to discard or feel ok with tossing away. My general heuristic is: if I don't ask myself whether or not I might need to keep it, I will put it in the Trash instead of the Archive folder.

> Does the trash get emptied periodically like many other apps?
It should not. I emptied the Trash recently and it had several old notes in there. @baptiste-grob can chime in if it ever does in certain situations. 

> Is there an option to manually empty the trash?

Yes! Please click on a note that is in the Trash to open it, then click on Option (located underneath the tag field) and then click on Empty Trash. (That's another functional difference between the Archive and Trash.)

> Notes in the archive and the trash can still be edited (at least partly, it's a bit buggy). Is this intentional?

While I personally do not know, our apps provide users the ability to Lock their notes, so it would be easier from a technical standpoint to allow users to edit any of their notes. Can you tell me what's buggy? I would love to hear what's not working as expected. Please include the editors that are being used and the OS that the app is running on. 

I hope this helps! Please let me know if you have any more questions! I will reach out to the team for questions whose answers that I do currently not know of.

I've assigned our Technical Writer, @TheodoreChu, to consider updating the FAQ. :)

**Comment by TheodoreChu** [comment]
I think what @JaspalSuri said is about right. We can use the Archive to hide notes that we don't need to see anymore but want to keep in SN. This can be used to improve workflow or app performance

The Trash is a place for us to mark the notes for deletion, but we need to empty it by ourselves

**Comment by johnbillion** [comment]
Thanks for the info folks. I actually found some of this info in the FAQ hidden under [What does it mean to lock or protect a note?](https://standardnotes.org/help/54/what-does-it-mean-to-lock-or-protect-a-note) but I couldn't find that by reading the list of FAQs on the main Help page.

Maybe you could add another FAQ item for archived and deleted notes?

Cheers

**Comment by JaspalSuri** [comment]
Thanks for the suggestion! I'll discuss it with the team to see what they have to say!
