### ISSUE TITLE
Filesafe-Onedrive integration

### ISSUE THREAD

**Issue by Tem3st** [standardnotes/forum#1034]
would like to know if I can use filesafe with onedrive as I have a subscription 4TB+ space available there, and only nominal space with the supported providers (Google and Dropbox)

Thx

**Comment by JaspalSuri** [comment]
Currently this isn't possible, but I will add it to the list of integrations to support in the future!

**Comment by X1SDNA** [comment]
I know this thread is from a couple of months ago, but I'd like to strongly second this proposal: Include OneDrive as an option for FileSafe.

**Comment by myreli** [comment]
Since [FileSafe is deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and this issue is unlikely to receive more interaction I'm closing it. [Files are now a native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) feature through encrypted storage. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
