### ISSUE TITLE
[Enhancement] Linking to other notes in-app

### ISSUE THREAD

**Issue by apederson94** [standardnotes/forum#1069]
Any chance at a feature where we can link some notes to other notes or specific sections of notes? As a software developer, I use Standard Notes to track progress on Jira tickets as well as my daily notes for what I did for daily standup.

Currently, I have a folder structure that can manage this, but it ends up having a lot of copy/pasting. If there were a feature where I could link to a specific spot in another note, I could record all my progress in my daily notes and then link that to specific tickets.

This could be managed using tags, but that could become very messy very quickly.

Thanks!

**Comment by apederson94** [comment]
That's totally reasonable. I just wanted to make the suggestion so that it could get you guys thinking about how it could work if it's something you'd want to do.

**Comment by JaspalSuri** [comment]
Of course! We've occasionally receive requests for this feature and a lot of "second brain" apps are gaining traction, so it's a possible direction that many text editing apps might evolve towards depending on how things turn out.

**Comment by heidlma** [comment]
+1 for this idea.

**Comment by kfiresmith** [comment]
+1

**Comment by thatwesguy** [comment]
I hear two separate requests here, and I'd like to amplify the one that is probably **easier to implement**:

1. Make it possible to link to another note
2. Make it possible to link to a particular place in another note

I'd get a ton of value out of #1 above.  #2 is just a nice-to-have in my view.  Any chance that this clarification could help bump up the priority of this feature request?

**Comment by apederson94** [comment]
I agree with you. The first request is much higher in value than number 2. Number 2 is definitely just a nice to have

**Comment by JaspalSuri** [comment]
> Any chance that this clarification could help bump up the priority of this feature request?

I'm afraid not since it might require support for note-linking in each editor or the creation/adoption of a new editor that would support note-linking. An faster alternative would be to provide links to other notes outside of the note itself, similar to tags. That said, as someone who isn't a developer, I can't guarantee that would expedite work on that version of note-linking as there might still be some significant things that we'd need to address first, such as support for Actions and the share sheet on the mobile apps. Let us know what you think!

**Comment by JaspalSuri** [comment]
Closing this since it is similar to #723.
