### ISSUE TITLE
App Restart After Autolock (Linux Desktop)

### ISSUE THREAD

**Issue by m-alt-f** [standardnotes/forum#1072]
**Describe the bug**
I have the StandardNotes desktop app set to lock after 5 minutes of inactivity (autolock). This works really well, but after unlocking the app "restarts" and loads all notes again. The note I was working on needs to be reopened, and I need to find the correct tag first. 

**To Reproduce**
1. Set up autolock with code
2. Wait for the time threshold to expire and reopen app (with unlock code)
Now the app will be restarted and you need to look for the note you were working on, which you can only do after first clicking on the appropriate tag.

**Expected behavior**
For everything to stay the same, before and after lock/unclock, so you can resume working.

**Desktop (please complete the following information):**
 - OS: GNU/Linux (Ubuntu 20.04 but this happened on previous versions of Ubuntu as well).
 - Browser: N/a - I use the appimage version 3.4.2 from https://standardnotes.org/extensions?downloaded=linux.
 - Version of the desktop app: 3.4.2

**Comment by baptiste-grob** [comment]
Thanks for the report!
This behavior is currently expected, because when the app locks it wipes all data from memory, leaving itself in a completely encrypted state. Locking is not just a UI concept but also a data concept, to protect the app from malicious software as well as malicious end-users.
Though this would definitely be nontrivial we could try to save the app's state when we lock it. Definitely something I'd like us to get to at some point!
