### ISSUE TITLE
Conflicted copy for Markdown Basic extension

### ISSUE THREAD

**Issue by dmitriy-bodroff** [standardnotes/forum#1074]
I get "Conflicted copy" for Markdown Basic extension and cannot fix it.

![image](https://user-images.githubusercontent.com/523055/90655513-58977680-e24a-11ea-8bbc-22fd38001c47.png)

**Comment by JaspalSuri** [comment]
Hi, I'm sorry that there isn't an easier way to delete the conflicted copies. May I ask what other devices are you are using Standard Notes on? This is something the team would like to have fixed by the next major release (v3.5).

To remove the additional copies, please click on the `Extensions` button (located in the lower left corner), enter in your passcode if needed, scroll down to the `Editors` section and uninstall the additional copies. Even if you were to accidentally delete all of them, you could easily reinstall the Markdown Basic Editor and none of your notes would be affected.

**Comment by nablagodel** [comment]
I'm using Xiaomi Redmi Note 8T and Google Chrome in Linux OS. Thank you, I followed your recommendation and fixed it.

**Comment by JaspalSuri** [comment]
Thanks for doing that and thanks for the info! I'll be sure to add it to our current report.
