### ISSUE TITLE
Plans for using MariaDB instead of MySQL?

### ISSUE THREAD

**Issue by ey-tsifry** [standardnotes/forum#1090]
Hi,

I'm curious if you are planning to stick with MySQL as Standard Notes's database of choice or migrate to MariaDB instead?  I ask because the Amazon Linux AMI is [end-of-lifing its standard support](https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/) on 31 December 2020, and the next gen AL2 apparently replaces MySQL with MariaDB.  I assume that most people will use the stock AL2 MariaDB package unless they make the extra effort to side load MySQL.

With the understanding that there is probably a low percentage of users (although I might be surprised?) who self-host Standard Notes on EC2/Amazon Linux hosts, I therefore wanted to ask what your plans are, especially if the MySQL/MariaDB issue potentially affects other distributions (I did not research this but suppose it's possible). Thanks!

**Comment by JaspalSuri** [comment]
Hi @ey-tsifry,

Thanks for bringing this to our attention. I've assigned two of our back-end devs to this to share their thoughts. 🙂

**Comment by karolsojko** [comment]
We are already using MariaDB as the underlying driver in order to connect to a database: https://github.com/standardnotes/syncing-server/blob/develop/Dockerfile#L11

As for AL2 - we have almost all of our apps Dockerized https://hub.docker.com/u/standardnotes and we highly recommend using our official images. This way we make ourselves independent of vendors image changes.

**Comment by ey-tsifry** [comment]
Thanks, that's helpful. I installed from the old standardfile repository the hard way (no Docker) and haven't updated for some time, so it looks like I'll be adding 'Docker migration' to my AL2 upgrade plan now. :)
