### ISSUE TITLE
Self-hosted AWS S3 storage, e.g Minio

### ISSUE THREAD

**Issue by 917huB** [standardnotes/forum#1102]
Is it possible to configure fileSafe to use self hosted AWS S3 compatible storage provisioned through services like Minio?

**Comment by myreli** [comment]
[FileSafe has been deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and it seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
