### ISSUE TITLE
Reset password via MySQL on self hosted

### ISSUE THREAD

**Issue by dallasFeature** [standardnotes/forum#1103]
Hi there,

I'd like to reset my self hosted standard notes password as unfortunately somehow the password is not working anymore.

I self hosted my standard notes so I can access MySQL and see my user on users table but don't know exactly how I can reset it (change it to something else).

Could you please help me with this process.

Regards,

**Comment by johnny243** [comment]
Hey @dallasFeature!

If I understood you correctly, you want to reset your self-host Standard Notes password? If so, that is currently not possible because the data is encrypted with an encryption key, which is derived from the current password. See [this article](https://standardnotes.org/help/6/i-ve-forgotten-my-password-what-should-i-do) for more information.

Your only choice would be to delete that account and start over.

**Comment by myreli** [comment]
Since this issue was opened SN has changed, including its [self-hosting documentation](https://standardnotes.com/help/self-hosting/getting-started). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
