### ISSUE TITLE
External editors and privacy

### ISSUE THREAD

**Issue by dcharalambous** [standardnotes/forum#113]
In the "Editor" menu of a note, under "External Editors", it is stated that external editors "can access your current note decrypted".  As I am not an expert in how these external editors work, I was just wondering whether actual note content is transferred away (decrypted) from my desktop, over to another (possibly network) location or whether all editing/formatting/markdown is simply happening on my desktop, with no information leaving my computer in plain text (decrypted). Just trying to understand the risk of using, e.g. a simple mark down editor with SN. Thanks!

**Comment by mobitar** [comment]
Hi, and good question. Once an editor is loaded from its remote location, all data input happens locally, so nothing leaves your computer. This isn't to say that external editors are *incapable* of sending data remotely. It's just that ours never do. We put up that warning so that you don't install editors from untrustworthy locations.

Really, if you're here for the hardcore privacy, editors might not be for you. But some users like a balance between privacy and productivity. Not every note I type is going to be super sensitive, so I can lower my guard just a little bit. Ultimately, it's up to the user to decide the kind of notes "lifestyle" they wish to lead. 

While our editors will never send data remotely, if you want to be on the safe side, you can take the approach of not editing notes that contain extremely sensitive data with external editors.

**Comment by dcharalambous** [comment]
Thank you very much for your response and advice - will stick to the system editor for more sensitive notes!
