### ISSUE TITLE
Where can I find my notes in plaintext/readable format on Mac?

### ISSUE THREAD

**Issue by justauserid** [standardnotes/forum#1138]
**Where are my note files on the disk, if at all they are on the disk?**

**To Reproduce**
Steps to reproduce the behaviour:
1. Check in settings/options and there is no way to choose where to keep the file locally on the Mac
2. Search on the Mac (e.g. using file names) and I am not able to locate the files

**Expected behaviour**
It should allow me a way to keep the decrypted version of my note files locally on my computer as well. At least an option to opt for it. There's none.

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.7
 - Standard Notes (desktop app)
 - Version 3.5.6

**Additional context**
I want to see where the files are saved locally on the Mac so that I can back up them on my own and that way I can keep a version history as well. It can also help me in case I get locked out of my notes (as there's no password reset in Standard Notes)

**Comment by JaspalSuri** [comment]
Hi @justauserid,

This currently isn't a feature because we don't want to accidentally "reveal" or "expose" your decrypted notes when they're not in use, in contrast with when you're using the app and it's unlocked. 

The desktop app (on the days that it's open) produces an encrypted backup of your notes daily.

To access them, please click on the `Backups` menu in the menu bar (available when the app is open and focused/clicked on) > `Open Backups Location`. 

It's available here on macOS: `/Users/YOURUSERNAME/Standard Notes Backups`. To access it via Finder, press <KBD>command</KBD>+<KBD>shift</KBD>+<KBD>G</KBD>, paste in that file path, insert your username in place of `YOURUSERNAME`, and then hit enter.

To decrypt your notes, you can follow the instructions [on this page](https://standardnotes.org/offline) to download a script that uses your encrypted notes file and your password. 

Of course, in the event that you forget your password but are still logged into the desktop app (or as a precaution before that happens), you can manually create decrypted backups of your notes by clicking on the `Account` button on the bottom-left corner > then scroll down, and under the section called `Data Backups`> click on the [radio button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio) next to the word `Decrypted`, and then click on the button that says `Download Backup`. 

I'll put in a request for providing an option for users to have automated decrypted offline backups. It might not be approved for security and privacy related reasons, but we'll review it once more.

**Comment by justauserid** [comment]
> This currently isn't a feature because we don't want to accidentally "reveal" or "expose" your decrypted notes when they're not in use, in contrast with when you're using the app and it's unlocked.

I don't understand how this can be a valid concern other than being a far-fetched reason just for the sake of it. By that standards everything on my Mac can be "accidentally exposed" including the notes itself via the desktop app. So everything should be locked; always. 

I mean it's my computer. I am supposed to have these notes on it as readable as it gets. It's open there, how can it be exposed? I know it's on my disk in plain text format.

I do believe:
- it will be an excellent feature. 
- will give users more control on their own data
- will mitigate against notes being locked in case of password being forgotten or some other issue

Yes, like many things it comes with resulting situations that may be challenging but that doesn't mean it's bad.

**Comment by baptiste-grob** [comment]
We go to great lengths to ensure your data is as hard to read by malicious programs as possible. That is part of our core principles. 
But if your notes are stored on your disk in plain text, it becomes extremely easy for any other program to read them and send them to a third-party over the network, or for someone with physical access to your computer to copy them. That's why we make sure no unencrypted data touches your disk unless you explicitly want to (via the backup download functionality).
In a world where you had control over everything that goes on in your computer, this surely wouldn't be an issue, but alas we do not live in that kind of world 😄
If you ever need to decrypt your backups without using Standard Notes, you can use our [offline tool](https://standardnotes.org/offline).

**Comment by JaspalSuri** [comment]
I also forgot to mention that the decrypted content that is visible when the app is open and/or unlocked is temporarily ["stored" in the device's RAM](https://blog.standardnotes.org/enhanced-security-with-device-storage-encryption/) and not written to the device's disk.

**Comment by justauserid** [comment]
Since it's by design then I guess it's a matter of choice on the part of developers.

> We go to great lengths to ensure your data is as hard to read by malicious programs and people as possible

That's commendable. But the point is having a choice. It can be an option - an opt-in option maybe.

>  If you ever need to decrypt your backups without using Standard Notes, you can use our offline tool.

That's fine but the backups are not diffed, are they? I guess they would be snapshots. If they can be diffed then it solves the problem at least partially that a user will have a local history of notes as well. 

Also, this doesn't solve the issue of password lost, forgotten, or not working for some reason - because that offline tool would be using the same password, wouldn't it? I have been locked out of accounts before. Password saved in a password manager, not touched for years and it suddenly stops working and app was auto logged out after the last update! 

Are there third party clients for Standard Notes yet? Is there an API? Something like the way `nv` is a Simplenote client.

**Comment by JaspalSuri** [comment]
> That's commendable. But the point is having a choice. It can be an option - an opt-in option maybe.

I've recorded your feedback, but I think in this case it will depend upon how many people request this feature, as it opens the user to a lot unnecessary risk.

>That's fine but the backups are not diffed, are they? I guess they would be snapshots. If they can be diffed then it solves the problem at least partially that a user will have a local history of notes as well.

You're correctly, they're closer to snapshots of your notes. We do offer the ability to access the version history of your notes in all of the apps and [Extended subscribers](https://standardnotes.org/extensions) can access a significantly longer amount (https://standardnotes.org/help/26/how-do-i-enable-note-version-history) of revisions.

>Also, this doesn't solve the issue of password lost, forgotten, or not working for some reason - because that offline tool would be using the same password, wouldn't it? I have been locked out of accounts before. Password saved in a password manager, not touched for years and it suddenly stops working and app was auto logged out after the last update!

I'm afraid that this is one thing that we expect from all of our users since we do not store your password in order to keep your notes truly private. I would suggest logging into our [web app](https://app.standardnotes.org/) to see if the password generated and saved by your password manager is the one used by your account. If not, you can export a decrypted copy of your notes from any of the clients that you're logged into (there currently is an issue with the mobile app where the decrypted backups are encrypted, but this will be fixed soon). It's also possible that you could check the date that your account info was last modified in your password manager and look for backups that were saved during that time and decrypt them.

>Are there third party clients for Standard Notes yet? Is there an API? Something like the way nv is a Simplenote client.

[Here is an unofficial list](https://github.com/jonhadfield/awesome-standard-notes#tools) of tools provided by the community that might help. There is also a [client written in Rust](https://github.com/matze/iridium) that [another user](https://github.com/standardnotes/forum/issues/1135) shared with us.

**Comment by justauserid** [comment]
Sure, I'll go through the links. I am closing it as it seems there's hardly any demand for this feature. Thank you both for the responses!
