### ISSUE TITLE
[Help Wanted] Move notes between "folders"

### ISSUE THREAD

**Issue by kfiresmith** [standardnotes/forum#1153]
**Describe the issue**
5 year extended user here, trying to use folder plugin - can't move notes from one folder to another.

**To Reproduce**
1. Create note
2. Create new folder
3. Try all UI options to "move" note into "folder"
4. See no way to drag or execute a menu option to move a note

**Expected behavior**
A clear documented method to move notes from one folder to another

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 AppImage and Browser based
 - Browser Chrome:latest
 - Version Std Notes latest

**Additional context**
The documentation for this plugin doesn't appear  to exist.  It's only a screenshot and a demo page.  Since this is IMO a core function of a notes app, it should be documented in detail if it can not be made intuitive via UI/UX tuning.  Right now it is neither documented nor intuitive.

**Comment by JaspalSuri** [comment]
Hi @kfiresmith,

Currently there isn't a way to drag notes to folders and vice versa. The current way to modify which folders are connected to a note is to add them in via the tag bar / text field, which is located underneath the title text field of each note. You can click on the tags and folders that are added in order to remove them from the tag bar. The `Quick Tags` extensions make inserting tags easier as it provides a list of matching tags against what it currently typed in the text field of the tag bar.

>The documentation for this plugin doesn't appear to exist. It's only a screenshot and a demo page. Since this is IMO a core function of a notes app, it should be documented in detail if it can not be made intuitive via UI/UX tuning. Right now it is neither documented nor intuitive.

I understand. We plan to overhaul our site and the UI and UX for version 4.0 of our apps.

**Comment by codepotatoe** [comment]
I type it in manually for each note...

#tagParent -> Parent folder
#tagParent.tagChild -> Child folder

**Comment by kfiresmith** [comment]
Looking forward to 4.0 - I'll have to dig around and see if there is a timeline for that to arrive.  Thanks for the information.
