### ISSUE TITLE
Editing a note on offline device error

### ISSUE THREAD

**Issue by R3DJOK3R1** [standardnotes/forum#117]
i edited a note offline on my PC and edited the same note but online on my mobile device, both are different edits, so when i synced my PC what i wrote on PC was gone and i couldn't get it back and what was edited on android only synced

**Comment by mobitar** [comment]
How far apart were the edits? Here's how it should work:

If you edit something on one device, and edit the same note on another device:
- If the edits are within 20 seconds apart, the last edit wins.
- If the edits are greater than 20 seconds apart, the note should be duplicated so that both copies remain.

Do you know which scenario yours falls under? If it's the second one, can you tell me what versions of the app you're using on both platforms? Bonus points if you can replicate this behavior consistently :)

**Comment by R3DJOK3R1** [comment]
the first one happened i used this version of PC which is i think 2.0.1, i replicated this behavior and the the 2nd one happened with the duplicated notes

**Comment by mobitar** [comment]
Please upgrade to desktop v2.0.2, which has some fixes that address issues in this proximity. https://standardnotes.org/download/all
