### ISSUE TITLE
Lost unsynced changes after signing out of account

### ISSUE THREAD

**Issue by bones-shift** [standardnotes/forum#1171]
![Screenshot_20201217-174757(1)](https://user-images.githubusercontent.com/62573813/102543827-9e4a3b80-4092-11eb-8f9a-06b9ee6b2ddf.png)

I never had any problems with this amazing app, but today after receiving the last update, this SHIT happened and I had to leave my account and when I came back I had lost at least 20% of my notes, the luck I had was to have  exported the data before.  I hope it doesn't happen to another user.

**Comment by mobitar** [comment]
Sorry about that. I can see now that asking you to sign out due to invalid sync state doesn't correctly communicate that you will lose any unsynced changes. I've pushed an update to our library that corrects this behavior so that instead of showing you this alert in the case of invalid state, it instead allows you to sign in in-line without needing to sign out. This will be reviewed tomorrow and hopefully shipped in an app update the same day. Glad you had a backup, and thanks for pointing this out, as these fixes should prevent this from happening to anyone else.

**Comment by myreli** [comment]
Seems like this issue was solved is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
