### ISSUE TITLE
Doesn't automatically update?

### ISSUE THREAD

**Issue by abraham-L** [standardnotes/forum#118]
Weird. I have the desktop app for PC and the Android and iOS apps.

Desktop: it doesn't have an option to check for updates? I tried to look and it's just nowhere to be found. Therefore, it didn't automatically update, therefore I didn't realize there was a version 2 until one of my tickets had been closed.
Android: I had to download another app? It seems like the app was changed or something, instead of just updated in the Play Store? I have no idea why that happened, but that was it.
iOS: I have an iPad Air. And the situation was the exact same as my Android phone.

It would be great if the app updated by itself, or if you were able to check for updates or something.

**Comment by mobitar** [comment]
Hi there, so for iOS and Android, the new v2 app was released as a separate app because it was backwards incompatible. You should have received an email about this :) Also blog post [here](https://standardnotes.org/blog/10/introducing-our-new-android-ios-and-desktop-apps).

The desktop app automatically checks for update on launch and open, so it should have just detected it automatically. You did not see a message regarding a new update when you were on v1?

**Comment by cryptopana** [comment]
I actually didn't. Not at all. I had to come to the website to manually download the new version.

**Comment by mobitar** [comment]
Strange. Will investigate.

**Comment by cedewey** [comment]
My desktop app didn't detect 2.1 when I closed it and reopened it. Is there a recommend manual way to update that ensures my notes are kept intact?

P.S. I love this app, nice work. :)

**Comment by mobitar** [comment]
Hmm that's strange. You can download manually from standardnotes.org. Your data will be kept intact as the data location is stored separately from the application itself.

Glad you're enjoying the app!
