### ISSUE TITLE
Unable to open .enex file using Import Backup

### ISSUE THREAD

**Issue by dtrossiter** [standardnotes/forum#1187]
**Describe the bug**
When using the Import Backup feature for the purpose of migrating from Evernote, I get the following message after choosing  the backup file in the Open dialog box. "Unable to open file. Ensure it is a proper JSON file and try again."

**To Reproduce**
1. Go to 'Account"
2. Click on 'Import Backup'
3. Navigate to the file to be imported in the file system
4. Select the file to be imported
4. See error dialog "Unable to open file. Ensure it is a proper JSON file and try again."

**Expected behavior**
Import the contents of the Evernote notebook from the .enex file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.04, Cinnamon
 - Browser: Brave
 - Version 1.18.77

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 11
 - Browser Brave
 - Version 1.18.75

**Additional context**

**Comment by chairmantheboring** [comment]
You have to use the converter tool [found here](https://dashboard.standardnotes.org/tools) to import notes from Evernote to StandardNotes.

**Comment by dtrossiter** [comment]
@chairmantheboring, those are the instructions I followed. I don't see any
Evernote file converter. It just says use Import Backup on the .enex files
exported from Evernote. That is the function that threw the error. Any
other ideas?

**Comment by chairmantheboring** [comment]
@dtrossiter, you put your enex file into the Evernote section on that site, then it will download the file you import into StandardNotes.

**Comment by dhdvt** [comment]
I get same error. how do you get a json file from a enex file?

**Comment by JaspalSuri** [comment]
As @chairmantheboring said:

1. Visit this link: https://dashboard.standardnotes.org/tools
2. Click on **Choose File**
3. Locate the `.enex` file
4. Select the `.enex` file and click on open/confirm or whatever else it might say towards the bottom right of the file picker window
5. It should download the `JSON` file
6. Open the desktop or [web](app.standardnotes.org) app
7. Click on **Account**
8. Click **Import Backup**
9. Locate the `JSON` file that was downloaded (it's likely to be in your **Downloads** folder)
10. Select the `JSON` file and click on open/confirm or whatever else it might say towards the bottom right of the file picker window
11. Sign into your Standard Notes account (make sure to click on **Sign In** first instead of **Register**)

It should import the backup as expected. Please let us know if you have any additional questions!

Here's a screenshot of the relevant part of the web page with the offline note converter tool that uses the exported file from Evernote.
![image](https://user-images.githubusercontent.com/44656000/103560420-98af6c80-4e6c-11eb-9a0f-31f4718556a1.png)

**Comment by dtrossiter** [comment]
Thanks Jaspal. I had clicked on that button early on, but it just opened a
graphic in the viewer. I think my browser was blocking scripts. I have
imported my notes, but despite being an extended user, it's stripped off
all formatting. That's for another thread.
