### ISSUE TITLE
[Question] What is "Insert Link" in FileSafe?

### ISSUE THREAD

**Issue by karan** [standardnotes/forum#1194]
What does "Copy Insert Link" do? It copy-pasted `[FileSafe:some-id:file-name.pdf]` but I don't know what to do with it. If I paste it into the note, it's not clickable and doesn't do anything.

Is there literally any documentation for it?

**Comment by JaspalSuri** [comment]
Hey @karan,

>What does "Copy Insert Link" do? It copy-pasted [FileSafe:some-id:file-name.pdf] but I don't know what to do with it. If I paste it into the note, it's not clickable and doesn't do anything.

The **Copy Insert Link** button copies the link to a file uploaded via FileSafe so a user can paste it somewhere into a note that can use the Bold Editor (i.e. not a note that is already using the Secure Spreadsheets or TokenVault editors and already contains data). Since FileSafe is currently integrated into the Bold Editor, the apps will render inline-previews for links to images that are contained within their notes. 

>Is there literally any documentation for it?

I've passed along your feedback in the form of a request to update the docs with information about this. 🙂 Thanks for bringing that issue to our attention!

**Comment by TheodoreChu** [comment]
@karan, thanks for bringing this up. I wrote some documentation here: https://docs.standardnotes.org/usage/filesafe/#filesafe-with-the-bold-editor

Please let me know if you think the docs need more information or could otherwise be more helpful. 🙂

**Comment by myreli** [comment]
Since [FileSafe is deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and this issue is unlikely to receive more interaction I'm closing it. [Files are now a native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) feature through encrypted storage. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Comment by myreli** [comment]
Since [FileSafe is deprecated](https://standardnotes.com/blog/deprecation-notice-filesafe) and this issue is unlikely to receive more interaction I'm closing it. [Files are now a native](https://standardnotes.com/blog/introducing-encrypted-file-storage-with-automated-backups) feature through encrypted storage. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
