### ISSUE TITLE
Mass archive notes?

### ISSUE THREAD

**Issue by yingw787** [standardnotes/forum#1222]
As a user, I'd like to mass archive notes. Currently, I see the GUI ability to click on an individual note and archive it, but no ability to select multiple notes and right-click "Archive". 

Also, not sure how I might be able to archive notes if I process the backup sent to email by Standard Notes.

**Comment by JaspalSuri** [comment]
Hi @yingw787,

>As a user, I'd like to mass archive notes. Currently, I see the GUI ability to click on an individual note and archive it, but no ability to select multiple notes and right-click "Archive".

This is currently planned for a future version of the desktop and mobile apps; we plan to have this feature available later this year. 🙂 

>Also, not sure how I might be able to archive notes if I process the backup sent to email by Standard Notes.

Archived notes that are restored from the backup should remain archived upon being imported. The best way to test this would be by importing the notes into the [web app](https://app.standardnotes.org) **without** being signed in, so that way you can clear the local data before signing in if necessary (via the Account menu). If everything is imported properly, you can sign in and select the option to merge and sync the locally stored data. 🙂 Please let us know how that goes!

**Comment by yingw787** [comment]
Thank you very much for the prompt response @JaspalSuri! If the batch archive feature is coming later this year, I'll just wait for that; I have around 2000 notes and I'd rather just wait for the feature rather than fiddle with the backups and possibly end up in a worse situation. Thanks again for the customer support, and looking forward to that feature!

**Comment by JaspalSuri** [comment]
You're welcome! We're looking forward to it as well. 🙂
