### ISSUE TITLE
Security Update Auth Prompt - Mask Email Address

### ISSUE THREAD

**Issue by iganeshk** [standardnotes/forum#1229]
![image](https://user-images.githubusercontent.com/23004399/106360711-0f168180-62e8-11eb-84b2-f45220628cbf.png)

While I performed an update, the prompt required me to enter email address and password again. Email needs to be masked and may be add placeholder text to input boxes?

**Comment by mobitar** [comment]
Emails are typically masked in UX interactions when the email can be exposed publicly via anyone that requests some kind of account reset. In this case it's only presented to you within your previously valid application session.

We should at some point add this value to the textbox since we already know it.
