### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by panthia** [standardnotes/forum#1233]
Installed on Windows Server 2012 and form comes up blank white. I installed as a user and not the admin but this should not be an issue. 

I downloaded a second time and installed again to the same result. 

**Expected behavior**
Graphics should be visible. The way it is I can't use it at all.

**Comment by myreli** [comment]
Since this issue was opened SN has changed, including its [self-hosting documentation](https://standardnotes.com/help/self-hosting/getting-started). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
