### ISSUE TITLE
Bottom panel vertical height is minimal and cannot be resized

### ISSUE THREAD

**Issue by 0x1a4f7d58** [standardnotes/forum#1240]
**Describe the bug**
Bottom panel that supports the following extensions cannot be resized: 
- Action Bar
- FileSafe
- GitHub Push

**To Reproduce**
1. Go to a note (editor selection doesn't matter)
2. Click on one or more of the following extensions to activate: Action Bar or FileSafe or GitHub Push
3. Attempt to resize the panel window
4. See error -- bottom panel is restricted is height and cannot be changed :/

**Expected behavior**
Bottom panel can be resized up/down so that content of extension can be viewed with ease

**Screenshots**
![image](https://user-images.githubusercontent.com/10007010/108374318-6a76c800-7233-11eb-9971-1066ebf388f3.png)

**Desktop (please complete the following information):**
 - OS: MacOS Desktop App
 - Browser: Chrome -- replicated the issue here
 - Version: 3.5.18 (MacOS), 3.5.19 (Chrome)

**Smartphone (please complete the following information):**
- n/a

**Additional context**
Other panels are re-sizable so it's odd this one isn't

**Comment by JaspalSuri** [comment]
Hi @0x1a4f7d58,

This appears to be intentional but we plan to redesign these components of the app's UI alongside the rest of the app for version 4.

For the FileSafe extension you can click on the button that's close to the right edge of the screen to expand its interface a bit more (but will still need to scroll inside of it).
