### ISSUE TITLE
Editor sync to Android app

### ISSUE THREAD

**Issue by klyon441** [standardnotes/forum#1245]
(Extended user)

I created a few notes in the windows app, using various editors.

I open the Android app and get raw text.

If I happen to recall what editor was used in the desktop app to create the note, I can choose that editor (in the android app) and it then renders fine.

In order to use the Android app, am I expected to:

- (a) always know what editor I used in the Windows app
- (b) always have to choose / fix the editor for every note

???

In windows app:
![SN Windows App](https://user-images.githubusercontent.com/4211534/108625721-03fbd080-7412-11eb-9ff1-3c9beae4b8f5.png)

In Android app (before choosing editor):

![SN Windows Before Editor Selection](https://user-images.githubusercontent.com/4211534/108625943-3ce87500-7413-11eb-8000-d4b3f7afad28.png)

After selecting the (Plus Editor) editor in the app:

![SN Windows After Editor Selection](https://user-images.githubusercontent.com/4211534/108625938-30fcb300-7413-11eb-81c4-803731b80023.png)

**Comment by klyon441** [comment]
I created a note in the Windows app using Plus Editor.  

Then I go to the Android app, and it comes up with raw text - it is showing the selected editor to be Plain Editor.  

If I change the editor in the Android app, it updates back to the Windows app.  

However, if I update it in the Windows app, it doesn't seem to push which editor is chosen to the Android app.

**Comment by JaspalSuri** [comment]
Hi @klyon441,

Currently if a note is being used in default editor of the desktop app, then the mobile app will load that note's contents into the default editor of the mobile app. To have it load the note's contents into the same editor on the Android app, please open the desired note, open the right sidebar, tap on **Editors**,  press and hold the button for the Plus Editor, then tap **Set as Mobile Default**.

We're considering changing this behavior so that all notes that are created from either app will use the same editor, the one that was last assigned to the note, across all platforms by default.

**Comment by myreli** [comment]
> We're considering changing this behaviour so that all notes that are created from either app will use the same editor, the one that was last assigned to the note, across all platforms by default.

I suppose since the [new mobile experience launched](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) this is now the behaviour. 

It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
