### ISSUE TITLE
Add FileSafe to Markdown Pro editor

### ISSUE THREAD

**Issue by fiskeren** [standardnotes/forum#1273]
**Have you read the [Longevity Statement](https://standardnotes.org/longevity)?**
yes

**Is your feature request related to a problem? Please describe.**
I love Standard Notes, I also love markdown and do all my notes in it. I often have to save a file together with my notes ie. a PDF or a screenshot, but to do that I have to create another note in Standard Notes using the bold editor, which I then use as file document.

**Describe the solution you'd like**
Add the filesafe feature to the Markdown Pro editor, so files can be held together with notes (or even be able to paste a picture directly to markdown)

**Describe alternatives you've considered**
Created my note using markdown editor, and also making second note using bold editor to paste stuff in to. Resulting in having two notes regarding same topic.

**Comment by JaspalSuri** [comment]
Hi @fiskeren,

Sorry for the delayed response. Instead of integrating FileSafe with multiple editors, we plan to provide a way to natively attached files to notes, similar to what you're describing. 

In the meantime, you can use the FileSafe extension on the [web ](https://app.standardnotes.org) or desktop apps with any note that is using any editor to "attach" a file to specific notes. The files that are uploaded will appear at the top-most level, above the other files that have been uploaded. 

For the mobile app, you can create a new note, switch to the Bold Editor, click on the icon that looks sort of like a file cabinet, upload files via FileSafe, then close the FileSafe modal, and switch to another editor.

**Comment by myreli** [comment]
[Files are now native](https://standardnotes.com/blog/folders-from-extension-to-native). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
