### ISSUE TITLE
Can I publish to listed from iOS app?

### ISSUE THREAD

**Issue by madhums** [standardnotes/forum#1289]
I am trying to find a way to publish to listed from the iOS app, is this possible or under consideration?

**Comment by JaspalSuri** [comment]
Hi @madhums,

It's currently not possible to publish the contents of a note as a post on one of your Listed blogs, but it's one of the features that is on our roadmap. 🙂 

I'm going to close this thread since it's similar to #1242, but please let me know if you have any additional questions or feedback.
