### ISSUE TITLE
[Help Wanted] Password Encryption Method

### ISSUE THREAD

**Issue by infosisio** [standardnotes/forum#1329]
I would like to ask for some details about the password encryption method that standardnotes uses. 

The part that is not clear to me is how password encryption can be that great and survive brute forcing efforts.

This is an important part to clarify as we have backups sit on cloud services etc.

**Comment by user8446** [comment]
It's public information right on the website: https://standardnotes.org/help/52/what-services-does-standard-notes-use-for-daily-operation

**Comment by infosisio** [comment]
@user8446 I've asked how the algorithms of Standardnotes secure against the common problem of brute forcing, since it's password-based encryption which theoretically is vulnerable.

**Comment by user8446** [comment]
Argon2 is the best known algorithm  against brute force and dictionary attacks because it slows down fast you can iterate. Choosing a log character password also would significantly slow down brute force and eliminate dictionary attacks.
More info: https://www.password-hashing.net/
https://keepass.info/help/base/security.html

**Comment by infosisio** [comment]
@user8446 Reading about Argon2 now, it seems promising. Thanks for the responses.
