### ISSUE TITLE
Most of my tags on Android say "unable to decrypt"

### ISSUE THREAD

**Issue by Marxsal** [standardnotes/forum#1332]
**Describe the bug**

Most of my tags on Android say "unable to decrypt." Some notes say "waiting for keys".

**To Reproduce**

I just opened the app and got "unable to decrypt" on all tags. Some notes  say "waiting for keys".

**Expected behavior**

Expect to see tags and notes.

**Smartphone (please complete the following information):**
 - Device: Moto G6
 - OS: Android 8

**Additional context**

It was working fine yesterday. I have rebooted phone, but it didn't fix things.  Will I need to re-install SN? My desktop and web versions are working fine (I hope). Having an easy sync experience was part of what got me interested in SN. So having it scramble itself is disheartening. 

I had to change passwords two days ago. Could some of the notes/tags on the device still be using the old password? The few tags that are working are ones I would have used yesterday.

**Comment by Marxsal** [comment]
I uninstalled. Reinstalled. Was met with an "Authentication needed" dialog. Something about a keyring. Didn't explain itself. What am I authenticating? What password is needed? What keyring? I don't know anything about a keyring (it didn't ask for an email, so it wasn't my sign-in)

I uninstalled again. Rebooted the phone. Reinstalled. Now I seem to be back in business. I hope this is a one-off.

**Comment by JaspalSuri** [comment]
Hi @Marxsal, I'm sorry to hear that. After changing one's password, the desktop and web apps should inform users that they need to sign out of all of their other devices and sign back in, as everything needs to be re-encrypted with the new password. Since we do not store your password, the content on the other devices can't be decrypted automatically. 

As for reinstalling the app the first time not working as expected, it's possible that the Google Play Store installed a backup of the app to your phone, and it either asked for your passcode or password after launching it. While _keyring_ might not be the precise term, it is referring to whatever Android is using to secure store the keys generated from your password after you've signed into the app.

If this ever happens again, you can clear the app's storage and cache, relaunch the app, and sign in again (all without reinstalling the app).
