### ISSUE TITLE
150ish Notes Either Broken or Lost [Help Wanted]

### ISSUE THREAD

**Issue by Creatie35** [standardnotes/forum#1334]
**Describe the issue**
I synced my offline notes with my account, then updated my app version. Once it was updated, about 150 or so of my notes have an "unable to decrypt" message on them, along with the instruction to sign out, update/reinstall, & sign in again to fix the issue. I did that, & instead of fixing the issue all of those notes just completely disappeared.

I did one backup before updating, & the backup file is missing encryption keys & unable to decrypt.
I tried to sign in on legacy to see if I can save my notes that way, & it says "This version of the application does not support your newer account type. Please upgrade to the latest version of Standard Notes to sign in."

I had around 700 notes, now only about 500 are functional.

**To Reproduce**
1. Sync offline notes to my account by signing into it.
2. Sign out of my account on all devices but one (1).
3. Update my app version (to 3.5.0 from its predecessor) .
4. Enter account password for authentication.
5. See issue ("Encryption keys lost" on about 150 notes)
6. Don't use for like 5 months in hopes this was a bug that would be fixed w/ an update in a few weeks, & then completely forgot.  
7. See issue ("Unable to decrypt. Sign out, update, or reinstall, then sign back in to fix issue." 
8. Sign out, & update (from 3.5.14 to 3.6.14 (automatic updates from 3.5.0 to 3.5.14)).
9. See issue (all notes which were previously unable to decrypt are now just completely gone, & no longer contribute to my total count of notes.
10. Attempt to import backup.
11. See issue ("Import complete. 556 items were not imported because there was an error decrypting them. Make sure the password is correct and try again."--- these were backed up decrypted there is no password on them.)

**Expected behavior**
After syncing, & updating my app/account would work normally. No decryption, or lost notes issues. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: currently 3.6.14, formerly 3.5.14, & 3.5.0 

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.4.2
 -  Browser N/A
 - Version 3.5.0 when I used it on iPhone (now)

**Additional context**
I've signed in across platforms(Ubuntu, iOS, android, & web) to see if this was a uniform issue, & it is.

**Comment by JaspalSuri** [comment]
Hi @Creatie35, I'm sorry to hear that.

>I did one backup before updating, & the backup file is missing encryption keys & unable to decrypt.

Did this backup include the 150 notes that are currently missing? Can you add this to the reproduction steps so that way I can get a better understanding of when the backup was performed with respect to everything else?

And just to make sure: 

- Did this happen entirely on the web app? Please make sure to update the iPhone app from the App Store later.
- While I understand that you exported a decrypted backup, did you use a passcode lock in the app while storing notes offline? 
- Have you manually examined the contents of the decrypted backup with text editors, etc.? 
- Were you signed in at some point and then found yourself signed out?
- Are you able to decrypt the backup file with the latest version of the [decrypt script](https://raw.githubusercontent.com/standardfile/decrypt/master/dist/decrypt.html)? You'll have to paste the code into a text editor and save it as an HTML file, or right-click the link and save it as an HTML file.

**Comment by mobitar** [comment]
> Update my app version (to 3.5.0 from its predecessor) .

I suppose as well this depends entirely on what app version the predecessor. Was it 1.x? Or 2.x? We do rigorously test migrations from 1.x to current versions, but the larger the gap in version the more chance there is for edge cases unfortunately.

> I did one backup before updating

So this backup was made after syncing your offline notes to an account, but before upgrading your application, correct? How many of notes in total were offline, and how many were pre-existing in your account?

If you could also email me your account email I could dig in a little deeper.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
