### ISSUE TITLE
Cannot import or use extensions from web interface

### ISSUE THREAD

**Issue by jwodder** [standardnotes/forum#1343]
Trying to import my notes via the web interface fails on the first step: When I click on "Extensions", I get an error.

In Safari 14.1 (Clicking "Reload" does not help):
<img width="470" alt="Screen Shot 2021-06-12 at 19 12 34" src="https://user-images.githubusercontent.com/98207/121790884-2cbaf800-cbb2-11eb-8a6a-53afe515ee28.png">

In Chrome 91.0.4472.77 (Clicking "Reload" does not help):
<img width="359" alt="Screen Shot 2021-06-12 at 19 13 20" src="https://user-images.githubusercontent.com/98207/121790900-4a885d00-cbb2-11eb-80a6-150047c09433.png">

(I get further in Firefox, but then when I actually try to import, I hit #1342.)

OS: macOS 11.3.1

**Comment by JaspalSuri** [comment]
Hi @jwodder, I'm sorry to hear that but I'm afraid that I wasn't able to reproduce the issue when importing a backup via the Backup **Explorer** option within the **Batch Manager** (I recovered all of the items in the backup) or via the **Import Backup** option within the **Account** menu. 

How old is the backup that you are trying to import? Can you open an incognito/private browsing window (within a Chrome-based browser), right click anywhere on the page, click **Inspect Element**, click on the **Console** tab, re-import the backup, and then send us screenshots of the errors that appear (if any) in the **Console** tab?

**Comment by jwodder** [comment]
> How old is the backup that you are trying to import?

Both the source ENEX file and the converted Standardnotes version were created minutes before.

> Can you open an incognito/private browsing window (within a Chrome-based browser), right click anywhere on the page, click Inspect Element, click on the Console tab, re-import the backup, and then send us screenshots of the errors that appear (if any) in the Console tab?

Here's the contents of the Console after trying to import again:

<img width="542" alt="Screen Shot 2021-06-15 at 08 24 43" src="https://user-images.githubusercontent.com/98207/122052001-352e5100-cdb3-11eb-8681-5bd8b9ceaaa9.png">

**Comment by JaspalSuri** [comment]
Hi @jwodder, thank you for that. I'll pass it long to the dev team to review. 

Are you importing the backup via the **Account** menu or the **Batch Manager**?

**Comment by jwodder** [comment]
@JaspalSuri The Batch Manager.

**Comment by JaspalSuri** [comment]
Hi @jwodder, thank you for clarifying. Can you launch the web app in a non-signed in state (i.e. use an incognito/private browsing window in a Chrome-based browser, or sign out of your account in a normal window on any browser) and import a backup via the **Account** menu to see if you run into the same issue? 

If not, please export a set of decrypted and encrypted backups of your account via the **Account** menu, [reset the account](http://standardnotes.com) to start from a clean slate, register a new account, and then import the data (that you had previous imported via the Batch Manager) from the **Account** menu. To add in all of the new notes that were created since then, please look in the **Note** folder of the of the decrypted backup (you will need to unzip the zip file first). I'm afraid that will have to manually re-tag the notes as well.

**Comment by jwodder** [comment]
@JaspalSuri

> Can you launch the web app in a non-signed in state (i.e. use an incognito/private browsing window in a Chrome-based browser, or sign out of your account in a normal window on any browser) and import a backup via the Account menu to see if you run into the same issue?

That works.

**Comment by JaspalSuri** [comment]
Thank you for letting us know! Please let us know if you have any additional questions or feedback. 🙂
