### ISSUE TITLE
"All Notes" Panel has disappeared, can't retrieve it.

### ISSUE THREAD

**Issue by boredincali** [standardnotes/forum#1348]
**Describe the bug**
I resized my Views and All Notes (Search) panels. I wanted to minimize them so as to make my writing window as large as possible. I ended up causing an issue that I could not retrieve my Views panel nor my All Notes panel (with the search field). I was able to retrieve my Views panel (not sure how exactly). But cannot retrieve All Notes panel. 

**To Reproduce**
1. Go to a note 
2. Hover above the line splitting the All Notes Panel and Note (writing) panel. 
3. When double arrows appear, click and drag until "All Notes" panel disappears. 
4. Repeat for "Views" Panel.  

**Actual Behavior**
My writing window is maximized. However, i had a very difficult time retrieving the Views Panel. I'm not even sure how I managed to do it, but I got it to come back. I click on the "All Notes", "Archived", and "Trash" items at the top. None of them retrieve the "All Notes" panel that lists outs my notes.  I know they are there because when I click on different tags, a different note loads onto the writing panel.  

**Expected behavior**
I can retrieve or expand the "All Notes" panel so I can see my list of notes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44553440/122509455-aab73e80-cfb8-11eb-8719-809b150337eb.png)
Tags and Notes are hidden. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
Not on Smartphone

**Additional context**
I know I did this when I closed the panels, but I assumed I could get them to expand again. I kept double clicking the edge. I added the "Folders" extension and I believe that's what brought back the Views panel. I also upgraded to the latest version to ensure that wasn't the issue, but no dice. Restarted and no dice. Clicking on any of the tags retrieves I believe the last updated file with the tag.

**Comment by mobitar** [comment]
Can replicate, thanks for reporting. We'll get this fixed asap but for now what you could for a manual fix is:

1. [Open dev tools](https://developer.chrome.com/docs/devtools/open/) and navigate to the Console tab.
2. Type in this command then press enter: `document.getElementById("notes-column").style.width = "200px"`
3. Once the notes panel appears, resize it with your mouse manually by gripping the right edge and dragging your mouse. This will trigger a save event so that the width is now properly saved.

You can do the same thing for the Tags column if it's disappeared: `document.getElementById("tags-column").style.width = "200px"`

A disclaimer that you shouldn't get in the habit of pasting code in the Console tab unless you know what you're doing. In this case the code is harmless but always double check before you copy/paste code into the console.

**Comment by tetrapak-dev** [comment]
This happened to me also in the Firefox 89.0 browser on Ubuntu (Linux Mint 20.1.)
Thanks @mobitar for the tip!

**Comment by JaspalSuri** [comment]
Hi everyone, I'm very sorry about this. We were trying to address another issue where [column/panel resizer would conflict with the scrollbar](https://github.com/standardnotes/web/issues/582) for users who didn't have a scroll wheel on their mice, so after reporting the issue I suggested to the dev team that the width of the resizer be reduced. In my brief testing I didn't account for the case where the columns would be fully collapsed and this issue slipped through as a result. A fix for this issue will be out later today or at least by Monday at the latest.

**Comment by tetrapak-dev** [comment]
No worries. Thanks for the update!

**Comment by JaspalSuri** [comment]
Hi everyone, this issue should be fixed in `v3.8.6` of the web and desktop apps. I am closing this thread, but feel free to let us know if you have any additional questions or feedback. 🙂
