### ISSUE TITLE
Question about Self-hosting Standard Notes

### ISSUE THREAD

**Issue by smokinjo** [standardnotes/forum#1354]
**Describe the issue**
A clear and concise description of what the issue is.
I am trying to understand how Standard notes works.

I want to take notes on my Linux machine.  I want to be able to synchronize them to a webdav folder (located in NextCloud).
I then want to be able to automatically synchronize the linux box to the android phone, via NextCloud.

I enabled the back up system.  But, is this the synchronization system?

It talks about signing in to my account.  I need to sign n to webdav/Next cloud, right?  Or, I need a standard notes account some where too?

Thanks

Joseph

**Comment by JaspalSuri** [comment]
Hi @smokinjo,

The default syncing server for the items on an account would be our servers, but you can self-host Standard Notes as well using what's provided in our [Standalone repo](https://github.com/standardnotes/standalone). 

[Here is the documentation](https://docs.standardnotes.org/self-hosting/getting-started/) on how to set that up. 🙂 

It currently doesn't have dedicated support for Nextcloud-based setups.

**Comment by myreli** [comment]
[Check the new self-host documentation.](https://standardnotes.com/help/self-hosting/docker). 

It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
