### ISSUE TITLE
"Unknown error" in Linux client

### ISSUE THREAD

**Issue by bigjdunham** [standardnotes/forum#1372]
When attempting to login from the Linux client (appimage) to my self-hosted instance of Standard Notes I get an "unknown error." popup window with the only option being to press "okay." Nothing else happens and I can't login to my self-hosted instance of Standard Notes. I can login via a web client from Firefox, and I can login from the Standard Notes client in MacOS. I am using the Standard Notes client 3.8.15 (but the issue was also present in an older version before upgrading to the this version). I am running ZorinOS 15.3 (based on Ubuntu 18.04). Does anyone know what might be causing this issue? Or if not, how I can get a more robust error log so I can get a more descriptive error, than "unknown error."? Thanks.

**Comment by johnny243** [comment]
Hi @bigjdunham! Thanks for reporting this issue.

Can you check the response of the sign in request by opening the DevTools panel?

**Comment by JaspalSuri** [comment]
Hello @bigjdunham, I just wanted to follow up with you on this. Are you still experiencing this issue?

**Comment by kushfest** [comment]
I'm having the same issue suddenly when using the iOS app to login to my self-hosted server (docker running on Ubuntu 18). I enter my info and when hitting login I get an "unknown error" pop up. No other info. So I'm not able to use the iOS app at the moment.

**Comment by JaspalSuri** [comment]
Sorry to hear that, @kushfest. 

>self-hosted server
Is it from the legacy syncing-server repo (using Ruby and RoR), syncing-server-JS repo, or the Standalone repo?

**Comment by kushfest** [comment]
> Is it from the legacy syncing-server repo (using Ruby and RoR), syncing-server-JS repo, or the Standalone repo?

Thanks for the quick response! My syncing-server container is standardnotes/syncing-server:latest. Sounds like maybe I need migrate to the newer JS server?

**Comment by JaspalSuri** [comment]
Hi @kushfest, that is correct. [Here are the docs](https://docs.standardnotes.org/self-hosting/getting-started/) on how to set up the new syncing server and how to migrate your database. 🙂

**Comment by kushfest** [comment]
Thanks for the heads up! I just finished the process and I gotta say, it took a lot of trouble-shooting to get it working:

1) Specific container names are used within the docker-compose file, but the 'container name'  is not specified for any of the containers in the docker-compose.yml. When the containers are created their names get appended with '_1' and the names no longer match what's specified in the compose file. I had to add the right container names to every container in the compose file in order get things running. It's an easy fix, but maybe not obvious to everyone and it seems like it should be standard in the compose file.

2) In the database migration instructions, the command to dump my current database into ```dbdump.sql``` resulted in this error:
```mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces```
This appears to be a common problem with mysqldump and required adding ```--no-tablespaces``` to the command.

3) I placed the ```dpdum.sql``` file in ```/data/import``` and everytime i ran ```./server.sh start``` I would get this error no matter what i tried to tweak:
```cannot open directory '/docker-entrypoint-initdb.d/': Permission denied```
This turns out to be another common issue and the solution was to remove the ```dpdump.sql``` from ```/data/import```. I don't entirely understand the reason, but it appears that the ```docker-entrypoint-initdb.d``` directory needs to be empty for everything to startup as desired.

In the end up I started with a clean database, re-registered my account and imported from a current backup file. Not quite database migration, but once I figure out the steps above, I was back in business. Hopefully this info can help others, if they have similar issues.

**Comment by JaspalSuri** [comment]
Hi @kushfest, thank you so much for taking the time to share your experience with migrating over to the new self-hosting setup. I'll forward this over to the dev team for further review so that way they can incorporate it where needed. 🙂

**Comment by bigjdunham** [comment]
It appears my issue was related to using the legacy syncing server, and not the new js version. Updating all of my install locations now to the new syncing server.

**Comment by karolsojko** [comment]
@kushfest thanks for the feedback. I've added explicit container names in here: https://github.com/standardnotes/standalone/commit/d31b61a471f887675030e93a4c192713edd1bf4b

As for the mysqldump permissions - [we recommend to run the standalone docker setup as a root](https://docs.standardnotes.org/self-hosting/docker/#requirements) because container volume management is troublesome otherwise in Docker - mainly the read/write rights transferring.

@bigjdunham yes, legacy syncing server is deprecated and we recommend using our new Standalone Infra setup. Make sure you are using that one: https://docs.standardnotes.org

NOTE: `syncing-server-js` setup is for development purposes only. For self-hosting purposes please use: https://github.com/standardnotes/standalone
