### ISSUE TITLE
[Help Wanted] Token not Matching for 2FA Manager

### ISSUE THREAD

**Issue by cercidiphyllaceae** [standardnotes/forum#1384]
Hi, I would like to use the 2FA Manager Extension to secure my Standard Notes Account. When I enter the Secret Key / scan the QR code I get a different Token than which is displayed in Standard Notes. When I try to enable 2FA I get an error message saying that my token is not matching.

- Standard Notes Client: Linux & Web (Firefox)
- 2FA Manager: Authy (web & desktop) and andOTP

I've never had issues with Authy / andOTP with other providers. (So far I've added ~20 accounts.)

Has anybody had a similar issue / know how I can activate 2FA? Thanks!

![grafik](https://user-images.githubusercontent.com/88078401/127280161-5be42388-fa8c-4835-8a5c-4fe46cae0a45.png)

**Comment by mobitar** [comment]
No issues on our end as far as I'm aware. Be sure that the clocks on both devices are exactly in sync, and try to use a code at the beginning of its 30 second lifecycle rather than the middle or end.

**Comment by ghost** [comment]
Hi,
have the same issue. I tried set 2FA-key manually and with QR-Code, at different times to enter the 2FA code, but didn't work.
Is it normal, that the 2FA-key is the same as the secret key?

- tried at web-app (Firefox 96.0.1) and windows app (win 11)
- Aegis - Authenticator (Android)

Has anybody an idea?

**Comment by stefan-yas** [comment]
Hey @eVlame, I tested this just now but I wasn't successful at replicating your issue using Aegis, Authy or Google Authenticator clients. Could you let me know what happens if you use another authenticator app such as Authy or Google Authenticator? You can switch to your authenticator app of choice, once we get to the bottom of this.

**Comment by atmoio** [comment]
> Is it normal, that the 2FA-key is the same as the secret key?

The secret key should be different from the 6-digit codes that are generated every 30 seconds.

**Comment by ghost** [comment]
Hey @stefan-yas,
yes it worked with Google Auth QR-Code-scanner. 
I wanted to find out, where the bug was. So I tested with Aegis QR-Code scanner and typed it manually. The result was: QR-Code scanner gave me a wrong 6 digit, but typing it in manually got me a right 6 digit. So maybe the scanner of Aegis has a bug, because QR-Code-scanning with Google Auth got me the right 6 digit.

Thanks for the help.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
