### ISSUE TITLE
Error message which overwrites my notes [Help Wanted]

### ISSUE THREAD

**Issue by simon-pesta** [standardnotes/forum#1420]
Hello, 
short time ago, every single note I clicked on showed me an error message, which you can see here: https://ibb.co/1QSPcFJ
It says: 
We´ve detected that this note contains a script or code snippet which may be unsafe to execute. Scripts executed in the editor have the ability to impersonate as the editor to Standard notes. Press Continue to mark this script as safe and proceed, or Cancel to avoid rendering this note. Cancel-Continue

I have no idea why it start to show up and I would by okay with clicking on conitue on each note, but something worse happened- two of the notes already were overwritten with text from another random note. The text is lost, which was two days of work for me. If I click Cancel, no text shows. Please, do you have any idea how to get rid of this?  I use W10 desktop .

**Comment by jbeldia** [comment]
Hi @simon-pesta, I just responded to your email through our help inbox, can I ask you to have a look? :)

**Comment by harrisondesbrosses** [comment]
Hi,

I am not experiencing this message in _every_ note, but it has been popping up on certain notes. Without revealing much, it has been appearing on some of my most sensitive notes, so it is alarming to say the least.

The exact error message is "We've detected that this note contains a script or
code snippet which may be unsafe to execute.
Scripts executed in the editor have the ability to
impersonate as the editor to Standard Notes. Press
Continue to mark this script as safe and proceed,
or Cancel to avoid rendering this note."

Can someone help me figure out what might be going on here? I'd really appreciate it. I thought I'd post here instead of making a new issue.

**Comment by atmoio** [comment]
This alert means that there is a code snippet in your note that when loaded by an editor that can render HTML may be dangerous to execute, if the source of the code snippet is untrusted.

For example if somewhere in your note you have <script>, <html>, it may trigger the alert.

Now in most cases the code should be safe because it's your note, but in the rarest of cases an adversary may trick an unsuspecting user into copy/pasting a code snippet into their note and potentially executing an unsafe script. Any script in the note can masquerade as the editor itself, so gains an equal amount of privileges as the editor (which in most cases is limited to just reading and writing the current note).

**Comment by harrisondesbrosses** [comment]
I just emailed you.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
