### ISSUE TITLE
Issue with tags when creating a note under a subfolder

### ISSUE THREAD

**Issue by hand-made** [standardnotes/forum#1471]
Hi!
I was using the feature about creating a subfolder but  when i create a note under the subfolder, only the tag of the subfolder is added. When I create the same note on other folder and I add manually the tag of the subfolder, the app adds the tag of the main folder and the subfolder also (2 tags in total). ¿Is this the normal behaviour?

**Comment by moughxyz** [comment]
Which behavior do you prefer?

**Comment by alejandrogutierrez12** [comment]
I prefer when the apps only adds the tag of the subfolder, not recursive. 
for example:

I create a note on a subfolder like this

- Personal (folder)
    - Finance (folder)
        - Expenses (Folder)
             *** January 2021 (note created here)** 
   this note only contains the tag: Expenses, but if I create the note under personal and then I remove the personal tag and add the expenses tag, the app will add: "Personal", "Finance" and "Expenses". 

**I prefer the behavior when the app only adds the tag of the subfolder because this is a closer-behavior to a directory in Mac/windows/linux which is what me and I think most of the users are used to**

**Comment by alejandrogutierrez12** [comment]
It looks like now I working good!!

**Comment by jdefleur** [comment]
This is still an issue for me on the MacOS client.

If I right click a note and click "Add Tag" for a tag that's within a subfolder, it automatically adds multiple tags for 

For example, if I have a folder structure "1. Projects > Project A > Section 1", the note is now tagged with "1. Projects", "1. Projects/Project A", and "1. Projects/Project A/Section 1".

I think the note should only be tagged with "1. Projects/Project A/Section 1". Otherwise there's a ton of visual clutter on the tags list, and it requires extra steps to change the note to a new folder since each of these tags needs to be removed individually.

Another issue is now if I drag and drop the entire "Project A" folder from "1. Projects" to "4. Archive", all these notes will still have the "1. Projects" tag, which now makes no sense since they're no longer in that folder.

**Comment by effieeee** [comment]
Hi @PhoenixRising36, for the tagging behavior with folders, you may just need to toggle the parent tagging behavior, found in **Preferences > General > Defaults**. Disabling the option will only apply the chosen tag and not its parent tags.

![image](https://user-images.githubusercontent.com/54989748/199766717-f9141fd1-55c7-466d-8c46-617f5394e80a.png)

As for the issue with what happens to the respective notes' tags when you move a folder, this is still something we need to look into. Will still close this issue since it was resolved with the toggle for the parent tagging behavior 🙏
