### ISSUE TITLE
[Help Wanted] Chose Plus Editor as default, now mobile app is full of code, also laptop app is SUPER SLOW

### ISSUE THREAD

**Issue by garudagirlie** [standardnotes/forum#1493]
I recently upgraded my subscription. I chose 'Plus Editor' as my default editor, and now my mobile app has lost all it's structure, and is full of code instead (along with my text). And If I switch back to 'Plain Editor' as the default, then everything loses structure and becomes full of code, both on the laptop and mobile apps. (Sorry, I'm not a tech gal, so I hope my description makes some sense)

Also, the program has become extremely slow, even with most recent update, taking up to 2 minutes to load the typing I've just done.

**Expected behavior**
I expected to be able have the formatting in effect on my mobile, and to be able to shift back to Plain Editor and have my formatting in effect on the laptop app. I expect to see what I'm typing, on the screen, as I'm typing it

**Screenshots**
![IMG_0019](https://user-images.githubusercontent.com/96272359/146474701-7cfde3a6-2b1e-4b32-86d9-dc3cef125b53.jpeg)

**Desktop (please complete the following information):**
 - OS: Monterey version 12.0.1
 - Browser :chrome & safari
 - Version  C:96.0.4664.110;  S: 15.1
 -SN App version 3.9.10

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 15.1
 - Browser : safari
 - Version 15.1

Thank you!

**Comment by moughxyz** [comment]
Are you using the newer M1 chip MacBooks? If so you should see a performance gain with our next dedicated release for Apple Silicon chips.

Regarding the formatting, the Plus Editor uses HTML under the hood (the code-like syntax). So you have to continue using the Plus Editor for those notes, otherwise the plain editor can't understand that format. You should switch to the Plus Editor on mobile for those notes too. You can set the Plus Editor to be your default on mobile by long pressing on it from the list of editors.

**Comment by myreli** [comment]
It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
