### ISSUE TITLE
Double tags

### ISSUE THREAD

**Issue by bepolymathe** [standardnotes/forum#15]
Hi,

After an importation of .txt files and synchronisation, i have a problem with double tags. 

![capturetags](https://user-images.githubusercontent.com/29939805/28306800-0a060f18-6ba1-11e7-9b64-0f781f44a94e.PNG)

They are exactly the same (no space, etc).

**Comment by mobitar** [comment]
Did you import data into an existing account that had that data? Or was this an import from scratch?

**Comment by bepolymathe** [comment]
I uploaded new files (without tag) into an existing account. But I did not import the same files as those that were already there.

**Comment by mobitar** [comment]
So the data you imported did not contain any tags? Was it data from another account?

**Comment by quartertone** [comment]
I am having this same issue. Using the most recent version of the desktop app (Linux) as of 2019-01-02. I imported several collections of notes from Evernote. The notes themselves were not duplicated, but there are multiple copies of the same tag. I presume this is because each converted file was provided with unique identifiers associated with the tag within that file, and importing the notes resulted in a new set of tags being created each time, even though the tags had the same name.

![image](https://user-images.githubusercontent.com/492588/50591436-23070500-0e3c-11e9-9063-286543ab15fe.png)

I think there should be a way to do one of the following:
* merge duplicate tags
* detect duplicate tags at the time of import so that this does not happen
* batch manager to allow mass-editing of tags (current batch manager only allows deleting notes)

**Comment by mobitar** [comment]
Hmm yeah, the importer will create a new tag with a new unique ID. Merging could be interesting. I agree that it would be nice to have more batch actions for tags. Definitely on the radar.

**Comment by fernandodrf** [comment]
I just noticed the same problem as quartertone, I haven't imported any notes, however I work with different operating systems: windows 10, linux and iOS.

**Comment by mobitar** [comment]
@fernandodrf how many duplicates of the same tag, and what app versions?

**Comment by fernandodrf** [comment]
Hi there @mobitar sorry forgot to mention that:
Linux: 3.0.14
iOS: 3.0.10
Windows: 3.0.1 

I see them double, but not more than that:
![image](https://user-images.githubusercontent.com/716547/60165582-d3f4c800-97ff-11e9-875e-b1b648b23a2b.png)
![image](https://user-images.githubusercontent.com/716547/60165632-e969f200-97ff-11e9-9266-3c8869f08697.png)

My guess is that the windows version does not keep automatically updated, the download time is terrible slow on my office network. So I will stop using the windows version and go with the web app.

**Comment by mobitar** [comment]
If you just see one or two duplicates, that's [quite normal](https://standardnotes.org/help/33/how-do-i-clear-duplicates). 3.0.12 was a big update released to improve on this.
