### ISSUE TITLE
[Help Wanted] Neither appimage or snap is working for me

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [standardnotes/forum#1501]
**Describe the issue**
This is my first time running Standard Notes on linux and it's just one problem after another. No problems with Windows or ios app that I've been using just fine for years.
 
Running standard notes on Manjaro linux for the first time using the appimage just loads an empty blank white screen once you start it. I've tried x86 _64 version 3.9.10, 3.9.12, and 3.9.13 with same issue for all. If you click on the help tab to pull up the error console it does show an error but I don't know how to fix it. Error shown in screenshot, something about "GetKeychainValue". I've also tried clearing the cache and reload button but that doesn't seem to do anything.
![standardnotesappimageerror](https://user-images.githubusercontent.com/97198569/148298917-4810831d-6f34-4786-8940-daef949a13a7.png)

As for the snap version, when you start it, it asks you to pick between using password service or local storage. Clicking on either button does nothing. I can't get past this prompt. The only button that works is the "Learn More" button that expands the text once clicked.
![standardnotessnapissue](https://user-images.githubusercontent.com/97198569/148301324-8eeb62a8-cd35-4dc9-8954-29a2845a9aef.png)

**To Reproduce**
1. Just download either for the first time and run it 
2. Downloaded the snap version from Manjaro's pacman software center though. Appimage from both Standardnotes website and GitHub.

**Desktop (please complete the following information):**
 - OS: Manjaro KDE Linux with Linux Kernal 5.10.89-1
 - Browser Firefox via Flatpak 
 - Version 95.0.2

**Comment by moughxyz** [comment]
Can you see if this helps: https://github.com/shiftkey/desktop/issues/507

**Comment by changemenemo** [comment]
Same problem on my end. 
Since you are using KDE and I have the assumption that the poblem declared itself to me when I've installed kde too, I think it's realted to kdewallet. Which means the snap version is not reacting very well to kdewallet integration.

**Comment by adrihut** [comment]
Hi all! I've been digging into this issue, here are my findings thus far...
<br>

## AppImage version

@SpaceRaccoonFluff, I tested multiple distros (*from Arch, Debian, and RHEL families*) and wasn't able to replicate the blank-screen issue you came across on any of them.

Please let us know if you're still experiencing it with the current version of SN — [**3.11.2**](https://github.com/standardnotes/desktop/releases/download/v3.11.2/standard-notes-3.11.2-linux-x86_64.AppImage).
<br>

## Snap version

### *Password Service Access* setup
A fix for the unresponsive "Use Password Service (Quit)" and "Use Local Storage (Continue)" buttons is already in the works and should be going live soon if all goes as expected.

### The "Use Password Service" setup option
#### Overview
While there does seem to be an issue that's—*at the very least*—adjacent to KDE Wallet Manager, I suspect there may be some underlying (OS config or distro-specific) factors involved as well. I strongly believe this is the case, because installing the Standard Notes snap on different versions of Manjaro's KDE Edition, for example, yields varying results despite the base system being nominally identical.

#### Test results
| OS | Status |
|-|-|
| Debian <sup><sup>11</sup></sup> | ⛔  : Not working |
| Fedora <sup><sup>35 (KDE Spin)</sup></sup> | ✅ : Just works * |
| KDE Neon <sup><sup>5.24 — User Edition</sup></sup> | ⛔  : Not working |
| Kubuntu <sup><sup>21.10</sup></sup> | ⛔  : Not working |
| Manjaro <sup><sup>Minimal (KDE Plasma Edition)</sup></sup> | ✅ : Just works * |
| Manjaro <sup><sup>Minimal LTS (KDE Plasma Edition)</sup></sup> | ⛔  : Not working |
| Manjaro <sup><sup>Standard (KDE Plasma Edition)</sup></sup> | ⛔  : Not working |
| Ubuntu <sup><sup>21.04 (Desktop edition — GNOME)</sup></sup> | ⚠️  : Quick-fix required ** |

\* <sup>**after enabling Snap support**</sup>
\*\* <sup>**`snap connect standard-notes:password-manager-service`**</sup>

#### Observations
- I initially thought the issue was somehow related to the Debian family of OS's, but the fact that the "standard" version of Manjaro's KDE edition isn't working either invalidated this hypothesis.
- Display manager selection (x11/Wayland) doesn't affect testing results.
- The AppImage version of SN works es expected in every single OS I tested.

#### Up next

We'll continue to investigate and try to find out more details about the nature of this behavior, to evaluate if there's any patch that can be applied on our end, or if a potential fix depends on some structural change that would need to be addressed by a third-party.

In the meantime, I'd recommend using the [AppImage version of SN](https://github.com/standardnotes/desktop/releases/download/v3.11.2/standard-notes-3.11.2-linux-x86_64.AppImage) until we're able to gain a more precise understanding of what's happening with the Snap version and decide how address it. *Remember to make the AppImage file executable.*

<br>
<br>

I hope this was helpful! Will be posting updated info as soon as it becomes available.

**Comment by mutable-dan** [comment]
hello
snap on kubuntu 22.04 is an issue. appimage works fine. have not tried flatpak
