### ISSUE TITLE
"Duplicate" no longer working in 3.9.13 (Windows desktop)

### ISSUE THREAD

**Issue by Regina3000** [standardnotes/forum#1505]
**Describe the bug**
I can no longer duplicate a note.

**To Reproduce**
1. Go to a note in SN desktop
2. Click on "Action Bar."
3. Click on "Duplicate."
4. See that note is not duplicated

**Expected behavior**
I expect a copy of a note to be made when I duplicate it.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2, Build 19042.1415
 - Browser: N/A
 - Standard Notes Version 3.9.13

**Comment by moughxyz** [comment]
Action Bar is deprecated and no longer supported, because most of its functions have been moved into the built-in context menu. So you should use the dedicated Duplicate menu item:

<img width="344" alt="Screen Shot 2022-01-11 at 1 21 55 PM" src="https://user-images.githubusercontent.com/3277844/149007655-dac964fb-df7d-4b0f-8871-8266eb6a6b7f.png">

**Comment by Regina3000** [comment]
Thank you!
