### ISSUE TITLE
Can't attach a file

### ISSUE THREAD

**Issue by jiyosub** [standardnotes/forum#151]
Regardless of what browser I use(Mac: Firefox, Brave, Safari, Opera), I can't attach a file. I get the following error:

We're sorry, but something went wrong.

This occurs for both drag and drop as well as using Finder to upload.

**Comment by mobitar** [comment]
Hey Joseph, following up on our email conversation, the current implementation of the File Attacher requires you to link your Dropbox. 

However, we recently removed File Attacher from our Extended offering (for new users), because this was originally built very early on as a proof of concept, and is not always very convenient to use. Not to mention that file attachments are not encrypted. 

So, I've taken it down until I can allocate more time to it, and provide better options than Dropbox, and most importantly, offer encryption of attachments.

**Comment by jiyosub** [comment]
Totally understand.  I'd do the same, not wanting my documents sitting unencrypted with a US company.  Check out Cryptomator.  They have an API, it's full encrypted and sits on top of any cloud provider.

**Comment by DreamFlasher** [comment]
@mobitar Is there a ticket for creating encrypted attachments?

**Comment by mobitar** [comment]
Yes see here: https://github.com/standardnotes/forum/issues/96#issuecomment-368958132

**Comment by cryptosmithio** [comment]
Stale
