### ISSUE TITLE
Conflicted copy error on windows 10

### ISSUE THREAD

**Issue by MadRatera** [standardnotes/forum#1521]
I was editing a long note when suddenly a unwanted duplicate of it appeared out of the blue, showing a red label under it saying there was a "Conflicted copy error", it keeps duplicating itself every 10 minutes more or less.

**To Reproduce**
1. Open standard notes
2. Click on a long note and edit it for some time
3.  It will eventually duplicate itself and show the "Conflicted copy error"

**Expected behavior**
Edit a loong long note without expecting it to form a conflicted army of clones.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 (home ver)
 - Browser: (using the download version for windows, but the main browser is chrome)
 - Version: 3.9.20

**Smartphone (please complete the following information):**
 - Device: it is also conected to a LG-M250ds, the duplicates also appears on the device with the "Conflicted copy error" label, the phone app was closed when I was editing the note on windows, but was running in background.
 - OS: Android 7.0
 - Browser: chrome
 - Version: 3.9.12

**Comment by stefan-yas** [comment]
Hey @MadRatera, this seems like expected behavior as the conflicted copy is being created to ensure no data loss is happening when there are issues with syncing your notes between devices, for various reasons. Perhaps this is due to spotty connection or some other sync error, but this function is there to protect your note progress.

You can read more about it in the [article here](https://standardnotes.com/help/33/how-do-i-clear-duplicates).
