### ISSUE TITLE
Hide markdown/HTML formatting code from previews

### ISSUE THREAD

**Issue by mr-islam** [standardnotes/forum#158]
By previews, I mean on the notes panel (2nd column out of three, between tag and editor columns — just to be clear). Under the titles there is a preview shown, and it is slightly annoying to always have a `#` there. And when using the advanced editor, the HTML tags make the preview completely useless.

It would be great if any of that formatting was hidden from the preview

**Comment by mobitar** [comment]
The thing is, the core application doesn't really understand the nature of the content it is handling. That's because Markdown and HTML are completely handled by external extensions. SN core itself makes no distinction between content types.

Perhaps in the future we could have a some sort of user-inputted regex filtering, or extension-based rendering in the notes list.

**Comment by M-Pixel** [comment]
If editor extensions were required to provide a method for filtering their notes to plain-text (advanced editor filters out tags, markdown editor filters out markdown), then this method could be used both for the previews, and for better search indexing (when I search "strong", I don't want to see every advanced-editor note that has bold items).

**Comment by mobitar** [comment]
Hmm..that would be interesting. But possibly infeasible. Because an extension isn't loaded until a note is selected. If you're scrolling through the All list and pass by a hundred notes, it would be chaos if we loaded up each extension just for filtering. 

Although, I like the idea of an extension made just for filtering text in the notes list. That could be cool.

**Comment by M-Pixel** [comment]
> an extension isn't loaded until a note is selected... it would be chaos if we loaded up each extension just for filtering

I see 23 extensions listed on the website. From what I understand, extensions are almost entirely code and probably some stylesheet, maybe a few images. If you had _all_ of them loaded into memory, I have a hard time imagining that would take any more than a few MB of RAM. Like, 2 maybe? Even 10MB wouldn't be worth fussing about.

Let's say you do want to keep unneeded extensions unloaded - why would 100 notes require 100 extension loads? There are only a handful of editor extensions. I can think of several batching patterns that could make make this feasibly optimized: explicitly sequencing a query of required editor extensions before a second iteration of notes for the actual generation of list/preview nodes, or even refcount- or timeout-based extension loading/unloading.

In fact, how confident are you that foregoing all optimization and just loading/unloading extensions for every note would actually create any noticeable amount of delay for the user?

I haven't read the source code yet, so I'm certainly making several assumptions and can't speak in precise terms, but I hope that all made sense. What do you think?

**Comment by mobitar** [comment]
Hmm good point. Although, what's the broader use here? Meaning, is there a way we can architect some "background" extension services that perform background tasks, including parsing and filtering text in the notes view, and, what else can that do for the app?

Meaning, I don't want to design a whole system based around just filtering note text. I want to generalize it a little more, so that same system can be used in other places of the app. I just haven't thought about what those other applications can be.

**Comment by odyon01** [comment]
Hi, I was wondering about this as well, until I read this item. Is it maybe an option to add to SN the option to just hide previews in the note list? Keeps it more simple/cleaner :) On my phone, I just add 2 line breaks to make it look more clean, but it gives a lot of useless white space. But the Windows app ignores those line breaks, and will just show html-tags.

**Comment by mobitar** [comment]
You can hide note previews on desktop (click Options in the notes list), but not mobile. I imagine this option will make its way into mobile at some point.

**Comment by odyon01** [comment]
Thanks, didn't notice yet that options "button". Works (and now looks) as a charm

**Comment by odyon01** [comment]
Ok, something I thought about just now: If the problem is that you don't want to be processing notes (to filter out the tags) by using some extension or background service, why not store a preview as part of the note? Then you only have to generate the previews once, and when you actually edit the content of the note, that's when you also update the preview-text and this filters-out any markup-tags.

Not sure if I was clear, I can elaborate on it if you want. But I can also understand you don't want to put much effort on this item as not many users mention it. I know however I would be interested in it, as my previews now look like: <p><b>Alternatives</b></p><ul><li>... (and now I just disabled the whole preview as it bothers me too much / adds too much clutter to my list).

**Comment by mobitar** [comment]
Hmmm..interesting idea. The downsides are that we'd be refactoring a lot of core code mainly to service the Plus Editor. Editors now also have to make sure two fields are in sync with each other, which is destined for a mix up every now and then.

I think a "linter" extension somewhere down the road would be a better, more long term solution.

**Comment by odyon01** [comment]
I'm not known with linter extensions et al., but that does sounds like a better solution than mine ;)
