### ISSUE TITLE
Folders to nested tags message

### ISSUE THREAD

**Issue by mailsone** [standardnotes/forum#1584]
I can't find the way to disable message for migration folders to nested tags. I've run migration many times, but message persist on desktop and web app as well. I've upgraded to the latest version as well.
![Screen Shot 2022-04-13 at 5 45 21 pm](https://user-images.githubusercontent.com/88648416/163126758-588ed7e9-11eb-4c3e-aadd-a9f3f2858c32.png)

**Comment by atmoio** [comment]
Lol, well, I suppose it was inevitable that we would meet someone who used dots to prefix their tags with 😄 This is actually how the migration logic works: it checks for any dots in tag names, and wants to convert those to folders. I'm afraid there's no way to hide this right now. You'd have to edit your tag names to not use dots. But I'll make a note to improve this logic so that if the dot appears only once and at the beginning, we shouldn't count it as a migrateable tag.

**Comment by mailsone** [comment]
Great, your answer was helpful! 

I've renamed all tags containing dots in front > run migration > message disappeared! 

Then I've renamed tags again to their original names with dots in front (it was just few tags anyway...)

Hope this can help somebody else as well.

Thanks!
