### ISSUE TITLE
[Help Wanted] Where to report issues correctly?

### ISSUE THREAD

**Issue by cuathro** [standardnotes/forum#1590]
For some time now I have been trying to contribute to StandardNotes by reporting bugs and following up on them. However, **I don't know where I should post the bugs.**

There are repositories for the platform (web, mobile, desktop, source code, offline decryption), extension (editors, themes), standalone projects (filesend, Listed, filesafe) and information (forum, docs). All of them have the "issues" section.

Where should I post the issue when it is an Editor's problem? Do I post it in the desktop application where I suffered the mishap? Do I report it in the editor's repository? Maybe I should report it in this Forum?

From my logic, it should be reported in the corresponding repository (trying to select it accurately and/or in the platform in general in case of not being able to elucidate the error) and this forum should be a space of healthy discussion about interesting topics that have to do with StandardNotes, but not an issue report, am I right?

Perhaps as a suggestion, in each repository should be enabled tags as in this forum, would allow reporting more accurately, helping developers to have clarity between what is a suggestion, question or issue.

Thank you and I hope to clarify this order to help in the best way to the development of this spectacular platform.

**Comment by jmason888** [comment]
I have the same question: I found what appears to be a feature regression on the "Classic Rich Text" (i.e., the Plus Editor). The repositories for the editors seem to be "archived" a few months ago, so [standardnotes/forum](https://github.com/standardnotes/forum/issues) seems to be the only place to report editor bugs, so that's where I opened the issue, but I'm still not sure if this was the right place.

They must have moved the current source code for the editors *somewhere*, so perhaps opening an issue on [standardnotes/app](https://github.com/standardnotes/app/issues) if I can identify the offending code.

**Comment by atmoio** [comment]
All source code is in standardnotes/app, including editors. The forum is the best place to report issues, followed by standardnotes/app.

**Comment by danielfernandez** [comment]
> All source code is in standardnotes/app, including editors. The forum is the best place to report issues, followed by standardnotes/app.

@moughxyz please add some sort of warning about this to other repositories, in the form of a `.github/ISSUE_TEMPLATE.md` or something similar, so that other people are aware. Or simply disable the issue reporting tool for those repos. I've added a couple of tickets to `standardnotes/desktop` thinking that would be the correct place, now to find out it wasn't…

**Comment by atmoio** [comment]
All other repos have been recently archived and are in read-only mode.

**Comment by cuathro** [comment]
Now the doubt is solved, thank you very much @moughxyz
