### ISSUE TITLE
Repeated conflicted copy errors

### ISSUE THREAD

**Issue by michaelding25** [standardnotes/forum#1614]
**Describe the bug**
Each time I try to edit a note, a conflicted copy is created. By just writing out one sentence like this, there may have been 5-10 new conflicted copies for some reason. I imagine it is a syncing error. 

**To Reproduce**
1. Go to any note.
2. Edit that note. 
3. See if there is a conflicted copy error.

**Expected behavior and attempts to debug**
No conflicted copy errors. My internet is working fine and I had no previous syncing issues. I tried signing out locally and signing back in, but the issue remains.

**Desktop (please complete the following information):**
 - OS: macOS Monterey

**Comment by atmoio** [comment]
What version of the app is this with? And is the note plaintext, or a speciality format like markdown or rich text?

**Comment by michaelding25** [comment]
@moughxyz Version 3.0.25 (3.0.25). The notes are in plaintext ("plain editor") and are "protected."

**Comment by FW444** [comment]
I am having the same issue. I am using Plus Editor but the newly created conflicted copies are in Plain. Also, when I click on one of the new conflicted copies to delete them, it creates a new copy, so I have a bunch now and cannot delete them.

Standard Notes iOS app Version 3.3.3, OSX 10.15.7.

**Comment by vtwang** [comment]
It seems this issue is related to these ones as well. 
https://github.com/standardnotes/desktop/issues/672
https://github.com/standardnotes/forum/issues/1438

I'm personally having the issue on desktop version 3.20.0 on Mac, with all editors (plain text, task editor, and external extensions).

@moughxyz If you haven't already, do you think you could raise this with the other devs? Many people have been having this issue for at least a year. Thank you :)

**Comment by adrihut** [comment]
## 📢 [Microupdate : Server status and conflicts](https://blog.standardnotes.com/35571/microupdate-server-status-and-conflicts)

cc @veimon @vtwang @fw444

**Comment by effieeee** [comment]
Issue now resolved as per update on [blog](https://blog.standardnotes.com/35571/microupdate-server-status-and-conflicts)
