### ISSUE TITLE
{"error":{"message":"Not found."}}

### ISSUE THREAD

**Issue by technetiumvault** [standardnotes/forum#1641]
Hi,

I have the following message display in the editor ; 
`{"error":{"message":"Not found."}}`

This happen in this context (all software up to date):

- Windows 10
- Firefox
- using Secure spreedsheet and Markdon basic editor.

It doesn't happend on the same machine, using the standalone Standart Notes App/Programme. So it appear to be a Firefox related issue.

TIA for looking onto this

**Comment by lnsu** [comment]
Hi! Getting the same error as well. I've tried with the latest version of Firefox 101.0.1 64bit and also Chrome 103.0.5060.53 64bit.

On the standalone I'm getting this error: "The extension was not found on your system, possibly because it is still downloading. If the extension doesn't load, try uninstalling then reinstalling the extension."

On Ubuntu 20.04.4 LTS.

Thanks!

**Comment by effieeee** [comment]
I recall this was a temporary server issue, now resolved!
