### ISSUE TITLE
Search no longer displayed at top of Notes & Files column

### ISSUE THREAD

**Issue by godavem** [standardnotes/forum#1648]
In the prior version of Standard Notes on Windows (3.0.15 or 3.4.1, not sure now), I had the Navigation column completely collapsed to the left and there was a search field at the top of my list of notes. Now there is no search field at the top of the notes list, which is very disappointing as I normally have no need of the navigation column. Is there some way to set a preference to get the search field to show at the top of the notes list (as I would strongly prefer to have the navigation panel hidden)? If not, could this be considered a feature request?

Also the columns used to be resizeable. I had to open the dev tools and select the #navigation div to manually resize it and make it visible again just to search my notes.

Thanks for your consideration and all of your hard work in creating this great product!

**Comment by DBCerigo** [comment]
+1 on this. 

I have no use of the navigation side panel - I use Standard Notes (web app) with the navigation side panel completely collapsed. Moving the search field into the navigation side panel means I either have to wastefully use a column of signifiant width to make search easily available and also have significant UI features now visible that I never use, or lose the search functionality, (or resize the navigation panel each time before searching). Given that the main reason I don't need the navigation panel is because I rely so heavily on search instead of tagging or using folders, this change unfortunately combines the two in a way which is detrimental to my usage. 

I'm assuming there is a good reason for moving the search bar into the navigation side panel, as such the ideal solution for myself while adhering to that good reason would be to have a preferences option which enabled the user to choose if the search bar was in the navigation panel or at the top of the notes list (similar for when note "icons" were introduced and turned on by default but there is a preferences option to turn them off). I hope this (or some other solution) can be accommodated. 

Soz for the wordy explanation, and congrats on on the Standard Notes Professional release - great stuff.

**Comment by atmoio** [comment]
If you have the Dynamic Panels theme, this has been updated in the latest version to have a super condensed navigation panel that auto-expands when you hover over it. This might help alleviate the pain for now.

**Comment by effieeee** [comment]
Closing, search is now back on the Notes column!
