### ISSUE TITLE
Spammers going bananas with fake payment notifications

### ISSUE THREAD

**Issue by pantsmasterson** [standardnotes/forum#1658]
Really just a heads up for the team that you're going to start getting a lot of angry emails, potentially -- I've received five different fake "we're about to charge you for our pro version" emails today, each to a different email address. Good luck! 
![image](https://user-images.githubusercontent.com/1688196/180021777-d03ad251-a2f5-4eaa-be8f-94a1a39c7a16.png)

**Comment by adrihut** [comment]
Many thanks for flagging! Please ignore those emails, it's is a mass spam campaign, sadly out of our control. Email providers can help by marking as spam—since it's missing the necessary validation headers.

For context... The way bad actors obtain email addresses for targeting, tends to be public email lists. They then try to validate those addresses against public endpoints like SN's for information regarding account existence for that email. Our public endpoints do not leak account existence data:

> 👉  https://standardnotes.com/help/81/why-am-i-asked-for-2FA-even-though-I-dont-have-it-enabled
