### ISSUE TITLE
v3.23.98 Editor is only half the window when using a small/narrow window

### ISSUE THREAD

**Issue by tab0r** [standardnotes/forum#1705]
![Screenshot from 2022-08-31 10-59-53](https://user-images.githubusercontent.com/4989811/187641768-5053698d-93aa-4bf3-8d22-baf9d095048c.png)
I think the screenshot speaks for itself. But I have a fairly small window, zoomed in, to work on a laptop next to a terminal. Regardless of focus mode or editor, the actual view of the note is less than half the window.

**Comment by myreli** [comment]
Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) the app is now completely responsive 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/17554234/221366136-6f6a252b-4730-4242-8aa6-44e569f37a33.png">

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_

**Comment by tab0r** [comment]
While the new mobile experience is very good, it does not transfer to the desktop app. This is a problem for people (like me) with vision impairments. I'm adding a new screen shot for emphasis. 

![Screenshot from 2023-02-27 12-36-39](https://user-images.githubusercontent.com/4989811/221565947-66d8613d-27d6-41cc-8cfb-c5b611c888f1.png)

I think a potential solution would be including the title/toolbar in what gets "scrolled" as a user writes. So I would like to keep this issue open until a viable solution is implemented.
