### ISSUE TITLE
Simple Markdown stopped working

### ISSUE THREAD

**Issue by tylerzika** [standardnotes/forum#172]
Stopped working for me a few days ago. I'm using Version 2.1.1 (2.1.1).

![mar-01-2018 12-10-40](https://user-images.githubusercontent.com/1011888/36867326-a72b1bc6-1d49-11e8-9000-9adf810843a1.gif)

**Comment by mobitar** [comment]
It looks like you may be using the old version of the editor. Did you get this back when it was free? That will no longer work in the new versions as it has undergone drastic changes. If you have Extended, please try uninstalling then installing the editor again.

**Comment by tylerzika** [comment]
Are there no more free extensions? You need Extended to use them?

**Comment by mobitar** [comment]
Well, the free extensions (which were just the Simple MD and Midnight theme) haven't been touched, but that also means they haven't been upgraded. The extensions infrastructure has changed drastically since then, so I wouldn't even recommend using them anymore in the new versions. Your only bet is to use a much older version of the desktop app, which I also wouldn't recommend. I'd be happy to help ease you into the transition since you were a member of the old system, by offering you our student discount. Shoot me an email if you're interested: mo@standardnotes.org.
