### ISSUE TITLE
Android App Note Authorization

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/forum#1742]
Using your Android App I am running into an issue when waking my relatively slow phone from sleep (with Standard Notes running in the background).

In the app I have:

- Logged in
- Set up fingerprint unlock

I've noticed that if I:

1. Launch the Standard Notes app
2. Unlock using fingerprint
3. View a note in the app
4. Press power button
5. Wake the phone using the power button
6. Unlock the Android lock screen

The Standard Notes app loads and shows the last note for one second. (without a fingerprint being confirmed)

_Please prevent this from happening._

**Comment by myreli** [comment]
Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) these settings were rewritten so the core mobile app now shares the same implementation of all platforms, while keeping its mobile-specific implementations.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
