### ISSUE TITLE
Mobile app does not re-download or update custom themes

### ISSUE THREAD

**Issue by shompoe** [standardnotes/forum#1743]
Mobile version 3.30.33

If I uninstall a custom theme from desktop, and let that sync. to mobile so that I only have the official themes on both devices, and then I re-install the same theme after making some changes to it, the changes are applied on desktop but when the theme re-appears on the menu on mobile it actually uses an old cached copy of the theme from before it was uninstalled. Holding down on the theme and re-download makes no difference.

I was doing the above without advancing the version number of the theme, but discovered this problem when I noticed that mobile was also failing to fetch new versions.

**Comment by myreli** [comment]
Since the [new mobile experience](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon) this has been solved, as the mobile app now shares the same implementation of all platforms.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
