### ISSUE TITLE
New "Note 1" on every launch/refresh of the web app in Firefox

### ISSUE THREAD

**Issue by DominikBritz** [standardnotes/forum#1890]
**Describe the bug**
I'm using Standard Notes on iOS app and on the web app via Firefox. Every time I start the iOS app, a new _Note 1_ gets created. 

**To Reproduce**
1. Start the iOS app
2.  Open Standard Notes in Firefox on desktop
4. See new _Note 1_

**Expected behavior**
No _Note 1_

**Screenshots**
![2020-12-14 08_27_23-Notes · Standard Notes](https://user-images.githubusercontent.com/11243580/102058491-dc740080-3def-11eb-8cd3-c577d3a4b76a.png)

The modified date you see in the screenshot is exactly the time I opened the iOS app.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83

**Smartphone (please complete the following information):**
 - Device: iPhone xs
 - OS: latest
 - Browser: Safari
 - Version latest

**Comment by JaspalSuri** [comment]
Hi @DominikBritz,

Is the app in a tab that is pinned by any chance? Sometimes that results in strange behavior for reasons that currently are not clear to us. Someone on Slack said that they were and we'll see if they stumble across the issue in the future.

Edit: it looks like this issue is similar to standardnotes/forum#2066, and a screenshot by the user shows that they're not using a pinned tab.

**Comment by JaspalSuri** [comment]
Hi Dominik,

Thank you for all of the updates! The dev team has made some enhancements to the web app to better detect when it's in a pinned tab and behave/respond accordingly. 😃 

Have you restarted Firefox at all within those 9 days?

**Comment by myreli** [comment]
Seems like this issue is unlikely to receive more interaction. 

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
