### ISSUE TITLE
Plans to make web app mobile responsive?

### ISSUE THREAD

**Issue by MattDHill** [standardnotes/forum#1905]
Currently, the web app is only formatted for desktop and is non-responsive. Are there plans to make the web app responsive, or would the team be open to a PR that accomplishes this?

**Comment by julianfairfax** [comment]
This is basically all that would be needed for https://github.com/standardnotes/forum/issues/1404, since you could then just use the web version, or build the app for arm and then the same work done on this would apply there. I'd really appreciate just this one change, as apart from it, the site already works on mobile devices, but as you can see in this screenshot, there's a small issue with it not being responsive

![image](https://user-images.githubusercontent.com/43753131/155496026-551065d4-e645-4df2-9e4d-e283c7935dfb.png)

**Comment by julianfairfax** [comment]
I would consider this done by standardnotes/app#1337

**Comment by MattDHill** [comment]
Awesome, looking forward to checking it out!

Likely we will now package Standard Notes for [EmbassyOS](https://github.com/Start9Labs/embassy-os).

**Comment by myreli** [comment]
[Done.](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon)

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
