### ISSUE TITLE
Notes are not being persisted after local environment shut down

### ISSUE THREAD

**Issue by jeet-parekh** [standardnotes/forum#1907]
I discovered standardnotes just last week. It's awesome! Thank you for your efforts.

I have been testing SN by running it locally. I tried both the Docker image and the manual build. Both development and production mode. I have been able to get standardnotes up and running each time.

I discovered that if I shut down the server and bring it back up, it loses my notes. More specifically, after shutting down the server, if I close my browser, then it loses my notes. If I shut down the server and bring it back up without closing my browser in between, then my notes are not lost.

I'm not sure if this is a bug or intended behaviour.

**Comment by myreli** [comment]
Since this issue was opened SN has changed, including its [self-hosting documentation](https://standardnotes.com/help/self-hosting/getting-started). It seems like this issue is unlikely to receive more interaction, so I'll close it.

_(This is a community effort to triage older issues in the forum. If this was a mistake please feel free to re-open the issue.)_
