### ISSUE TITLE
Love the app but please add a manual sync/save option to notes, I keep losing stuff. 

### ISSUE THREAD

**Issue by neverxxever** [standardnotes/forum#195]
Hey guys,

Basically the title. It's happened a couple times now that I've lost something important even though it said "All changes saved" in the corner. This has happened on different computers/platforms and internet connections so I don't think it's problem specific to any of my own setups.

Thanks and keep up the great work

**Comment by mobitar** [comment]
Hey @neverxxever, can you provide more details on this? This is the first time that I'd be hearing about an issue like this, so there aren't any known issues we're aware of. Can you describe the steps you're taking, what you're noticing, what you're missing, what platforms you're using, what version you're on, what extensions you're using, etc. I know it's easy to think "if it happened to me, it must be something normal in the ecosystem", but with issues like this, it's usually really on the individual level, so any details you provide can go a long way in identifying and resolving any issues.

**Comment by neverxxever** [comment]
Hey @mobitar, thanks for your response. 

The issue presents as:
I'll be typing away in a note and, wondering if I am safe to leave it I will check the top right corner to make sure "All changes saved" is displayed. After confirming that it is saved, I will close the app or leave my computer.
Upon viewing the note from another platform (as far as I can tell, always on an app which has been opened after the note was supposedly saved) the note is either missing significant updates (as in, had not updated in a while) or is blank altogether. I haven't yet experienced a note that is simply not there.

This issue goes back some time, it's just that today I experienced it in a way where I lost an entire note which set me back a few hours so I wanted to raise the issue. As far as I know, all of my apps have been kept up to date, the most recent issue occurred with Linux Standard Notes 2.1.26 on an Ubuntu 16.04 LTS x64 system. Everything appeared "synced" when I shut down. I formatted the computer and reinstalled Ubuntu 16.04 LTS/Standard Notes and the note I had been working on was gone.

Other systems I have been using and experienced similar issues in varying degrees (although never this bad, and never with a re-format between viewings of a note) include: macOS Sierra x64, Windows 10 Pro 1607 x64 and iOS 11. I am not using any extensions at present.

Would it be possible to add a manual sync button and/or some sort of check to verify that a document is safe? I saw something about locking documents but I'm not sure if that should be necessary, and it also seems like a hassle to be constantly locking and unlocking these documents. On one hand I'm quite glad that you have never experienced this issue but on the other hand it makes me feel as though we need some sort of fail-safe system in case it does.

Thanks again

**Comment by mobitar** [comment]
Very strange. Haven't heard this issue from anyone before. As far as verifying that a document is synced, that's exactly what All changes saved is for. If it says that, then it's synced. If there's an error syncing, it will say that. What could be happening, given that you're operating on so many devices, is some sort of sync conflict situation where one platform is overriding the other.

Are you able to reproduce this issue at will? That's the only way to diagnose it. Try on one device, go on the other, and see if it's pulled up. When you open another device, it pulls changes on first launch, and then every 30 seconds. On web/desktop, there's a Refresh button in the lower right corner that can be used to pull in the latest changes (you usually never have to interact with that button; it's there just to give people a sanity check.)

If you can replicate this issue with steps, then you've found a goldmine. I've been using this app for 1.5 years on _several_ devices and never had any issues (otherwise they'd be fixed in an instant).

I know bugs don't like to show themselves when you're looking for them, but give it a shot and see if you can duplicate this behavior, and what steps lead to that.

**Comment by mobitar** [comment]
> I formatted the computer and reinstalled Ubuntu 16.04 LTS/Standard Notes and the note I had been working on was gone.

This is so extremely unlikely that it's giving me a headache just thinking about it. It's not possible that the app would report All changes saved incorrectly. Obviously nothing's impossible, but there must be some other explanation. Can you check the sort order and make sure the note isn't just out of view? What do you mean by "gone"? Is the note item there, and missing some text? Or the note is just altogether no where to be found? Can you try searching for it? Can you check on your other devices? It's unlikely a bug like this just would have gone undetected for this long. If none of those apply, can you describe the history of this note? Tagging status, pin status, whether it was archived before, when it was created originally, etc.

Lastly, can you shoot me an email with your account email so I can make sure everything's in good order there? mo@standardnotes.org.

**Comment by mobitar** [comment]
@neverxxever Let me know if you had a chance to look further into this..

**Comment by mobitar** [comment]
I've uncovered an issue last week where under spotty or transitioning network conditions, some sync requests can be dropped, causing some discrepancies. Version 2.1.28 was released on all platforms to fix this issue. I do believe this is what was causing your issue. Technical details [here](https://github.com/standardnotes/web/commit/4d2c61d07cfd4c5be6ae02f56cf3179babb61652). Thanks for your patience on this.
