### ISSUE TITLE
Add password confirmation for registration

### ISSUE THREAD

**Issue by moughxyz** [standardnotes/forum#2115]
When a user clicks the "Register" button, app should present a password confirmation box under the password box with a small note about how important it is they don't forget their password. Then it will have a confirm button that actually submits the registration. This is how the iOS app handles it.

**Comment by xlbrto** [comment]
Quick question! I didn't want to add another issue. I created my account recently because I wanted to try it out, however I would like to change my password, is that possible or how do I go about it? I saw that my encryption key depends on my password so I am assuming I would have to delete everything to make a new one? Thanks.
