### ISSUE TITLE
Bug: iOS app stuck after using TouchID plus copy/paste.

### ISSUE THREAD

**Issue by s0ftwhere** [standardnotes/forum#217]
Hello. I apologise if this has been posted before but I couldn’t find it.

Basically I am using TouchID to lock the app. Every once and while (about every 4th time getting back into the app) it is just stuck on “Fingerprint successful” and it doesn’t let me in. I have to close it completely and open it again for the fingerprint to work. I am going through the following steps to reproduce the problem:

1. Open the app (TouchID works as normal)
2. Create new note with title and text
3. Press home button (app goes to background)
4. Copy text from browser
5. Open Standard Notes again, go to the new note and paste the text (not as title but as content).
6. Repeat steps: 3,4,5
7. Fingerprint gets stuck on the third or forth time pasting new text into the note

Hope I have explained properly. I’ve noticed this since I often have to get information from different websites and paste it into a note.

Also I don’t know if this is possible but it’ll be great if standard notes gets back to the note I had open before switching to another app instead of “all notes”.

I am using iPhone 7 Plus (iOS 11.3.1), free version of Standard Notes.

**Comment by mobitar** [comment]
Hey @s0ftwhere, thanks for the detailed report. I tested your steps using an iPhone X, which uses FaceID instead of TouchID, but it might be the same flow. I wasn't able to reproduce this issue. I'll have to try testing on a simulator, but that won't get the real experience.

One thing I recommend that can solve both of your problems is changing require fingerprint from Immediately to "On Quit" in the settings. This way, when you reopen the app, it's still on the note you left it at, and I'm pretty sure given the lower frequency of requesting your fingerprint, you'll have less issue with the stuck issue.

I do have an older iPhone lying around somewhere. I've made note of this and hope to test it out thoroughly soon.

**Comment by s0ftwhere** [comment]
Hello @mobitar. Thank you so much for the quick and thorough responce.
My only concern with the solution is that all the notes can be accessed if I forget to fully close the app. However, I do see it as a useful solution both for the problem I described and for getting me back to the exact text I was edditing.

Let me know and if you are not able to reproduce the problem and I will try again to see if my steps are correct. I can also send a recording of the exact steps as well. :)

**Comment by mobitar** [comment]
A recording never hurts ;)

**Comment by s0ftwhere** [comment]
Hello @mobitar. As of version 2.1.36 I can no longer reproduce the problem. So I guess you have fixed it somehow.....I don't know if that makes sence based on the changes you've made but I tried everything...

**Comment by mobitar** [comment]
I think it's a race condition. Which is why it can't be reproduced at will. I was able to achieve some funny behavior using FaceID when I really prodded the app. Perhaps the issues are related. In any case, I hope to spend more time with it soon.

**Comment by s0ftwhere** [comment]
That makes sense. Sometimes I was also able to achieve a situation where after creating many notes the “New” bottom becomes “Manage” and you can no longer create new notes but I was not able to reproduce it enough times to record it. Anyway. I hope all of this was helpful and you can find a way to improve the general stability. :)
