### ISSUE TITLE
SN crashes on ISO 16.0.03 + iPhone 14 Pro when attempting to view or create a note which is not plan text

### ISSUE THREAD

**Issue by balashx** [standardnotes/forum#2191]
**Describe the bug**
Attempt to view or create a note on  ISO 16.0.03 + iPhone 14 Pro.  Standard Note crashes immediately.  It is possible to create and view plan text notes. 

**To Reproduce**
1. Go to 'and note that is not plan text'
2. Application crashes

**Expected behavior**
To view Rich Text Notes. Or create a Rich Text Note

**Screenshots**
Application crashes and disappears not possible to obtain an screenshot 

**Smartphone (please complete the following information):**
 - Device:  iPhone 14 Pro
 - OS:  iOS: 16.0.03
 - Browser default browser Safari

**Additional context**

**Comment by retrocaster** [comment]
I noticed the same thing on my Android phone (Pixel 3 and now Pixel 7). The app immediately crashes if I try to open a note that used the "Scratch Editor" (https://dylanonelson.github.io/sn-scratch-editor/). After using a web browser to change the note back to plain text the crash went away. None of my other plain text notes had an issue.

So it seems the bug is likely in code that is not specific to iOS.

And FWIW this only started happening a few days ago.

**Comment by balashx** [comment]
In iOS changing the preference from “Classic mobile experience” to new mobile experience  (Preferences -> General -> Defaults) will stop the application from crashing on RTF.   So it seem they've stopped testing the Classic mode.  A notification would have been nice!!!

**Comment by homberger** [comment]
@balashx Thank you! That workaround works.

**Comment by effieeee** [comment]
Hi @balashx, thanks for mentioning the new UI 🙏Indeed we've been working more on the new UI lately as it's set to replace the old one, so please let us know of any other feedback you have on it!
