### ISSUE TITLE
Duplicated notes and tags on sign in [user stories needed]

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#222]
Hi all,

I saw issues with dups from last year.... still getting them.  took me 2 hours to recover today from dups.  seems to only happen when i log into the web site from browser

1 linux
2 firefox
3 had linux app running 2.1.33
4 android app but not being used 2.1.36
5 after logging in with browser to remove dup extension subscriptions, i had tags duped all over in linux app
6 removed all dup tags
7 started android app, had dup tags and notes, would not sync 
8 emptied cache and data and re-installed android app and finally got them to sync (logging out and uninstalling did not help)
9 now had dup notes and some old notes of existing ones
10 i think everything is cleaned up, but i won't log into the web site again, as this is the third time logging into the web site caused dups

please feel free to contact me directly if it can help
thanks

**Comment by mobitar** [comment]
Hey @WCJLJZUBTSC, sorry about this. This issue is really bewildering. I thought I had a fix in the last deploy, but apparently not. I appreciate all the detail you've provided. The best I can do right now is just collect more clues, as I have no leads as to what is causing this issue. I've looked through every line, but can't determine what is causing this. I've personally never experienced this issue before, which makes it even more difficult to track down.

Can you describe step 5 with more detail? Some questions:

1. You were logged in on Firefox, right? Was this a "stay signed in" session, or a temporary session?
2. When you logged out, did you notice that your data was removed properly from Firefox? Or did some notes linger around after signing out?
3. When you signed in, were tags duplicated on the web as well, or just on Linux?

Any other behavior you observed, no matter how minuscule, can be helpful, so please don't hold back. Lastly, what version of Firefox?

**Comment by WCJLJZUBTSC** [comment]
Hi,

1.
I was logged in using firefox.  I don't remember what type of session it was.
   extensions used: ublock origin, privacy badger, cookie autodelete & adblocker ultimate

2. 
i logged out of the browser (firefox) when i noticed that as i was repairing dups in the desktop app, they were coming back.  when i logged out, i did NOT notice any other sync events, ie nothing else was removed.
as i fixed on the desktop app, the android app was staying in sync with corrections.  the tablet app (android) was correct the next day when i turned it on

3. 
yes, tags were duped on web, desktop app and phone (all were the same) tablet (android) was not in use
there where three types of dups.
   1. exact copies of notes with same tag
   2. exact copies of notes with dup tag names (tags had same displayed spelling)
   3. one or more copies of same note that differed with the same tag

4. 
firefox 60.0, (containers not in use)

more info:
the first time it happened the desktop app was open and then i logged into web
second time, android phone app was running and i logged into web

I will repeat this one point, because it's important, on the second time, i started making fixes to the dups from the web and as fast as i was fixing them, new dups were showing up on desktop (presumably web, but i don't recall).  I logged out of web and started making fixes from desktop and fixes were taking.  i opened the android phone app and the fixes took there too.  I then proceeded to finish fixing from desktop and phone stayed in sync

I hope this, helps, if you need to talk, we can arrange PM or a call.
Please don't hesitate to ask to reach out to me, happy to help

**Comment by mobitar** [comment]
Thanks so much for the details. Really strange. I should also ask: how was your network connectivity during all this? Were you using a VPN? Was syncing happening at a normal speed, or slower than what you were used to?

**Comment by mobitar** [comment]
Thanks so much @roesel for the explicit detail. That is very helpful. So it seems in your case, you have some unique circumstances. And my first task in tracking this down is to isolate what is unique and what is common. This issue has occurred to some dozen users, and so far, here is what's common:

1. It always occurs on sign in.
2. A web browser is always involved.

What is sometimes involved:
1. Existing notes appearing in a session, but the user not being signed in (shouldn't be the case; most likely relates to browser cache missing session parameters)

What is unique in yours:
1. Notes were shown in red as unable to be decrypted.

Now, there was an issue related to this solved a few months ago where when you had red notes, and logged in, it would duplicate them. This issue is fixed, but if your web browser was running what you describe as an older looking version of the app, it might not have had that fix.

In which case, if it didn't have the fix, signing in would put your account data into a duplicated, and hard to reconcile, state.

At this point, I'll just need to collect more evidence and descriptions from other users, and hope that we find the one thing they all share in common. That would then be my best lead. I have, in my several, several months of trying, been unable to reproduce this issue on my end. So there's some unique thing I'm missing. 

One question though:

>  So I closed the tab, opened another and logged in again.

Why did you have to log in again if you just closed the tab? Your login session should still have been active. Did it strike you as unusual that you had to sign in again after closing the tab?

**Comment by mobitar** [comment]
Also, four important questions to add:

1. Was the account password changed recently?
2. Was the Advanced -> "Resync All Items" option used recently?
3. Was data imported from a backup file recently?
4. Was an app passcode lock added or removed recently?

**Comment by roesel** [comment]
To answer the question:

> Why did you have to log in again if you just closed the tab?

I am actually not 100% sure what I did. I might have opened a new tab and attributed the "not logged in" state to a glitch or I might have opened an anonymous window to make sure I have a "clean state" for the second try. I'm sorry but I do not remember.

> Questions 1-4.

No. I don't recall doing any of this ever. Definitely not in the last months.

**Comment by roesel** [comment]
> network connectivity & speed excellent. no vpn. sync speed seemed normal

I second this as well, I was on academic uni internet by cable, so basically the best connection I could ever have.

>  if i understood correctly @roesel said that it occurred in FF but not with chrom(ium). 

While not strictly speaking incorrect, I have never before accessed SN from the Chromium installation, so (at least in my case), there is no way of knowing if it's **browser** related or just  **prior access** related. And I feel like the second seems a lot more likely (although it could just as well be both). It still happened in Firefox, so who knows. 

Firefox version is 61.0b11 btw, I just checked today.

**Comment by mobitar** [comment]
Now that you mention it, Firefox is indeed a frequent suspect. I'll have to reread email reports just to make sure, but Firefox is almost always mentioned. It might have something to do with how FF clears cache, as I know it to be a little different from Chrome behavior.

**Comment by effieeee** [comment]
Closing for now due to inactivity and less reports of duplications as of late. Can be reopened if needed!
