### ISSUE TITLE
Automatic theme switching works poorly on iOS

### ISSUE THREAD

**Issue by magicznyleszek** [standardnotes/forum#2253]
I start with saying that I missed that feature and am glad you've added it. 

There are multiple issues I have:
1. I would expect that theme switching would happen in the background, automatically (😉), based on the system theme. Instead I see that weird popup asking me if I want to keep or apply the theme. I don't want this question, I want this feature to do what it says in the settings: to always use the system theme. 
2. The popup sometimes doesn't show up, and I have the wrong theme being used at the moment. 
3. Sometimes I have multiple popups appearing at the same time. And when the timeout ends, the theme switches. Or rather toggles, as after second popup finishes the countdown, the theme is changed again. 
4. Sometimes during the time of day when system theme would switch, I open the app and see the popup and I don't really know if the app has correct theme set up, and I see the popup, and I don't know if I want to keep or if I want to apply 😅 Like if the app realised it's the time to switch, or is it to early yet. This confusion comes from the fact that the popup doesn't work correctly so it's hard to trust it.

**Comment by effieeee** [comment]
Hi @magicznyleszek, we're sorry to hear that 😞 We initially rolled out a fix for this on v3.45.4, though since you and some other users still seem to be having issues with it, we may need to investigate further. I'll also be closing this since we're already tracking this on [another thread](https://github.com/standardnotes/forum/issues/2229), but feel free to monitor the situation there instead! 🙏
