### ISSUE TITLE
[Help Wanted] Authentication is required to approve this note for Listed

### ISSUE THREAD

**Issue by xthrk** [standardnotes/forum#2267]
**Describe the issue**
I have noticed that every note I want to publish to Listed from Standard Notes now requires authentication:
![grafik](https://user-images.githubusercontent.com/116081825/200172345-94837beb-4b60-4347-b607-d28e861e0cd2.png)

**To Reproduce**
1. Create a new Note
2. Click on Note Menü Button with three dots.
3. Click on Listed actions
4. See Authentication window.

**My Question**
Is this a new default behavior?

**Comment by effieeee** [comment]
@crophit yup, this is the intended behavior on the app now. After you provide authentication, you should be able to properly access and use the listed actions for that note :)

**Comment by andrigamerita** [comment]
Could this behavior be changed? I have a super long random password, so I can't type it by hand, I would have to copy it every time from my password manager (which takes minute to decrypt my database on my phone) to paste it in the app, which is very, very annoying, since the passwords gets asked for every single note (the access is indeed remembered, but only on a by-note basis)

The only way I can think to get around this is to switch to the web app from the native ones whenever I have to access Listed options for a note, because in the browser I can save my password for autofill; but not only is this also slightly annoying, it puts the security of my entire SN account at risk (especially on PC, where the browser passwords are saved completely unencrypted on disk!)
