### ISSUE TITLE
[Help Wanted] Trying to reinstall FileSafe & Alternative Rich Text Editor

### ISSUE THREAD

**Issue by RohsCE** [standardnotes/forum#2269]
In trying to make my notes uniform I preemptively removed FileSafe and Alternative Rich Text Editor all too soon from my extensions. I am now unsure on how to reinstall the extensions. I am struggling to find information about those extensions especially the FileSafe with it being faded out.
Thank you

**Comment by effieeee** [comment]
Hi @skrinskas, a link to install Alternative Rich Text is found in our community plugins repo below:

https://github.com/standardnotes/plugins

FileSafe is also still accessible through its icon on this editor's toolbar 🙏

**Comment by RohsCE** [comment]
> Hi @skrinskas, a link to install Alternative Rich Text is found in our community plugins repo below:
> 
> https://github.com/standardnotes/plugins
> 
> FileSafe is also still accessible through its icon on this editor's toolbar pray

Thank you, I now have bold editor and can see FileSafe, however I am now seeing this message in red when FileSafe is clicked:

Deprecated
FileSafe is deprecated and no longer offered to new users as of February 9th, 2022.
Existing users who have the extension installed, will continue to have access to it indefinitely.

Is there any way to decrypt some old filesafe files that I have without this extension?

**Comment by effieeee** [comment]
Hmm, I'm afraid FileSafe is really needed for those :( However, I've found an install link for the separate FileSafe extension, so please try installing this as well!

https://extensions.standardnotes.org/repos/legacy/filesafe

**Comment by RohsCE** [comment]
I was able to install it, unfortunately it did not change the deprecated message. Thank you very much for trying regardless!

**Comment by effieeee** [comment]
Hmm, that's odd 😢Though you have already used FileSafe prior to its deprecation earlier this year, yes? Do you perhaps have any backup files from before you removed FileSafe from your extensions repo? (If you use the desktop app, you might find an automatically generated backup file by opening the top menu of the app, then choose **Backups > Open Backups Location**

**Comment by RohsCE** [comment]
Yes I used filesafe for maybe a year. I am not sure why I didn't think of importing a backup! I have had backups since over a year ago. I suppose I didn't realize that a backup would contain the extension information aswell. Thank you, I was able to decrypt everything I needed by re-uploading the filesafe folder to a google drive account and connecting that way. The deprecated message is gone. I appreciate you 🙏

**Comment by zero-thermo** [comment]
Hello. FileSafe was not working in my app, and the Standard Notes error message recommended uninstalling and reinstalling. I've tried the following with the Linux AppImage desktop app:
1. Reinstalling FileSafe via https://extensions.standardnotes.org/repos/legacy/filesafe
2. Restoring a previous backup from before I removed the FileSafe extension

In both cases, I still cannot see FileSafe in the action bar despite FileSafe showing up as one of my extensions in Settings ==> General ==> Advanced Options.

What else should I try to regain access to FileSafe files?

**Comment by effieeee** [comment]
Hi @zero-thermo, are you also unable to see the FileSafe extension on the web app? (app.standardnotes.com)

How about through the Alternative Rich Text editor, as mentioned in my [other comment](https://github.com/standardnotes/forum/issues/2269#issuecomment-1305784326) above?

**Comment by zero-thermo** [comment]
Thanks for taking a look @effieeee.

I still do not see the FileSafe extension in the web app, but can access it via the Alternative Rich Text editor. Is there any way to get the main FileSafe back, or is this now the only way to retrieve those files?

Regardless, it sounds like I am better off downloading all of the FileSafe files and reuploading them with the new Files feature. Is there any way to search for all notes with FileSafe attachments so that I can download them all?

**Comment by effieeee** [comment]
I see 😞 While there isn't a way to filter notes with FileSafe attachments per se, you can at least set up a **Smart View** to show only notes that use the **Alternative Rich Text** editor, since this is the only one which could work with FileSafe attachments inline:

![image](https://user-images.githubusercontent.com/54989748/206723091-04ae7843-6724-43c8-a94c-371c1186c2c3.png)

Once it's been saved, you can click on it in your **Views** section to filter out only notes which use that editor:

![image](https://user-images.githubusercontent.com/54989748/206723269-403a2eaa-1736-4323-90be-eec0e4baec0d.png)
