### ISSUE TITLE
A way to select multiple tags on OSX client

### ISSUE THREAD

**Issue by frego** [standardnotes/forum#230]
It would be nice to be able to select multiple tags on the tag column on the left.

**Comment by mobitar** [comment]
Indeed it would be :) No way to do this now, would require large architectural changes, but it's definitely on my mind.

**Comment by christianhans** [comment]
Would it be possible to include tags in the search? I.e. one could filter for `#tag1` and then search for `#tag2`.

**Comment by mobitar** [comment]
@christianhans can you elaborate more? So you would select #tag1 from the tags panel, then type #tag2 in the search box? What would the expected results be?

**Comment by christianhans** [comment]
Sure. My intend is to find notes that have **both** tags. So selecting tag `#tag1` and then searching for `#tag2` will show only notes that have both tags. I guess it would make sense to open a separate issue (to make tags searchable from the search bar)?

**Comment by mobitar** [comment]
Some thoughts here: https://github.com/standardnotes/forum/issues/280#issuecomment-445571331

**Comment by christianhans** [comment]
I think being able to search for tags would be an *awesome* intuitive feature. Otherwise I would suggest changing the behavior on mobile to not combine multiple selected tags with OR logic but with AND logic (only show notes that have both tags). Desktop would need to get that same multiple tag selection feature then as well. But again, just being able to search for tags sounds more intuitive to me (and allows for more use cases).

Best
Christian

**Comment by effieeee** [comment]
Will continue tracking here: https://github.com/standardnotes/forum/issues/280
