### ISSUE TITLE
Logged in but can't read /open my notes (including non-password protected ones)

### ISSUE THREAD

**Issue by json-pierce** [standardnotes/forum#2319]
I am using Standard Notes free /basic plan on Windows 11 using a 12th Gen Framework Laptop and I cannot open any of my notes.  I can login successfully, but I can not read my notes.

I uninstalled the program and reinstalled the program; it's didn't solve the problem.
I CAN open standard notes on my iPhone and another PC computer.

Please help!

**Comment by effieeee** [comment]
Hi @jeisonc83, is it possible that this is might be an issue with the UI? I noticed some similar reports in the inbox which mention similar issues, though it turns out that the note editing panel was hidden upon opening the app. Can I ask you to check if you're able to click and drag on the right most margin to reveal the note editing pane, as in the video below?

https://user-images.githubusercontent.com/54989748/205339028-5fd16e73-97b9-4d1d-95e9-6272ec9d59b3.mp4

**Comment by json-pierce** [comment]
Hello Effie,

Thank you so much for your response. Your solution worked for me :)
When I use my 12" screen laptop, and tinkered with the three column widths, I can now see them all.

Thank you again!

Kindly,
Jason

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
