### ISSUE TITLE
[Help Wanted] Install extensions

### ISSUE THREAD

**Issue by stkr22** [standardnotes/forum#2324]
**Describe the issue**
I am using Standard Notes for many years now as a pro subscriber and it used be quite
straightforward and easy to install and use extensions. Just go to
settings > advanced and choose the one you want to use.

However, recently I noted that the "Advanced Checklist" extension was
marked as "[Alpha]" in iOS and stopped working. I thought "Maybe
reinstalling helps" and then realized I could not reinstall it via
settings > advanced.

I spent quite some time researching reading different help/issue pages
like:

- https://standardnotes.com/help/77
- https://standardnotes.com/features
- https://github.com/standardnotes/forum/issues/1476
- https://github.com/standardnotes/forum/issues/1540

I also found this page:

- https://github.com/standardnotes/plugins

While reading through this I got the impression I really missed out on
some developments within the Standard Notes subscription model. Can you
help me here?

- Like what plugins/extensions are available to me as a Pro subscriber
by default(coming from the Standard Notes team)? 
- Some pages said something about third party extensions, where do I
find these third party extensions? 
  - How do I know if they are save to use?
- What about the plugins github repository(on the author field it often
says "retired")? Advanced Checklist seems to not work on iOS.

Wrote the same as mail to the standard notes support like two weeks ago but did not get an answer.

**Comment by effieeee** [comment]
Hi @stkr22, indeed the extensions system works quite differently at the moment. Essentially, all extensions that come with your Professional Plan are already automatically downloaded and made available for you on the app. The "Compare features" section of the pricing page on our website will show you which particular features are made available for you on the app.

About 3rd party extensions, while there isn't a commonly agreed place to collate them, there is one repository in GitHub that has quite a lot of them: https://github.com/jonhadfield/awesome-standard-notes. Since we're really unable to review any 3rd party extensions though, we can never truly guarantee safety or privacy for any of them 😞 If you'd like to try installing one though, you will need to do so as instructed below:

1. Take note of the **install link** for the extension you'd like to install.
2. Click on the **Open Preferences** icon at the bottom left of the app
3. Click on **General** on the left hand side, then click on the **Advanced settings** dropdown menu
4. Scroll down to the box labelled, **Install external packages**, then paste the link to install your chosen extension

Retired extensions would be the deprecated extensions that were once offered as part of the subscriptions. You can find some of them in the [community plugins repository](https://github.com/standardnotes/plugins) which you also linked above! You can install these in the same manner as a 3rd party extension.

**Comment by stkr22** [comment]
Hi @effieeee, 

Thank you so much!! That really helps. 😃🙌

Is there a way to link or show your explanation in the docs? That might help others, maybe I am not the only one wondering how that now works.

**Comment by philipmobrien** [comment]
Got to agree, this explanation should just be part of the sn documentation. Nice and clear, easy to follow.

**Comment by effieeee** [comment]
Glad it helped, though yes, I'll take note that this could be added as part of the help page too 😅 Closing this now!
