### ISSUE TITLE
Too easy to accidentally select multiple notes | iOS

### ISSUE THREAD

**Issue by r-i-v-a** [standardnotes/forum#2338]
**Describe the bug**
Since the UI overhaul on the iOS app, clicking on a note in list view will often accidentally select multiple notes instead of opening the note that was clicked on. I'm not even sure what the difference in gesture is; it seems non-deterministic.

**To Reproduce**
- Be on the main view listing all notes
- Click on notes to open them
- Sometimes this opens the note in the editor; other times it goes into multi-select mode
- Once in multi-select mode, it is hard to exit and select a single note again

**Expected behavior**
I would expect different gestures to click on note to open vs. select multiple notes. Actually, the old / simpler UI without multi-selection was preferable to the new UI.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 16.1.1
 - Browser: n/a, using the app
 - Version: v3.120.2 (393)

**Comment by feinersaft** [comment]
I would also agree to this. I think, it is too easy to select multiple notes.

**Comment by effieeee** [comment]
Been trying to reproduce this as well, though I noticed I could only trigger it when selecting **Checklist** notes so far. Is this still happening on your end with v3.125.0?

**Comment by txkxgit** [comment]
Same here. Since the UI overhaul I constantly find myself accidentally ending up having multiple notes selected. There should be a way to at least deselect the current selection

**Comment by ryansytsma** [comment]
The iOS version is unusable because I cannot switch notes without multiple notes being selected. I have to close and re-open the app to switch notes.

**Comment by fredlunau** [comment]
Ditto here.  A setting to turn off multiple notes selected (don't need that feature) would be great.

**Comment by pasteleraser71** [comment]
I have the same issue ever since the UI redesign couple months ago.  I have waited for minor releases to fix it but no change has been made.  I can consistently reproduce by using the search function.  Steps to reproduce:

Open app.
Open a note.
Hit the back arrow to return to the notes list.
Use the search function.
Open a note from search results.
The note that is opened is not the note that I select.  It is the note that was first opened before running the search.
Hit back to return to search results.
Hit back to return to main note list.
The app now will not open notes, it just selects multiple notes after pressing on them.
Returning to the search function in this state, no notes in search results can be opened and no reaction is seen on screen when pressing on notes.

Sometimes I can get out of the broken state by pressing and holding one note until the extra options come up, then hit the X to exit the extra options.  Usually, I have to shut down the app and then reopen it.  Right now, even shutting down the app and reopening it still shows multiple notes selected.  In this condition, it seems letting the phone screen go to sleep and then reopening the app sometimes solves it.  Although I can reproduce the problem condition consistently, I cannot consistently get out of the broken state, which makes this bug especially troublesome.

If I open the app from a fresh start while it is not broken, the search function does allow opening notes in search results, as long as I don't open any notes before running the search function.

If selecting multiple notes is an intended feature, I don't see the usability of it unless a mouse and keyboard are connected to the device.  
    
Device: iPhone SE 1st Generation
OS: iOS 15.7.2
Browser: n/a, using the app
Version: v3.132.2 (444)

**Comment by effieeee** [comment]
Hi all, we’re planning to disable multiple selection for the mobile apps in an upcoming update. Apologies for the trouble!

**Comment by pasteleraser71** [comment]
@effieeee Thanks!

**Comment by r-i-v-a** [comment]
@effieeee Thank you! The problem seems to be fixed in recent versions of the iOS app.
