### ISSUE TITLE
Untagged documentation doesn't actually explain how to filter untagged items

### ISSUE THREAD

**Issue by nathanmerrill** [standardnotes/forum#2343]
**Describe the bug**
I found this article: https://standardnotes.com/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters

It has great documentation on how to create dynamic filters.  However, it doesn't actually contain an example of how to do untagged notes and I'm not seeing an easy way to do it.  All of the operators are inclusive operators.  I don't see a "not" operator or "notincludes".  As far as I can tell, "includes" is the only operator for tags, which is what I don't want.

**Comment by effieeee** [comment]
Hi @nathanmerrill, this article actually needs a lot of updates, since we now have a **Smart View builder** to help make things a bit easier 😅 You can find it under **Preferences > General > Smart Views** 

![image](https://user-images.githubusercontent.com/54989748/207643268-c2143549-1c10-4e4c-86d0-685d5272a7df.png)

**Comment by nathanmerrill** [comment]
Yeah, I noticed it was a bit different, I assumed that the text in the documentation was an alternative way of writing the json.

That said, I think I've figured out how to do this (though it replicates the existing Untagged filter), so I'll post it here for future reference:
```

{
  "operator": "not",
  "value": {
	"keypath": "tags",
	"operator": "includes",
	"value": {
	  "keypath": "title",
	  "operator": "!=",
	  "value": ""
	}
  }
}
```
