### ISSUE TITLE
[Help Wanted] Smart View filter for FileSafe items?

### ISSUE THREAD

**Issue by tiddesk** [standardnotes/forum#2364]
**Describe the issue**
I'm attempting to migrate my various file attachments from file safe to the new linked files interface. Is there a query I can write for smart views that will display all my notes with filesafe attachments so I can move through them systematically? TIA!

**Comment by shompoe** [comment]
This same question was asked a long time ago in #262 and the answer was no, it's not possible.

**Comment by effieeee** [comment]
Hi @tiddesk, while you cannot create a Smart View that displays notes with FileSafe items per se, it might still help to set up one that displays only **Alternative Rich Text** notes, since this is the only editor where FileSafe works. As long as you have Alternative Rich Text installed, you should be able to set up the Smart View as shown below:

![image](https://user-images.githubusercontent.com/54989748/210089123-2e4c6616-78da-47f7-aed8-b7fbd3e98217.png)

**Comment by tiddesk** [comment]
> Hi @tiddesk, while you cannot create a Smart View that displays notes with FileSafe items per se, it might still help to set up one that displays only **Alternative Rich Text** notes, since this is the only editor where FileSafe works. As long as you have Alternative Rich Text installed, you should be able to set up the Smart View as shown below:
> 
> ![image](https://user-images.githubusercontent.com/54989748/210089123-2e4c6616-78da-47f7-aed8-b7fbd3e98217.png)

This got me what I needed. Thanks!
