### ISSUE TITLE
No landscape mode in iOS.

### ISSUE THREAD

**Issue by ealeksejev** [standardnotes/forum#2383]
**Describe the bug**

No landscape mode in iOS.

**To Reproduce**
1. Open StandardNotes
2. Rotate iPhone on its side
3. Nothing happens ...

**Expected behavior**
Displays content in landscape mode.

**Smartphone (please complete the following information):**
 - iPhone 13
 - OS:  iOS 16.1.2

**Comment by effieeee** [comment]
I’m afraid landscape mode for the mobile app was [disabled](https://github.com/standardnotes/app/commit/a365c17c46f38e6d8cacade47542fd4ec625bc0d) in an earlier version.

**Comment by kooshiel** [comment]
Why was landscape mode disabled? The app has become far less useful to me since this change was made. I type with the landscape keyboard, so now I need to open up the iOS notes app, type out my note, then copy and paste it into Standard Notes. Obviously, this is very inconvenient and has majorly downgraded the quality of my experience with the app.
