### ISSUE TITLE
Self hosted with subscription enabled but "Unlock features" in app v3.141.0 android

### ISSUE THREAD

**Issue by drapado** [standardnotes/forum#2427]
I just updated to v3.141.0. I self host it and have subscription activated in my accound (ends in 2243). After the update, I can't edit spreadsheets in android, and I see the banner to "Unlock features". This was not happening before the update.

**Comment by MrToast72** [comment]
Just updated my desktop app on my main PC running Pop OS, I got the same issue as well. Cant edit or do anything counted as a "paid feature" even though I self host my sync server and my web app. Only the web app I host does not show the "unlock features". I rolled back my app on linux by downloading a older version from their repo. Not sure if this is standard notes pushing people towards paying for even the self hosted version but that is what it kinda feels here. I would rather be wrong though...

**Comment by hutcheon** [comment]
There's been a recent uptick in changes that seem to be hostile to self-hosters, and in my opinion, damage the mission of Standard Notes.  This recent paywall is a great example, but back in November, all the open-source server components were shutdown, switching to closed source self-hosting services.  Not to mention the shuttering of the Standard File protocol.

Standard Notes's philosophy says that my notes should be there for me in 100 years, but these actions are not following that.  If the focus was truly on having my notes available in 100 years, they would be pushing for public standards (not shutting them down), open source clients and servers (not closed source that won't outlive the company), and encouraging self-hosting, all to spread the technology widely.

**Comment by AdamXweb** [comment]
Issue also present on iOS

**Comment by vongoethe** [comment]
They changed the subscription policy for self-hosted servers.
It now needs an "offline subscription" to get the full feature of the self-hosted servers.

**Comment by drapado** [comment]
@vongoethe do you have a source for this? Is it possible to config your self-hosted server to solve it? Or just rolling to a previous client app version?

**Comment by AdamXweb** [comment]
Don't think they announced it, but their site has this: https://standardnotes.com/help/48/can-i-use-extensions-with-a-self-hosted-server

**Comment by drapado** [comment]
39$ per year wtf. Well, time to look for an alternative to SN I guess

**Comment by AdamXweb** [comment]
Thats's what I was thinking, but I'm sure if there's enough backlash from users they should consider backtracking.
I don't see the value of $39, especially as they were offering ~$45/5 years for some users with a hosted solution..

**Comment by drapado** [comment]
They changed the pricing system in 2021, right? I don't think they offer that deal right now. The premium plan prices are rather high right now. Probably, they're losing money and want to reverse course. But I don't know if what they offer is valued at 90$ per year. Probably they want to get some extra bucks from self-hosted. I wonder what their subscriptions numbers are right now.

**Comment by drapado** [comment]
Link to thread in HN: https://news.ycombinator.com/item?id=34578045
Indeed, with enough backlash they might consider backtracking.

**Comment by vongoethe** [comment]
> @vongoethe do you have a source for this? Is it possible to config your self-hosted server to solve it? Or just rolling to a previous client app version?

They post it on their site. And you can revert to previous client before 3.140.x to avoid this.
This policy really sucks and I'm looking for alternatives now.

**Comment by AdamXweb** [comment]
Its so silly, and the fact that lets say on iOS, you can't downgrade. Especially with their patch notes not giving any information about subscriptions or even a heads up. Seems like it is being swept under the rug as a way to raise revenue rather than be truly open and public.
Bitwarden has a similar setup, where they charge for an offline subscription, however they don't lock out the clients if people choose to host Vaultwarden or similar.
A better strategy would have been to publicly announce a date when users self-hosing would be expected to pay or expect changes.
The past few months have really been a struggle self-hosting, and may look into going back to Joplin or an alternative..

For anyone interested, looks like [this was the merge](https://github.com/standardnotes/app/commit/3a204cdcc83254824a6fe0a87283d6a6db4da0e3) that broke self-hosting

**Comment by hutcheon** [comment]
> 39$ per year wtf. Well, time to look for an alternative to SN I guess

Raising prices is one thing (though $120/yr pro version seems to be well above other options in the market), but putting significant development time towards building a new licensing system, specifically targeting a niche subset of your customers, is opposed to their ["We are complexity bigots" / "We say no to most feature requests"](https://standardnotes.com/longevity) mission statements (and I still can't search within a note).

This is exactly the behaviour a failing company would do: grasp at all potential sources of revenue.  Doesn't give me confidence that they, or my notes, will be around in 100 years.

**Comment by drapado** [comment]
The worst part of all these startups is that they promise X, like full self-hosting in this case. Then, once they have enough user base and/or investors start asking for money, the pull the plug on those features. Just be honest from the beginning, if offering and maintaining a self-hosted solution is not profitable for you, don't offer it in the first place.

Luckily, the app is open source (if I'm not mistaken). Therefore, someone could fork it and remove the paywall.

**Comment by AdamXweb** [comment]
For Android yes, but iOS users will be in the dark, depending how hard baked the paywalls are..

**Comment by deljones** [comment]
I too self host using yunohost. The only thing working is writing notes and sync and that’s it. I can’t use Listed, can’t use Cloud backup, upload and downloading files is hit and miss. The iOS app won’t even attempt uploads! I’ve raised all of these on the various forums but silence. I paid the 39 bucks, which I don’t mind if the self hosted version works but I’m wondering what the point of the yunohost version is as 80% of it doesn’t work. Yes I realise that the money goes to SN and not the devs at YNH, and SN do say that they only support the Docker version for self hosting, and yes we are relying on volunteers to make it happen for which for my part I’m greatful, and I mean that. It all seems a bit all over the place to me, a normal user. I’ll be cancelling the next 39 bucks as it gets taken automatically so if you’ve done it make sure you cancel at least 90days before. The point is the 39 bucks offline key helps pay toward the development of the paid version because despite two updates in two weeks I’ve seen no difference in stuff working. I love the app but for self hosting it’s a bit mugggh! Not great support unless you are using docker. The paid for version, for what you get is also well over priced. Just saying.

So coming back to topic, I’ve done an update to both server and app, thinking that this is it, we will have more stuff working instead I too now see an upgrade splash screen to use stuff that was kind of working before, even though I have an offline code and I’m self hosting. It certainly looks like self hosted folk are getting a bit of a kicking or at the very least poor support. 

Dj

**Comment by deljones** [comment]
> > 39$ per year wtf. Well, time to look for an alternative to SN I guess
> 
> Raising prices is one thing (though $120/yr pro version seems to be well above other options in the market), but putting significant development time towards building a new licensing system, specifically targeting a niche subset of your customers, is opposed to their ["We are complexity bigots" / "We say no to most feature requests"](https://standardnotes.com/longevity) mission statements (and I still can't search within a note).
> 
> This is exactly the behaviour a failing company would do: grasp at all potential sources of revenue. Doesn't give me confidence that they, or my notes, will be around in 100 years.

I’ve just read that. Odd mission statement that. Hmmm.

**Comment by drapado** [comment]
Apparently, they're giving lifetime licenses to people self-hosting before the change. Check the discord channel. I'm closing the issue as it's not a bug.
