### ISSUE TITLE
[feature request] Rendered notes - font size option

### ISSUE THREAD

**Issue by greiggy** [standardnotes/forum#252]
For some uses e.g. speaking notes I find the rendered size of SN notes a bit small on my iPad. Any possibility of an option on appearing size? I'd like my favourite font  as well, but that's just being picky...

**Comment by mobitar** [comment]
Ideally we'd have the app respect the system settings for font size. I thought this was the case, but after testing now it looks like it's not respected. I'll have a look at this and see if there's an easy solution. Otherwise, we'll have to wait until the mobile apps support some sort of custom preferences. The first of which will definitely be a font size option.

**Comment by greiggy** [comment]
Plus editor font size isn't changing the size. Size appears fixed...

**Comment by mobitar** [comment]
Ah, for editors, that will be a different story. The app doesn't directly control those. Most likely a custom theme will be required.

**Comment by effieeee** [comment]
Font size can now be changed for Plain Text notes, and there don't appear to be any issues with changing font sizes on Rich Text so far!
