### ISSUE TITLE
SN Windows won't access data

### ISSUE THREAD

**Issue by greiggy** [standardnotes/forum#278]
I use SN between Mac, iOS and Windows 10 and it is particularly valuable for bringing notes to a project being worked on in Windows. So, thanks for that very good facility... However I am finding that SN refuses to access data. It shows the 'private window or another instance of SN open' dialogue. Even when SN on Windows is the only one open or opening. Quitting and opening again is not a remedy. 

As an aside, I feel that SN should be able to carry out a sync with other related SN apps open. This would be usual with other notes apps.  Meanwhile I can use Simplenote which is rock solid, but SN has the additional ability to handle rich text which is better - when it works.

Something to work on?

**Comment by mobitar** [comment]
Well you can only have one instance of the desktop open at a time. This is because if two instances try to access the database at the same time, corruption can happen. This is mostly out of our control, and is related to the underlying database technology. 

There may be some sort of "ghost" instance running. Can you try opening the task manager and seeing if you can terminate any references of a Standard Notes process?
