### ISSUE TITLE
No keystroke to open new note?

### ISSUE THREAD

**Issue by wlbentley** [standardnotes/forum#288]
In the MacOS desktop version (not Extended), I'm surprised to find that I must use the mouse to open a new note. Will there be support for basic keyboard operations?

Thanks.

**Comment by mobitar** [comment]
Please see this: https://github.com/standardnotes/forum/issues/39

**Comment by Soleone** [comment]
Hi, I noticed the other issue has been closed. What is the right place to discuss the topic of keyboard shortcuts. For a lot of power users like myself this is a big problem and my only gripe with an otherwise nearly perfect app.

I guess the app being super cross platform might make things more complicated. But I would really love to see this prioritized or at least have a place to properly discuss this and potential workarounds and so on.

Is there an opportunity for pull requests here? If so then that might require some context on what the current problems are why it wasn't straightforward to implement yet.

As an example on my Mac I find myself hitting CMD + H all the time trying to hide the app in the background and instead of doing that default Mac behaviour it instead it changes the current line to a header via `#`, but this only happens in advanced markdown editor that I'm normally using.

Apart from that small gripe, I would really like to see:

* Global shortcut to bring standardnotes to foreground (really important for some people's workflow to use this as a braindump without having to touch the mouse)
* Shortcut to focus search while editing a note, for quicker navigation between notes
* Shortcut like CMD+F to search for text within a note

**Comment by mobitar** [comment]
There hasn't been any new thought on this topic since #39 was closed. It was recently discussed in the [Slack group](https://standardnotes.org/slack) and here were my thoughts (and especially why a PR wouldn't work):

I experimented with keyboard shortcuts maybe a year ago, and what was supposed to be a simple undertaking eventually began to be a very complex problem. One is, navigating between contexts. When you press up and down, it needs to determine if you mean tags, notes, or editor. Another issue is extensions. How do we get the Folders component to respond to shortcuts? Another problem—how do we let the user customize shortcuts? We’d need to allow users to record a custom pattern for a shortcut. I tried doing that in native JS, but it proved tricky. mousetrap (https://github.com/ccampbell/mousetrap) was a nice solution, but involves including an external dependency. Another problem was, how do we let extensions define their own events to map to a shortcut? For example, we’d want FileSafe to register an event called ‘upload-file’, and we’d want the keyboard shortcut manager to be able to map a shortcut to that.

All of this, in my opinion, is keyboard shortcuts done right, and it’s a huge, huge undertaking. This is why it’s not already done.

**Comment by Soleone** [comment]
Thanks, appreciate the update!

I understand it will be a lot of work. Just want to iterate one more time that this is one of the most important features for a lot of users. But I'm sure you have many other features on the priority list as well. :) Best of luck with everything!

Random note while I'm here: Another blocker for some people seem to be better attachment support from what I've heard, but I don't have that use case so I don't have any more details on that.

**Comment by mobitar** [comment]
Yup, better attachment support is a big one :)

**Comment by bschlagel** [comment]
Just want to respectfully echo the request for keyboard shortcuts as my biggest blocker to adopting SN over Simplenote or nvAlt.

I wonder if there's a way to iterate towards full support here. Personally I'd be very happy with some simple defaults for things like new note, navigation, and search, on par with Simplenote (quite basic shortcuts) or nvAlt (let's call that intermediate level shortcuts).

User-customizable shortcuts would be a nice extra, but I can see that adding a ton of complexity, and seems like a far less essential feature. If it might be possible to add basic shortcuts, and punt on full user-customizability (ditto additional shortcuts for lesser used extensions etc.), I think that's still far better than no shortcuts at all. Totally understand there are underlying architectural challenges here though. Thanks for considering!

**Comment by mobitar** [comment]
There are some experimental shortcuts available now. 

- cmd + ctrl + n will create a new note
- cmd + delete to trash
- cmd + alt + shift + delete to permanently delete
- cmd + shift + f to focus search field
- alt/option while Menu open to show alternative options.
- up/down to navigate between notes

The equivalent on Windows, but I've heard reports that not all shortcuts work on Windows. Will need to investigate. There's also the tricky problem that these shortcuts do not work if the current context is inside an extension. That is, if the cursor is blinking inside, say, the Advanced Markdown Editor, none of these shortcuts will work. You'd have to click outside of the extension, on a native UI element. Not ideal, but also why we haven't really publicized these shortcuts until these problems are solved.

**Comment by bschlagel** [comment]
Awesome, thanks @mobitar this seems like a great start!

Testing these, and some feedback/suggestions:
- cmd + L could be a good additional shortcut for global search due to muscle memory with web browsers and other note taking apps (cmd + F for in-note search makes a lot of sense along with cmd + shift + F for global search, so keeping that too seems 👍!)
- cmd + shift + N for new note (or even just cmd + N) might feel a bit more natural for new note
- a way to quickly toggle between views / notes list / active note could be great…maybe something like cmd + 1, cmd + 2, and cmd + 3 (in the first, up/down arrow could navigate views/tags too…perhaps even left/right arrows to go between these?)
- minor glitch, when I hit cmd + shift + F to get to global search, if I hit the up arrow immediately after, it doesn't work; if I hit the down arrow it does works, and after that both up/down work as expected
- after up/down selection, feels intuitive that 'enter' should take you directly into body of note for quick editing (I see tab takes you to title > tags > body, but that means 3 keystrokes to get into a note); this could also clear the highlighted search term which feels a bit distracting to persist when editing the note 
- after search, also intuitive for 'esc' to clear the current search
- re: the issue of shortcuts not working when inside extensions, if hitting 'esc' (or some other simple global command…thinking of extension contexts kind of like vim modes) could reliably exit that current extension context, might be a nice solution and allow for extension-specific shortcuts w/o clobbering global ones

Hope this is helpful; I realize these are super early / experimental and I don't mean to nitpick, just some things that came to mind while trying these out. Anyway love that you're working on this and I think I'll have to upgrade my account soon 😃

**Comment by mobitar** [comment]
The tricky thing with shortcuts is that they have to work in the browser too, and a lot of these are already reserved by the browser. It's why we couldn't use cmd + shift + n, or why we can't use cmd + 1/2/3.

**Comment by mogwai** [comment]
Are these experimental shortcuts working on linux?

**Comment by mobitar** [comment]
The latest release 3.0.16 may have affected these shortcuts if you don't see them working anymore.

**Comment by jnizniowski** [comment]
> The tricky thing with shortcuts is that they have to work in the browser too, and a lot of these are already reserved by the browser. It's why we couldn't use cmd + shift + n, or why we can't use cmd + 1/2/3.

Why is that a thing? In Nozbe, shortcuts for desktop apps are different than shortcuts for the web app. And there's nothing wrong about that.

**Comment by bbeennjjnneebb** [comment]
Hi. Not sure piling up on others' messages is welcomed, but I was not sure where to ask.

Also just starting with SN and very happy with it (came from Simplenote whose sync issues were getting me mad).

When using the Mardown Pro editor, I find myslelf hitting Cmd + H to hide the app, only to add a # markdown header instead (this does not happen if I use the Plain Editor for instance), like @Soleone described.

I figured a simple workaround would be to reassign the command triggered by Cmd + H in Markdown Pro (Heading), to some other key combination to restore the standard use of Cmd + H to hide the app, which I tried to do using the Shortcuts tabs of the Keyboard preferences on Mac. But since the command is not a Menu item, this does not seem to work (I tried "Heading" and "Heading (Cmd-H)"), is this not possible (annoying, but I could live with that), or am I just not using the right name?

Thanks

**Comment by JaspalSuri** [comment]
> Hi. Not sure piling up on others' messages is welcomed, but I was not sure where to ask.

It's fine to ask here, although it is a slightly different question and might get overlooked. Good thing it's my job to make sure that doesn't happen!

> Also just starting with Standard Notes and very happy with it (came from Simplenote whose sync issues were getting me mad).

I've lost notes to Simplenote and it was pretty frustrating. I have a tag named after it in SN for all the notes I've manually imported from it. I discovered an uncomfortable amount of blank notes. We're glad to hear that you're happy with Standard Notes!

> When using the Mardown Pro editor, I find myself hitting Cmd + H to hide the app, only to add a # markdown header instead (this does not happen if I use the Plain Editor for instance), like @Soleone described. I figured a simple workaround would be to reassign the command triggered by Cmd + H in Markdown Pro (Heading), to some other key combination to restore the standard use of Cmd + H to hide the app, which I tried to do using the Shortcuts tabs of the Keyboard preferences on Mac. But since the command is not a Menu item, this does not seem to work (I tried "Heading" and "Heading (Cmd-H)"). Is this not possible (annoying, but I could live with that), or am I just not using the right command name?

Unfortunately, I don't think it's currently possible to remap keyboard shortcuts. It might not necessarily be impossible to implement down the road, of course. 

In the meantime, may I suggest using <kbd>command</kbd>-<kbd>m</kbd>, since Standard Notes is currently a single-window application and will be easy to switch back to? I know it doesn't fix your problem and you'll have to fight muscle memory, but it will at least "hide" it as needed. 

I will make a request for this on your behalf to the team for them to consider. Thank you for letting us know about this!

**Comment by bbeennjjnneebb** [comment]
Hi. Thanks a lot for the prompt reply.
Yeah I guess Cmd + m will do in the meantime.
Thanks for making a request for me.

**Comment by FetchFast** [comment]
This is important. Apparently it's not that easy. 

Can anyone here link to a dev thread on another app's github where they tackled this problem and documented it? That might give the dev here some help.

**Comment by effieeee** [comment]
Tracking here as re: shortcuts https://github.com/standardnotes/forum/issues/1511

**Comment by atmoio** [comment]
Keyboard shortcuts are now available: https://github.com/standardnotes/forum/issues/1511#issuecomment-1322276205
