### ISSUE TITLE
Printing and in-line search

### ISSUE THREAD

**Issue by gpwwjr** [standardnotes/forum#306]
I have some rather length notes, so search is really a must-have feature for me.
Also, I consider printing to be a pretty basic necessity.
I've read that these features are somehow out-of-scope for Standard Notes, but this doesn't make any sense to me.
I've purchased the extended version, but I don't find these features anywhere.

**Comment by mobitar** [comment]
Searching via the notes panel will search and highlight terms. Currently searching inside a note is not available, but definitely something we want to build in the near future. Printing is unlikely to be added inline, as printing is a job better done by applications who specialize in those functions, like word processors.

**Comment by gpwwjr** [comment]
I don't understand why you think printing is a function to relegated to word processors. To me this just doesn't make any sense. Anybody that uses text is going to want to print their documents sometimes.

**Comment by mobitar** [comment]
Just part of our simplicity focus. There are lots of text functions that will be essential that we will say no to. It's totally subjective. But makes perfect sense to us. It's more important for us to minimize our code footprint then to deliver every essential feature a user may be looking for.

**Comment by lxnow** [comment]
> Searching via the notes panel will search and highlight terms. Currently searching inside a note is not available, but definitely something we want to build in the near future. Printing is unlikely to be added inline, as printing is a job better done by applications who specialize in those functions, like word processors.

+1 on the search function for desktop and mobile app. CTRL+F works already in the web browser when you have the note opened, so that works well enough if crudely.

**Comment by Poecilia** [comment]
I agree with gpwwjr that printing is now pretty ubiquitous. Standard Notes is the first text software I've used in a long time that won't let me print. Almost everything else does, including my basic text editors.

**Comment by mobitar** [comment]
It's just not trivial to implement with our editor extensions architecture. I've looked into it before and it would take considerable work. Not totally out of question though.

**Comment by ra-pha** [comment]
> Searching via the notes panel will search and highlight terms. 

My experience is that if the same search keyword exists in multiple notes, that the first occurrence of the first note may be highlighted and if you click on the next note then you're on your own...you have to scroll through the note eventually to find the keyword.

Sometimes search returns the notes containing the keyword but still won't highlight the keyword in the note. Could this be due to case sensitivity as the search field won't accept uppercase characters? In that the case the user has to scroll the note to maybe find the keyword on his own, knowing that it should exist in there. It's not really elegant nor efficient from a user's point of view.

**Comment by mobitar** [comment]
@ra-pha there is currently an issue with some Extended editors where anything not initially in view will not be highlighted. This one's on our radar and one we hope to have fixed in the near future.

**Comment by mobitar** [comment]
In-line search is now available with the Minimal Markdown Editor via Cmd/Ctrl + F.

**Comment by ra-pha** [comment]
Is this valid for browser or also for the Mac App?

**Comment by ra-pha** [comment]
This is what search looks like on the MAC App. First found items in a note in the Advanced Markdown Editor (visible when running the search) are highlighted. Words that match the search term and are further down in the note are not highlighted.

![screen shot 2019-01-26 at 19 53 59](https://user-images.githubusercontent.com/36484392/51791487-32137580-21a4-11e9-9166-752ead88c26b.png)

**Comment by mobitar** [comment]
With most editors, text content isn't rendered until it's visible, which is why later results aren't highlighted. There are potential solutions to this we want to explore. But for in-note search, I was explicitly talking about only the Minimal Markdown Editor, which offers a dedicated search bar for this which can be toggled with ctrl/cmd + f.

**Comment by TheodoreChu** [comment]
By the way, the **unofficial** [Append Editor](https://demo.appendeditor.com) ([source](https://github.com/theodorechu/append-editor)) has support for printing and search-and-replace. Choose the **Monaco** editing mode in the Settings
