### ISSUE TITLE
Incorrect character count in Super Labs notes

### ISSUE THREAD

**Issue by shashwatsridhar** [standardnotes/forum#3153]
**Describe the bug**
The character count of a chunk of plain text is wrong in Super notes.

**To Reproduce**
1. Create a new "Super Labs" note.
2. Enter any random piece of text.
3. Activate the Action Bar at the bottom.
4. Notice that the character count is much larger than the number of characters you've entered.

**Expected behavior**
The character count should correspond to the characters entered into the note.

**Screenshots**
![Example screenshot](https://github.com/standardnotes/forum/assets/16129966/da2a8c7b-9583-4a4a-8354-b2afc9aceef6)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 Gnome 42.5
 - Browser Firefox 114.0.1 (not sure why this is important)
 - Version 3.161.1

**Additional context**
The Action Bar doesn't respond very reliably in the GUI. Clicking on it doesn't toggle it, until I switch to another note and back. Should I file a new issue for this?

**Comment by effieeee** [comment]
Hi @shashwatsridhar, the Action Bar unfortunately records the character count based only on the **raw, plain text** contents of the note, rather than the rendered version shown by the premium editor. The Super note in particular uses a custom JSON format when you check the plain text contents of the note, so the JSON code interspersed within the plain text would likely account for the additional characters that the Action Bar sees. 🙏

Furthermore, I'm afraid that the Action Bar is already a **deprecated extension**, so while a reinstall would normally be advised in this case, I'm afraid it's no longer possible since it's no longer maintained by the team.

**Comment by shashwatsridhar** [comment]
Thanks @effieeee for the helpful response.

Is there another way to get the character count in premium editors? That would certainly be a useful feature.

**Comment by effieeee** [comment]
I'm afraid there isn't any extension that can properly count characters on the premium editors at the moment, though we'll try to keep this in mind for the Super notes in particular, since this is the note type we're actively developing!
