### ISSUE TITLE
Fast note creation from search

### ISSUE THREAD

**Issue by gwynm** [standardnotes/forum#319]
I love Notional Velocity's workflow here: if there are no search results, press enter to create a new note with the title you were trying to find. So I've implemented it:

https://github.com/gwynm/web/commit/0cd1bf460b4e2e36718d5d1e016959a2564ef76c

Should this be:

a) merged (in which case I'll create a PR)
b) an Extension (let me know and I'll have a shot at it), or
c) not part of SN + not possible as an extension (in which case I'll maintain my own personal fork) ?

**Comment by gwynm** [comment]
Makes sense. I imagine writing this extension wouldn't be entirely trivial, since rather than just copying-and-pasting the existing search code, it'd need to be rewritten to get/set all its data via the extensions interface. I'm up for it, but it might take me a while!

I've got some other personal bugbears I want to work on (last-modified-date is reset on import, adding keyboard shortcuts, modifying the theme to get more note titles on screen at once). How about I get those done first to get a bit more up to speed, before using up your time adding a zone? Adding the new zone does seem like the right direction, though, especially if people also want advanced search.

**Comment by mobitar** [comment]
Sounds good! Btw, keyboard shortcuts will be an extension. I have plans for that, but definitely won't be native.

**Comment by mmlmrx** [comment]
That is true - there is always someone who doesn't want/need a feature.  And I totally understand the hesitation about adding features - it is a rare and admirable stance that more websites/apps should consider.  

My only counterpoint would be: in what scenario someone would accidentally run into that feature?  I can only think of two reasons someone would use the search bar:

1.  **Looking for something to act upon.**  In this case, they search until they find what they intend to modify, then they leave the focus of the search bar to edit whatever it is they found.
2.  **Looking to see if they already have something before they go ahead and add it.**  In this case, they search until they don't find anything, then they will want to add it.  

In the first scenario, I can't think of why they would search for something and then press + (or enter) - but **not** want to create something related to what they just typed.  Capturing the change of focus is important, otherwise they might click + later on and pull in whatever was left in the search bar.

But for the second scenario, pressing enter or + is a very smooth transition from searching to editing.  Currently, the flow is selecting/copying the text I just typed into the search bar, clicking +, then pasting/finishing what I want to enter.

Just my $.02, though - I'd be happy to have it either native or via an extension.

Thanks!

**Comment by mobitar** [comment]
@mmlmrx good points, thanks! I'll have to let this one marinate. It's tempting, but just don't want to rush into it. An advanced search extension in general has been on my mind, so perhaps there's room for this there in the future.

**Comment by TheodoreChu** [comment]
Closing this because in the latest web/desktop apps (v3.5+), clicking the plus above the search bar creates a new note with the title of the search term: https://app.standardnotes.org
