### ISSUE TITLE
Broken file associations

### ISSUE THREAD

**Issue by devinaconley** [standardnotes/forum#3197]
Latest update `3.166.x` seems to have broken all file associations

Getting an error message when opening "Simple markdown" style notes
```
The extension was not found on your system, possibly because it is still downloading. If the extension doesn't load, try uninstalling then reinstalling the extension.
```

Also most (not all) checklists now load as plain text

Re-selecting the note type seems to resolve both issues, but this is a manual process (for hundreds of notes in my case)

**Comment by devinaconley** [comment]
a related comment is that currently changing the type association also counts as a "last modified" update. It would be nice to be able to change this (especially in situations like this) without affecting this timestamp

**Comment by effieeee** [comment]
Hi @devinaconley, duly noted on your feedback regarding how changing the note type would still affect the date modified, and we're really sorry for the trouble due to the recent issue on certain accounts.

If you used a certain paid note type as your default in the past, please also check your **default note type** settings and verify if it's still set to that type. Setting this back to your preferred note type may help restore the affected notes.

![image](https://github.com/standardnotes/forum/assets/54989748/f697e66c-b5c7-445d-9ce7-e5636c63de7d)

You may also use **multiple selection** on the desktop app or web app to select more than one note for quicker conversion back to the preferred note type. Use **Ctrl or Shift + Left click** to select specific notes, while **Ctrl + A** selects all currently loaded notes in the list. Once the affected notes are selected, open the **note type list** on the top right of the app and select the note type you'd like to switch to.

![image](https://github.com/standardnotes/forum/assets/54989748/d1c02bcb-141b-4d06-955f-29a3070242e3)

**Comment by devinaconley** [comment]
Hi @effieeee thanks for the response and for the suggestions! Appreciate all the work on this application - it's a great product.

The default note type did not seem to fix anything, but it's possible I had already messed with the files too much. And the multi-select is helpful, good to know.

It's possible that there is some mismatch in my notes previously being associated with "simple markdown" which I cannot seem to find anymore. Was this moved to be called "basic"?

**Comment by effieeee** [comment]
You're most welcome, I do hope the multi select helps you get back on track faster!

Regardless of their name, both Simple Markdown and Basic Markdown refer to the same editor, so the naming shouldn't be the main cause here, especially since other note type appear to have been affected by the issue here. We'll try to see what other info we can find, though I'll be closing this issue for now. Feel free to reopen if you have other concerns related to this! 🙏
