### ISSUE TITLE
[Help Wanted] - No Desktop 3.167.2 for OS X?

### ISSUE THREAD

**Issue by CdtDelta** [standardnotes/forum#3204]
**Describe the issue**
There are no OS X packages for the Desktop 3.167.2 version 

I went to do an update this morning and the latest release only has Linux and Windows packages.

**Comment by CdtDelta** [comment]
Just a quick update, apparently there is a new version here but it's 3.167.11 (and tagged pre release in Github):

https://standardnotes.com/download

But the project page here shows the latest release is 3.167.2:
https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.167.2

**Comment by effieeee** [comment]
Hi @CdtDelta, there was a known issue with app updates on the Mac app, and this was addressed [here](https://github.com/standardnotes/app/commit/ef2d1b9228c90a9cb9cf88535526a312bb28fca4)

You should find that it's actually ok to use v3.167.11, since it's technically the same build that's available on the web app. We only mark a new "Latest" release every so often, because if we don't users will need to update their apps to new sub-versions quite frequently 🙏

**Comment by CdtDelta** [comment]
Ok I know sometimes updates "come in droves" and then quiet down for a bit, that was part of the reason why I was asking. I'm assuming the update issue with OS X is fixed in the Desktop 3.167.13 version then?

**Comment by effieeee** [comment]
Yes, we've also updated the dependencies on our end to help resolve the update checking issues on current versions 🙏
