### ISSUE TITLE
Minimal Markdown Editor does not load as default after the editor is reinstalled.

### ISSUE THREAD

**Issue by johnsonalex** [standardnotes/forum#3216]
**Describe the bug**
If the minimal markdown editor is removed under general and advanced settings, reinstalled by adding https://standardnotes.github.io/plugins/cdn/dist/entries/com.sncommunity.minimal-markdown.json, set as the default new note type, and then a new note is created, the new note uses the Super note type even though the dropdown shows as Minimal Markdown as selected. Clicking on Minimal Markdown then correctly changes the editor.

The normal Markdown editor does work as a default option.

**To Reproduce**
1. Go to Preferences
2. Select General
3. Expand Advanced options
4. Remove Minimal Markdown editor
5. Reinstall using https://standardnotes.github.io/plugins/cdn/dist/entries/com.sncommunity.minimal-markdown.json
6. Set default note type to Minimal Markdown
7. Click create new note
8. New note will be the Super type and not Minimal Markdown

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser: Using desktop app
 - Version: Current version for all devices

**Smartphone (please complete the following information):**
 - Device: iPad Air and Pixel 7
 - OS: 16.6 and 13 respectively
 - Browser: Using the apps
 - Version: Latest available on respective stores

**Additional context**

**Comment by effieeee** [comment]
Hi @johnsonalex, this has now been fixed here: https://github.com/standardnotes/app/commit/73609ca7e31c6cc628f46319f0b9502f7b8afcd3

**Comment by chaserene** [comment]
@effieeee the fix (https://github.com/standardnotes/app/commit/73609ca7e31c6cc628f46319f0b9502f7b8afcd3) was included in 3.169.20 (Android APK), and I'n using this version, yet I'm facing the same issue.

following your advice in [this comment](https://github.com/standardnotes/forum/issues/3198#issuecomment-1646606609), due to having the same problems as described in that thread, I removed Minimal Markdown from my Android client, reinstalled it with the following URL: https://standardnotes.github.io/plugins/cdn/dist/entries/com.sncommunity.minimal-markdown.json, then in the Display options and set the default new note type to Markdown Minimal. However, my notes with this note type were/are still set to the Plain note type.

what's worse, these note type changes to Plain translated over to my desktop client as well, where the reinstalling of Minimal Markdown was not necessary.

**Comment by effieeee** [comment]
Hi @chaserene, I'm sorry to hear about this. May I know if you were also able to see the added instructions in this [linked comment](https://github.com/standardnotes/forum/issues/3197#issuecomment-1646606543)? Using multiple selection on the desktop or web app can at least help you revert the affected notes to Minimal Markdown faster 🙏

**Comment by chaserene** [comment]
@effieeee yes, as I wrote in my previous comment, I followed those added instructions as well:

> in the Display options and set the default new note type to Markdown Minimal

in the end I changed the note type via multiple selection, but I hope others won't have to go through these steps.
