### ISSUE TITLE
Super Note Block Selection Menu & Item Attachment Menu Scrolling Bug

### ISSUE THREAD

**Issue by amigaomega** [standardnotes/forum#3246]
**Describe the bug**
When working on a Super Note- opening either the "/" block menu or "@" attachment menu produces the menu but scrolling through either menu doesn't work. The menu/s reset once you remove your fingers from the touch pad. As such any item that is not visible (ie you have to scroll down to see it) can't be selected as the menu jumps straight back to the top. Scrolling with keys doesn't move the menu down at all.

**To Reproduce**
1. Go to a Super Note.
2. Type "/" or "@" to open the menu.
3. Attempt to scroll down in either menu.
4. The menu jumps back to the top of the item list as soon as you remove your fingers from the touch pad.

**Expected behavior**
The menu should be scrolled smoothly and not jump back to the top of the item list once you remove your fingers from the touch pad/scroll keys.

**Screenshots**
Can't show in a screen shot.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Browser [n/a]
 - Version MacOS Standard Notes Desktop App Version - 3.169.32

**Smartphone (please complete the following information):**
 Works on smartphone (iOS)

**Additional context**
Not tested on the web app.

**Comment by effieeee** [comment]
Hi @orangetails, I'm afraid I haven't been able to reproduce this so far, but may I know if you're also encountering this when using the web app on any browser on your device? (app.standardnotes.com)

**Comment by amigaomega** [comment]
Hi @effieeee, I have now tested this with both Safari & Firefox browsers for MacOS. The menus work as they should in both browsers. It just seems to be with the MacOS Standard Notes app that the issue arises.

**Comment by effieeee** [comment]
I see, thanks for checking! The web apps are almost always on a more updated build since fixes are pushed live there, so can I ask you to try downloading an installer for Mac from our website’s homepage? This should give you the installer with the same build as what is on the web app right now. Let me know if the issue persists even after installing and updating to the newer version!

**Comment by amigaomega** [comment]
Hi @effieeee, I've just updated via the website to- standard-notes-3.171.9-mac-arm64
I've tested both the menus and everything is now working as normal! 😄
Can I ask- why when checking for a new update via my existing install of Standard Notes it said it was the most recent release, yet there is a newer version available when I went direct to the website?
Thanks again.

**Comment by effieeee** [comment]
Awesome! Regarding the difference in version numbers, we actually mark the “Latest” release versions on the repository for the desktop apps only after a significant amount of updates has accumulated, so that users don’t have to constantly update the desktop apps whenever we push fixes live.

The website on the other hand, always pulls in the very latest package built by the latest changes/commits!
