### ISSUE TITLE
[Feature Request] Prevent deletion of note when note is locked

### ISSUE THREAD

**Issue by mxng** [standardnotes/forum#327]

**Comment by mobitar** [comment]
Hmm..I've thought about this. But what would the use case be? Accidentally clicking delete then confirming?

**Comment by silverpierce** [comment]
There should be a warning that you cannot delete without unlocking first (with an option to not show again next time). After not showing, subsequent pressing of delete while the note is locked will just have no effect. Bonus if the "delete" is greyed out. So basically a double confirmation instead of the current system.

This is to prevent any accidental deletes for locked notes. Maybe for a note we thought is important and shouldn't be deleted last time and we locked it. Then in the future when we forgot that it's important and wanted to delete it but the warning showed and reminded us to think twice.

Or, you could just add a recycle bin feature to take back what we accidentally delete or regret deleting.

**Comment by mobitar** [comment]
Yeah, a recycle bin feature is something planned for the near future. I'll revisit this idea as well once we're working on that. Thanks for the feedback!

**Comment by mobitar** [comment]
Deletion prevention on locked notes has been added to desktop 2.3.10 and web. Mobile likely soon.
