### ISSUE TITLE
Checklists notes not working in ios, when in lockdown mode

### ISSUE THREAD

**Issue by rodogu** [standardnotes/forum#3295]
When the phone is in Lockdown mode, a checklist type note cannot be edited, only shows the "Open Tasks", "Completed Tasks" in the Edit mode.

Preview shows the tasks correctly.

**To Reproduce**
* Enable Lockdown mode (iOS' Settings > Privacy & Security > Lockdown)
* Select a Checklist notes, you won't be able to edit, it doesn't even display the tasks

If you disable Lockdown mode, then the tasks are displayed porperly.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 16.6
 - Version: 3.178.8

Work around is excluding the App from Lockdown mode

Edit: added work around.

**Comment by rodogu** [comment]
wondering how come it works when the app is excluded from lockdown mode... would it be that the plugin uses a third party library which is not whitelisted/trusted?

**Comment by effieeee** [comment]
Hi @rodogu, there are certain functions that are limited while lockdown mode is enabled, though because Apple does not disclose much about how it works as well, it makes it difficult for the team to anticipate and look into how we can address the issues when they arise. Please see my comment below on a related issue as well 🙏

https://github.com/standardnotes/forum/issues/3051#issuecomment-1737299295
