### ISSUE TITLE
Keep asking me to login..

### ISSUE THREAD

**Issue by github2099** [standardnotes/forum#3296]
It will randomly ask me to login, and if I don't do so, I can't sync my notes.

Instead of refreshing the session, it creates a new session after I login. There are many sessions being active on my account because of this.

Mobile iOS, version 3.173.8

**Comment by effieeee** [comment]
Hi @github2099, please try out the instructions below to reset the app as an initial step:

2. Click on the View dropdown menu on the top menu bar for the app
3. Click on the Toggle Developer Tools option.
4. Expand the window until it reveals a button for tab named Application.
5. Under Application, click on Storage on the left hand side.
6. Click on Clear site data.
7. Relaunch the app, and sign in again.

**Comment by github2099** [comment]
Hi @effieeee , sorry but I can't find the Developer Tools option.. Mine is iOS v3.175.2 (880), regular version not TestFlight.

**Comment by effieeee** [comment]
Hi @github2099, my apologies, the instructions I sent were not for the iOS app. Please try these instead:

1. Please open the Settings app, and navigate to your iCloud backups with the following path: [Your name and iCloud account username (at the top)] → iCloud → Manage Storage → Backups → [Tap on the correct device]
2. Wait for the list of apps to load.
3. Finally, locate the Standard Notes app and tap on the toggle button to remove the current and all future backups of the app from iCloud.
4. From there, please reinstall the app and sign in again.

**Comment by 7aitsev** [comment]
Hi @effieeee, I had the same issue as @github2099 when my app started to ask me to sign constantly on iOS. I tried to sign in, but it didn't solved the problem. I decided to reinstall the app, but for more than 2 weeks I cannot sign in. The app just hangs on "signing in" screen after I type in 2FA code (the screen disappears back to username/password screen with the "signing in button").

I tried the steps above - no luck. The desktop version of the app for Windows works fine when I sign out and sign back in.

Thanks for your help and I hope this frustrating issue will be fixed

**Comment by effieeee** [comment]
Hi @7aitsev, I apologize for having to ask, but I wanted to confirm if you reinstalled it as instructed in [my comment](https://github.com/standardnotes/forum/issues/3296#issuecomment-1775378648) above?

I also wanted to verify if you currently have **Lockdown mode** enabled on iOS? This is known to inhibit the sign in workflow of the app, though because the exact workings of Lockdown mode aren't disclosed to developers, it's been rather tough for us to look into a solution. If this is the case for you, it should be possible to add the app as an exception under lockdown mode, as [instructed here](https://github.com/standardnotes/forum/issues/3051#issuecomment-1658890314).

**Comment by 7aitsev** [comment]
@effieeee yes I did enable the Lockdown Mode. The guide solved the problem I was having, thanks for your help!
