### ISSUE TITLE
[Feature request] Search within a note

### ISSUE THREAD

**Issue by jan-gerard** [standardnotes/forum#330]
[For the Android StandardNotes app:] It's extremely useful to be able to search all notes for a piece of text. But once a note with that text is opened, there is no way to search within. Therefore I would like to request that functionality: 
** A search function in the note editor screen that brings me to the corresponding location within the text (and the next and the next...) **

**Comment by gpwwjr** [comment]
I agree- this missing feature is necessary.

**Comment by mobitar** [comment]
I also agree. Our first priority would be bringing this feature into the desktop/web app, and then mobile. No definite dates on either yet though.

**Comment by dvejmz** [comment]
I find this feature absolutely essential and would really appreciate if it were added soon!

**Comment by mild0d** [comment]
Did this ever get added?

**Comment by Kiminaka** [comment]
I am facing this need over and over again and am even using a different note app because of it. Very much appreciated if this feature is added on desktop/mobile soon.

**Comment by mobitar** [comment]
Desktop already supports this feature via the main search bar. Pressing enter will highlight search results. Otherwise the Minimal Markdown Editor supports traditional in-note search. The mobile app is not likely to gain this feature anytime soon.

**Comment by Kiminaka** [comment]
Thanks! I see. Why is the in-note search function only supported for the Minimal Markdown Editor? I mainly use other editors such as Code and Advanced Markdown Editor and would be great if I could use the same function there as well.

**Comment by ra-pha** [comment]
I also have switched to another note-taking app because of this particular issue. Good luck for you and your app in the future. Wishing you all the best.

**Comment by jfallisg** [comment]
Really want to plus one this feature request.
Standard Notes ticks SO many boxes for me, I've tried everything including nvAlt, simple notes, Evernote, Bear, Notion, Quiver, and The Archive. For my usage needs SN is the best package after many years of looking for that perfect thing.
All that's missing is this! Search within a note! I end up maintaining several long "log" like files per year, that may include code snippets or general diary like log entires, and not being able to search for text and cycle through to the next location is app-breaking for me. When I'm desperate I'll copy a long note out of Standard Notes in to a text editor like Sublime and search that way, which is just terrible.
Highlighting occurrences of the search term is not usable enough if you have files with several thousands lines, you need to be able to cycle between, even with a keyboard shortcut or on-screen pop up.
Please prioritize such a feature, I would be so grateful!

**Comment by tmikaeld** [comment]
Multi-select mode like CMD+D (CTRL+D) would also be extremely useful.

**Comment by pymche** [comment]
I can see this thread has been two years - any updates on whether this is still in the backlog of SN? Would love to be able to perform search in a note on Android.

**Comment by JaspalSuri** [comment]
Hi @pymche, this issue is still on our backlog. 

While not optimized for devices without a physical keyboard, some editors support per-note search, such as the Vim-mode in the Code Editor, the Monaco editor within the [Append Editor](https://appendeditor.com), and the Markdown Minimist Editor. You can also narrow search results to certain notes by selecting a tag before searching.

**Comment by ubi-master** [comment]
Such a shameful lack in an otherwise great note app.

Come on, guys, this is not a hard bit of programming!

**Comment by mobitar** [comment]
It's very, very hard. Searching is not the hard part. Showing a yellow rectangle behind instances of a text in a note is hard. It's hard because we use textarea for the Plain Editor which doesn't support any custom behavior, and it's hard because we'd also need to build a custom solution for every other editor in our ecosystem. The Bold Editor would need a different solution from the Plus Editor would need a different solution from the Spreadsheets editor, and so on. Then you need another custom solution for mobile native editors.

In fact probably the only way to build this in the plain editor, which is the primary use case, would be to ditch textarea for a custom-render editor like CodeMirror, and this is no small feat.

So no, none of this is easy.

**Comment by ubi-master** [comment]
What if you just moved the cursor?

That's all I would need.

**Comment by jan-gerard** [comment]
And select the word (or characters) found? That should be possible in basically any editor. Highlighting comes then by itself.

**Comment by KevinSource0** [comment]
I agree. Search within a note is essential for a note-taking app, probably for almost any editor, even browsers. Can't think of any editor can't do search within a document.
If each editor needs to have it's own implementation, plain editor is a good start, since that's the most basic and popular. People usually search for text, not format / style. 
As @mobitar mentioned:
> Our first priority would be bringing this feature into the desktop/web app, and then mobile. 
since desktop has large screen space and has the most power users.

Plain editor on desktop only would be a huge improvement to user experience.

**Comment by RonanCodes** [comment]
This feature is so important. I have to copy paste large notes into my vscode editor to find where words are sometimes 😭

**Comment by DaveFlowberries** [comment]
Jesus, can't believe we are still waiting on this very basic and necessary feature. Do the devs not use their own product?

**Comment by fury182** [comment]
I vote for @ubi-master 's proposal. Moving just the cursor just for the Plain Editor would suffice for many users (maybe select the text if possible). This would be much better than using CodeMirror which might degrade the performance for large notes.

**Comment by fury182** [comment]
I found a temporary workaround for now (posting here as it may help some); if I use the "Code Editor" with "Plain Text" and "Enable Vim mode" I pretty much have a searchable plain text note (if you don't know how to search you can Google how to search in Vim).

And most surprisingly, generally working with the note seems faster: I was editing a pretty large 1 MB note and there was a noticeable lag when typing in the "Plain Editor", but not anymore with the "Code Editor" and "Plain Text"!

**Comment by effieeee** [comment]
Tracking here: #1770

**Comment by jreus** [comment]
+1 I notice CTRL-F now brings up a very minimal text search in the `Minimal Markdown` editor. This is great!
Could we please have this as a general feature available in all the editors? Or at the very least port this over to the more elegant `Markdown Alternative` editor. 

The ability to go through all instances of the searched term would also be really useful. At the moment in `Minimal Markdown` you have to re-run find repeatedly to get to sequential instances of the search term.
