### ISSUE TITLE
A note on Editors and Extensions on mobile

### ISSUE THREAD

**Issue by moughxyz** [standardnotes/forum#34]
_Update May 2018: Editors are [now available](https://listed.standardnotes.org/@sn/1437/editors-on-mobile-desktop-highlighting-and-2-new-extensions) on mobile._

I get asked frequently about supporting editors or other extensions on mobile, so thought I'd give a response here.

Editors on mobile would be a whole other beast of an engineering challenge, and is not something I'd be ready to take on anytime soon. Especially given that we'd need to support them on both iOS and Android.

This would add an intense level of complexity to our applications, making them far more bloated and expensive to maintain, while also distracting us from keeping the platform as a whole stable and in good shape.

It's best to hold off on adding any more complexity to our mobile apps until it is something we can afford and commit to maintain over the long run. With SN, it's best not to have a feature then have it and cause issues and stress for everyone involved.

This might not be the answer you were looking for, but it's important to note that there is a whole "economics of software" involved here, namely that nothing is free, and costs rise exponentially with  feature set. We'd rather be thrift and survive longer, than take on risks and projects that can jeopardize long-term stability and survivability.

**Comment by ClarkeCC** [comment]
Would this apply to folders and sub folders? On mobile notes are pretty unorganized. I use tags, but I can go more in details with my folders.

**Comment by mobitar** [comment]
Ya, folders would be under extensions. With folders, they're `.` separated, so you can still get at the structure from mobile, but it won't be organized under a tree hierarchy.

**Comment by ClarkeCC** [comment]
@mobitar I think the basic structure is all that is needed. Folders would be the only extension I would need. The mobile app is more of a quick reference / basic ruff note, then do all my actual editing / fixing on my laptop.

**Comment by zanedb** [comment]
I have to agree with @ClarkeCC, folders are very important as an addition.

**Comment by mobitar** [comment]
No doubt there's a lot of important features that SN lacks, and will probably always be behind in implementing. That's a promise we make to you, and it's a feature, not a bug. This culture invites workarounds rather than more core code. Workarounds can be extensions, which are available for desktop, but not yet thought out for mobile, or just small things, like creating a psueo-folder interface by creating tags with dot patterns, like "blog.business.marketing" and just using that mentally to manage folders, until a physical solution exists. 

Not the answer you probably want to hear, but I'd rather tell you the truth than to say "folders will come in the future" when I can't promise that for certain.

**Comment by zanedb** [comment]
Well, thank you for being upfront about it. When I've learned enough React Native, I'll try to open a PR about it.

**Comment by DreamFlasher** [comment]
@mobitar I would find it great if you'd use something like uservoice.com to collect feedback which features are most important to people and then also prioritize by that :) I am under the impression that the lack of a rich text editor on mobile is problematic for a lot of people.

**Comment by mobitar** [comment]
It's more of an engineering problem, than a feedback problem.

**Comment by smikmiks** [comment]
I'm very sympathetic to SN, even sort of a believer, I guess.
But I must admit that lack of cross-platform alignment is an issue. It's not so much that a lot of features on mobile are needed in my view; it's more the fact that if you use any kind of editor in desktop, the notes then become more or less unreadable/unsuable on mobile. 
Wouldn't some kind of middle ground be feasible? Like, som sort of basic rich text and check-list view mode on mobile?
(Says one who hasn'nt a clue)

**Comment by mobitar** [comment]
I'm currently shuffling around ideas in my head. The reason this is difficult is because in order to add editors on mobile, it's not just a matter of adding code. Adding code is easy. It's, I don't want to duplicate code. I don't want to copy/paste the same code from the web/desktop app to mobile (they both use JavaScript, so this is very possible). Before editors come on mobile, I'll need to extract the current extensions system from the web code, into its own separate library, and integrate that library into both codebases, mobile and web.

This is a _huge_ and dangerous undertaking. It's definitely a healthy move for the project, since you decouple large parts from the main codebase, and extract it into its own independent library that can be used by many projects. But again, it's difficult. I may have decided this will be the next thing I work on, but I haven't yet decided when I will begin working on this. It would probably be the biggest refactor in SN history :)

**Comment by smikmiks** [comment]
Sounds like a big deal for sure. 

Personally I’ve opted for Total Simplicity meaning no editors, since I use both desktop and mobile a lot. I don’t mind that much actually, keeps things to the point. 

From a completely naive/pragmatic/technically-illiterate user viewpoint, one might imagine a temporary workaround by having some of the editors written in a language (or whatever the term is) that is a little more readable/manageable on the current mobile app. Like, a to-do list editor that didn’t say - [x] but something more easily accessible/type-able.  

Well, maybe it’s crazy. It’s certainly half-baked, I know, but from a simple user pow it would still make a difference.

**Comment by mobitar** [comment]
That's an interesting idea, and Markdown would probably be the closest thing to that. But even then, people want to to see their rendered Markdown.

**Comment by DreamFlasher** [comment]
i think markdown is at least somewhat editable on mobile, I mean it's still text. While the HTML from the plus editor is not editable at all. So I think one rich-text editor that can work with the HTML and does some basic formatting would help a lot.

**Comment by mobitar** [comment]
But what markup language exists that can do font sizes and families, highlighting, and tables, that's not HTML?

**Comment by DreamFlasher** [comment]
As I said an HTML wysiwyg editor for mobile is what I think would be the most valuable.

**Comment by mobitar** [comment]
Right, but then this takes us back to the refactoring requirement.

**Comment by DreamFlasher** [comment]
Well, yes and no. While I do think the refactoring is necessary in the long-term, a quick fix could be to provide a wysiwyg mobile editor as extra code.

**Comment by mobitar** [comment]
We don't do quick fixes with SN ;)

**Comment by DreamFlasher** [comment]
But that's exactly what @smikmiks asked for ;) So then it's the refactoring ;)

**Comment by smikmiks** [comment]
Well, for the record, my second comment was more to the effect of a Bad Fix than a quick fix :-) 
Markdown actutally works fine to that end. People should use it more. 

Maybe as a communication thing, you might want to label the editors with a note about their degree of readability on mobile. I might be nitpicking here, but as a mortal user I did spend some time finding that out - then changing editor again on a lot of text - and so on - that I might have saved with some info like that. 

(Still dreaming of a simpler check list editor-language though... The 'easily editable' feature being the whole difference between a check list and... a list.)

**Comment by mobitar** [comment]
It's definitely called out in a few places, but perhaps I can add a note to every editor about mobile readability. Though, I've learned to never underestimate people's ability to gloss over important details (guilty of it myself at times).

**Comment by mobitar** [comment]
Ok, added this under every section in the [Extensions](https://standardnotes.org/extensions) page. Hopefully that should remove any confusion.

<img width="864" alt="screen shot 2018-03-16 at 3 34 42 pm" src="https://user-images.githubusercontent.com/3277844/37543457-a7f9920c-292f-11e8-8f1b-d5233d21a631.png">
<img width="941" alt="screen shot 2018-03-16 at 3 35 02 pm" src="https://user-images.githubusercontent.com/3277844/37543458-a9c59982-292f-11e8-8501-b9802579ab06.png">

**Comment by smikmiks** [comment]
Nice. Like you said, maybe one or two users will actually notice :)

**Comment by fletom** [comment]
a bit of feedback for you from a new user:

firstly, this issue is currently the main reason I've decided not to subscribe to Extended. mobile is at least half of my note-taking usage, and paying for something that I can only use if I happen to be on the right device doesn't seem reasonable to me

but secondly, your response to this request and hesitance at taking on the major work involved, is what convinced me that this app is the right thing to use going forward. it shows that your sustainable and responsible approach to developing SN is not just marketing, and that I can trust it long-term. I'll be importing my notes from Apple Notes, and using the free version of SN for now. I hope to be able to subscribe to Extended in the future when I can make use of it on all platforms.

can you explaina bit more, in technical terms for a fellow developer, what makes this so complicated? why are the mobile and desktop apps not runing the same code with a responsive design approach?

**Comment by fletom** [comment]
thanks for the explanation. I'm not sure that I agree that a WebView can't feel just as good as native, especially on a modern mobile OS. but I can easily see that achieving that might require more resources than you have available currently. and thanks for not spreading yourself too thin!

**Comment by mobitar** [comment]
Not webview on mobile, but long text input on webview on mobile, particularly. That experience isn't ideal.

**Comment by matthjes** [comment]
Did something change over the last month? I'm asking because the extensions page now shows for editors " Desktop, Web & Mobile", so I would expect that editors are available on my phone / tablet...

**Comment by mobitar** [comment]
Yup, sorry forgot to update this issue. Read here: https://listed.standardnotes.org/@sn/1437/editors-on-mobile-desktop-highlighting-and-2-new-extensions

**Comment by smikmiks** [comment]
This is GREAT. Works and looks good and switching to plain editor is simple. Nice job!

**Comment by mobitar** [comment]
@smikmiks thank you!

**Comment by hanct** [comment]
If i purchase the extension, it will appear in my mobile phone or web-based. Those editors that comes with the extension,, can I confirm that whatever features of those editors  will appear the same across all platforms?  Cos usually, I always have the impression, tat desktop application always has the most functionalities, and its corresponding mobile or web version contain strip down versions of the desktop features.

**Comment by mobitar** [comment]
@hanct yes, the editors do appear on mobile as they appear on desktop. But you're right in that desktop performance of those editors would be most optimized. On mobile, we don't strip away any features, but that also means you're using a desktop-based editor on mobile. So, maybe _too much_ power for a mobile device, if your device can't keep up.

**Comment by retorquere** [comment]
Should I expect Secure Spreadsheets to work on mobile? I'm looking to use SN for journaling and a spreadsheets would seems to come closest for me to fill out date/time in an easy-to-glance format.

**Comment by mobitar** [comment]
I've personally never had any issues with it on mobile (I use iOS). But it is a beast of a web-app (the spreadsheet software), so, it's definitely going to stretch what your device is capable of. Best to try it and see if it works for you.

**Comment by effieeee** [comment]
Old issue, closing in light of new mobile experience
