### ISSUE TITLE
Desktop UI Improvements

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#340]
Any chance you're planing to implement these for the desktop app? Would greatly improve my user experience and make me better able to stick with your work.

Creating new notes from the search bar
Selecting multiple notes at a times

Also a huge fan of hotkeys for things like:
Renaming notes
Deleting notes
Centering cursor on search bar

Thanks for the work and the great experience so far!

**Comment by mobitar** [comment]
Hey @ikatesx4r, creating notes from the search bar is not currently planned. Selecting multiple notes for deletion can be done with the Batch Manager extension. For viewing notes side by side, we have an editor extension planned for that. For keyboard shortcuts, please see here: https://github.com/standardnotes/forum/issues/39

**Comment by mark6400** [comment]
I noted this in #39, but please consider creating notes from the search bar, as implemented in [Notational Velocity](http://notational.net). This is a **game-changing feature**, one that allowed me to fully commit to plain-text notes, and I'm certain that I'm not the only NV (or [NValt](http://brettterpstra.com/projects/nvalt/)) user who's considering Standard Notes as a replacement.

**Comment by mobitar** [comment]
I feel like this is a luxury feature. It doesn't _feel_ essential. Useful for sure, but not essential. Can you describe why this feature is essential to you?

**Comment by mark6400** [comment]
Here is my use scenario; it's common to academic research, and its predecessor is the index card catalog, a fine example of which may be found [here](https://takingnotenow.blogspot.com/2007/12/luhmanns-zettelkasten.html). 

I'm taking notes on a subject/book, and I'd like to add a note. I go to the search/create field and type the tags, source, and/or keywords I'm planning to use. Oh, look, there are two other notes with these same search terms. Do one or both of these extant notes already contain what I'm planning to write? I read the first note, then perhaps arrow down to scan the second. 

- Maybe the extant notes already contain what I'd planned to write, in which case my desire to create a note has led me to rediscover a previous effort, which in turn may suggest other sources to consider. 

- Maybe I'd like to just append to one of the extant notes—add a new reference or angle—rather than create a redundant note and reduce the efficiency of my note system.

- Or maybe I'd like to make a third note, because I have a different angle in mind; this new note can now refer to one or both extant notes as needed, providing greater context.

In all of these cases, my action is *informed* by the results of the search, but in only the first case is the final action itself a search. Not having to distinguish between actions at the start of this process increases the likelihood of serendipitous connections, which for me are the truly rewarding moments of taking and managing notes.

**Comment by mobitar** [comment]
Got it, thanks for the detailed feedback. In these cases, how many words would you say your search query contains? One/two/three? Or much more? And how often do you imagine you'd undergo this flow? Many times a day/week/month?

**Comment by mark6400** [comment]
Often three or four: a (partial) date, a file type, a topic/category, and a keyword. Example: 2017- qNote #Watergate Wiretap. 

This is my main flow for using and creating notes; unless it’s the first day of a brand new research topic, I always search before I create.

**Comment by effieeee** [comment]
Tracking here, for the shortcuts in particular: https://github.com/standardnotes/forum/issues/1511
