### ISSUE TITLE
Windows 7 support killed in v3.178.0 ?

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#3467]
On my Win7 setup, v3.175.2 works fine while v3.178.0 throws the error "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll."  Some quick googling suggests this error is related to dropping support for Win7, but I don't see any mention of this in the [changelog](https://github.com/standardnotes/app/releases) or anywhere else that I can find.  Is that indeed what happened?

**Comment by JeremyMusick** [comment]
https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
Where does standard notes publish their list of supported OS's?  I'd assume they supported Windows, doesn't mean they're going to ensure the app functions on Windows 98.

**Comment by virtuallyvlad** [comment]
I couldn't find it in any place a normal user would look.  They don't need to explicitly mention a lack of support for Win7, but most developers will at least put "Windows 10 and later" or something to that effect, so that people know the minimum requirement.

(Not listed on any of these pages:)
https://standardnotes.com/
https://standardnotes.com/download
https://standardnotes.com/plans?downloaded=windows
https://github.com/standardnotes/app

Also, killing support for an OS without so much as a mention in the release notes, and having your software update to self-destruct seems a bit... unprofessional.  (If that is indeed the issue causing that error.)

**Comment by effieeee** [comment]
Hi, unfortunately yes, because we updated to the [newer versions of Electron](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice), this also meant that the newer versions of the app could no longer run on Windows 8.1 and earlier OS versions. We also apologize that there weren't more visible announcements regarding this.

We updated it sometime in October 2023, so a release from September 2023 (such as [this one](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.173.20)) may still work, though I generally wouldn't advise using older versions of the apps in the long run, as I can't guarantee that you won't run into any issues with your notes and with certain app features.

Although the desktop apps won't be able to run on older OS versions, the [web app](https://app.standardnotes.com/) should still be able to run on older devices using any browser. 🙏

**Comment by virtuallyvlad** [comment]
Ok, thanks for confirming.  So for anyone on Windows 7/8/8.1, [the last working version is 3.175.2](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.175.2).  That one works fine as of now, but you will need to disable automatic updates (since Standard Notes didn't bother to make sure they don't cause the app to explode), via the Menu -> Updates -> Enable Automatic Updates.
