### ISSUE TITLE
[Help Wanted] When creating an "Austomatic plaintext backup", all the notes are not saved.

### ISSUE THREAD

**Issue by scrollop** [standardnotes/forum#3495]
When checking the automatic plaintext backup,  all of the folders are not created,  and all the notes are not created.

This is on a Win 11 box.

Thank you.

**Comment by effieeee** [comment]
Hi @scrollop, can I ask you to share a screenshot of what's recorded on the **Console** whenever you create an automatic plaintext backup?

Desktop:

1. Click on the top left menu, then choose View > Toggle Developer Tools.
2. Once the Developer Tools window is open, click on the Console tab on top, then try to create an automatic plaintext backup. Take a screenshot of the output you see (as in the sample screenshot below)
![image](https://github.com/standardnotes/forum/assets/54989748/7e1fd778-cc31-4171-a42b-2f5622ca0e61)

 

Web App 

1. Depending on your browser, you may be able to use Ctrl + Shift + I (or Cmd + Option + I for Mac) to display the developer tools immediately. Otherwise, it should be found somewhere in the More tools options of your browser.
2.  Once the Developer Tools window is open, go to the Console tab as described previously, and take a screenshot

**Comment by jfstepha-sifive** [comment]
I found that this happens for me when a title contains a colon (":").  That's not a legal character for windows filenames.

**Comment by effieeee** [comment]
Closing in light of the actual issue in #3550
