### ISSUE TITLE
Offline activation in app not working

### ISSUE THREAD

**Issue by traktuner** [standardnotes/forum#3574]
I self host standard notes and have an offline activation key. 
When I open the iOS app, go into settings - general and want to paste the offline activation key, the UI does not open. 
I tap the little arrow and nothing happens (the UI does not show up). 
Latest App Store build, and TestFlight - same issue.
Thanks for you help!

**Comment by effieeee** [comment]
Hi @traktuner unfortunately this is a limitation with the iOS app, since iOS apps have certain regulations against subscription activation features when the subscription isn't purchased through the App Store.

However, are you able to apply the offline activation key through another device or app platform? You only need to apply it once, and then you can continue signing into this same account on all your devices through your self hosted server.

**Comment by traktuner** [comment]
Thanks Effie for the explanation! That makes sense. 
Yes the activation worked on the macOS app. It was just strange that the offline activation menu was there and not working. Maybe you could just hide it if it's an iOS/iPadOS platform. Thank you!

**Comment by traktuner** [comment]
@davidsmith91 
https://standardnotes.com/purchase/offline
