### ISSUE TITLE
sync unreachable 

### ISSUE THREAD

**Issue by Dmitry119** [standardnotes/forum#3582]
Not syncing, writes "sync unreachable", the same problem as here: https://github.com/standardnotes/forum/issues/770

But update, re-login and even re-install doesn't help! (iPhone + win)
Also web version writes "Unable to write to local database" instead of opening

Help please!

**Comment by con2vp1** [comment]
Same here, I hope my notes are lost forever.

**Comment by virtuallyvlad** [comment]
It's down.  In the future, just check the [#sn-discussion channel](https://discord.com/channels/894600255058898974/894600255058898977) of the Discord server.

**Comment by the-a-man-006** [comment]
Unable to sync.
Sync unreachable.

**Comment by diplomendstadium** [comment]
After several hours (6?) the servers seem to be online again. At least I can synchronize again. :)

**Comment by lostinacave** [comment]
I was happy to see it working again after so many hours. It was my first day with SN, so I thought the problem was on my end.  
Instead of signing out/ back in, reinstalling the apps on my devices, I should've just realised that if it didn't work on the iPhone (which does not rely on my shaky Wi-Fi), it's not gonna work anywhere.  (Or just look at the website.)

Anyway, does anybody know if this is a common occurrence?

**Comment by virtuallyvlad** [comment]
> I was happy to see it working again after so many hours. It was my first day with SN, so I thought the problem was on my end. Instead of signing out/ back in, reinstalling the apps on my devices, I should've just realised that if it didn't work on the iPhone (which does not rely on my shaky Wi-Fi), it's not gonna work anywhere. (Or just look at the website.)
> 
> Anyway, does anybody know if this is a common occurrence?

Once or twice a year, I'd say.  [That chat room](https://discord.com/channels/894600255058898974/894600255058898977) is the quickest way to check if it's just you or an outage.

**Comment by lostinacave** [comment]
> 
> Once or twice a year, I'd say. [That chat room](https://discord.com/channels/894600255058898974/894600255058898977) is the quickest way to check if it's just you or an outage.

Thanks, @virtuallyvlad.   Yeah, it was just bad timing.    And you have convinced me to sign up for Discord.

**Comment by lostinacave** [comment]
Excerpt from SN Customer Support:
“… it was found that the issue was caused by an automated update of our database cluster version which had an incompatibility with our client version. The issue was resolved on the same day that it was reported, and in light of what happened, we'll be reviewing our update processes to ensure this doesn't happen again.
 
In case you aren't already part of our [Discord group](https://standardnotes.com/discord), we encourage you to join in order to get in touch with the Standard Notes community, and possibly find updates whenever an app-wide issue is affecting users. You may also follow us on our [X/Twitter](https://twitter.com/StandardNotes) page, in case you're also active there."
