### ISSUE TITLE
Desktop Stable version still stuck at Desktop 3.194.0

### ISSUE THREAD

**Issue by github2099** [standardnotes/forum#3628]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/standardnotes/app'
2. Scroll down to 'Release'
4. See that Desktop 3.194.0 on Apr 24

**Expected behavior**
Update to the latest version when they are deemed stable.
On official site, https://standardnotes.com/plans?downloaded=linux always pointed to download the latest available version, (> 3.194.0, and as of writing, it's 3.194.9)

Please update the repo if the 3.194.9 is considered stable.

Another question, in changlog, I see this more than often, "Version bump only for package @standardnotes/desktop". What does Version bump mean in here?

Thank you

**Comment by effieeee** [comment]
Hi, this is intentional 🙏 While we push changes live to the web app, and it reflects the latest version right away (3.194.9, we delay releases on desktop and mobile by only marking certain versions as the latest after significant updates have accumulated, or only when critical updates are needed.

As for "version bumps", when changes are pushed on the app repository, new packages for all the app platforms are simultaneously made as well, but they don't always contain changes that affect only the desktop or mobile apps specifically. Releases which don't contain changes specific to any of the app packages are noted as "version bumps"

**Comment by github2099** [comment]
thank you!
