### ISSUE TITLE
FileSafe can't be disabled per note

### ISSUE THREAD

**Issue by jhermelink** [standardnotes/forum#363]
I want to disable FileSafe attachments for arbitrary notes to get more screen space.
This leads to the lost of FileSafe functionality in all notes after application restart.
Steps to reproduce (MacOS):
- Activate FileSafe in the Extension window
- Setup encryption keys and cloud integration
- FileSafe works!
- Now disable FileSafe in one note (Editor/click on "FileSafe" under "Editor Stack")
- FileSafe is disabled for this note, but enabled for all other notes - that's fine
- Exit StandardNotes application and restart
- encryption keys and cloud integration are lost in all notes!

**Comment by mobitar** [comment]
Hmm..I can't replicate this. By "lost in all notes", do you mean they are not loading properly? Or that no matter what you do you can't seem to get them to display? Because that would definitely be a display issue and not an actual data issue. If you were to deactivate then reactivate FileSafe again from extensions, would the items reappear?

Also, what version of the app is this?

**Comment by jhermelink** [comment]
* client version is 2.3.11 (MacOS)
* yes, if I deactivate then reactivate FileSafe again, the items reappear. But only until the next restart, so this is not feasible
* it's not a display issue. The FileSafe extension appears as not more initialized ("No encryption keys loaded / No cloud integrations configured") and is not usable
* I can reproduce this behavior on two different MacOS clients

**Comment by mobitar** [comment]
Any chance you can provide a video of this? That would be valuable. Otherwise I'll have to wait till someone else can reproduce this, perhaps with a slight twinge on replication steps that would allow me to replicate it myself.

**Comment by chucku** [comment]
I have exactly the same problem.  Client version 2.3.13 on Windows 10.  
I noticed it a couple of days ago but put it down to being a newby.  I tried it again after reading this thread and got exactly the same results as described above.  
The file that I had attached is still in Dropbox but no longer attached to the note.  
The FileSafe, CloudLink and Dropbox Sync extensions are still installed.  
Another note that has FileSafe in its Editor Stack but that I had not attached a file to is also complaining about no encryption keys and no cloud integrations configured.  
I then went through the rigamarole of re-installed the Dropbox Sync extension and generating a new key and re-attaching the file.  
While that was happening I checked another system (Xubuntu 32-bit client 2.3.13) and the file was still attached to the note on that system.  I tried downloading the file but it failed with an "error decrypting file" error.  I noticed that it had 2 copies of Dropbox integration and 2 keys for the file.  Shortly thereafter a 3rd key appeared (no doubt from the new file upload from the Windows machine).  It was fairly obvious which key was the good one from the timestamps but unfortunately I now had 2 copies of the identical file displayed with no way to tell which was the new copy.  I also couldn't delete one of the older keys since it was still associated with the now non-existent zombie file.  So I guessed that the right hand file was the new one and tried downloading it.  The decryption appeared to continue for a longer period but I then got what I can only describe as a "white screen of death" on the Xububtu client (the window occupied by Standard Notes went white and is non-responsive (I suspect this is a different bug but exposed by the current one).  
Back to Windows (if this all seems a bit stream-of-consciousness it is because I'm typing this as I check things) and I successfully downloaded the (new) copy of the file.  Dropbox confirms through its version history that I have now had 4 copies of this file uploaded to it.  
So there you have it: two bugs for the price of one.  
I went back to the Xubuntu machine and killed all the processes claiming to know anything about Standard Notes and the WSOD went away.  I started the Standard Notes client and guess what?  The file(s) that were attached to the note have now disappeared and it claims no integrations/no key.  So this problem exists on the Linux desktop client as well.  
On to my iPhone — I guess that client doesn't know anything about attachments?  
I hope this gives you a few more hints to what the issue could be :)

**Comment by chucku** [comment]
Another data point for you.  
- I closed my Windows client knowing that I had not removed the FileSave extension from any more of my notes.  
- When I restarted the attached file had disappeared again with the same no integration/no key.  So it would seem that it is not necessarily the act of removing the extension from the editor stack but simply the fact that some (any?) of the notes have it removed.

**Comment by mobitar** [comment]
Hey @chucku, thanks so much for the detailed feedback. Very bizarre. We know that the data is there; it's just the the FileSafe extension is not receiving the proper communication from the app. Are you able to open the dev console when this issue happens to see if it reports any errors? On desktop you can access it via Help -> Toggle Error Console (or ctrl + shift + i).

**Comment by chucku** [comment]
Right — not good news I'm afraid.  
- I uninstalled and reinstalled the FileSafe extension.  
- FileSafe then complained about being unable to communicate with anybody and that I should restart & try again (sorry I don't have the exact wording of the error message).  I then had to OK about 10 instances of the same message before everything settled down.  
- I then noticed that their were 2 copies of the FileSafe display at the bottom of every note.  
- The note that had the attachment which was missing from yesterday now had 3 copies of the file, 4 copies of the Dropbox integration and 3 keys.  Dropbox of course still only had one copy of the file.  
- Restarted SN and now only one copy of FileSafe was displayed at the bottom of the screen.  Still 3 files, 4 integrations and 3 keys.  
- I tried downloading one of the files but the programme hung on the decrypt (I gave it 30 minutes and the CPU utilization was about 6% which indicates to me it wasn't decrypting anything).  
- I then tried deleting all the files, integrations and keys and was successful.  
- At this time, since I had reinstalled FileSafe, all the notes had the FileSafe editor stack extension installed.  In fact every note had 2 copies installed according to the Editor pulldown (one red, one green).  
- I restarted SN and attached a new file to a note.  That worked successfully and I could see it on Dropbox and download it.  
- Restarted and everything was still OK.  
- Then removed the FileSafe extension from one note and restarted SN.  
- The attached file was still there!  Checked Dropbox and download, all OK.  
- Then removed the FileSafe extension from all the other notes.  The note with the attachment still OK.  
- Restarted SN and the problem had returned — no attachment, integration or key.  
- Did see errors in the console log attached.  
[SN-error-log-chucku-20181209T1855Z.txt](https://github.com/standardnotes/forum/files/2660927/SN-error-log-chucku-20181209T1855Z.txt)
- Reinstalled integration & key.  Tried attaching a different file but it hung while attaching, no more errors in log.  
- Restarted SN and back to square one — no attachment/integration/key.  
- I'm off to dinner.

**Comment by mobitar** [comment]
These are great repro steps, thanks. I'll give these steps a shot myself and hopefully replicate this issue. Also seems to be some interesting error in the log. That could be a good lead. 

Really appreciate your thoroughness! A rare trait, and makes development and bug-fixing so much easier.

**Comment by mobitar** [comment]
This issue has been fixed, and has been pushed live to the web app. Desktop app will be updated with fix tomorrow.

**Comment by jhermelink** [comment]
It's working now. Thanks!

**Comment by chucku** [comment]
I have tested 3.0.2 on Windows and Linux and everything appears to be fixed.  Thank you!

**Comment by mobitar** [comment]
Glad to hear that!
