### ISSUE TITLE
Is there a way to save the tags within the exported/backup text files?

### ISSUE THREAD

**Issue by Caldefredo** [standardnotes/forum#366]
I just got extended and tried out the back up funtionality. I prefer plaintext, so opted for the individual .txt files solution. However, it looks like tags are saved separately from the notes, which isn't much use.

Is there a way to save our tags within each file? 

Just trying to avoid redundant work of putting the tags into the note itself as well.

Thanks.

**Comment by mobitar** [comment]
Not with decrypted backups. These are simple, non-relational text files. Only way to preserve relationships is encrypted backups, or with the decrypted single file that is downloaded along with the zip.

**Comment by gerbenzaagsma** [comment]
I am currently considering buying extended too, but hesitating because of the above.

Just to be sure: is there, in principal, a way to export notes with their tags saved within the file? I would need this ability to use exported notes in other apps (and in general, would not like my notes + tags to be locked in).

**Comment by mobitar** [comment]
The relational text file is just simple JSON, so you could parse that if you wanted to. But otherwise, individual text notes in the zip folder do not contain anything but note contents.

**Comment by effieeee** [comment]
See here: https://github.com/standardnotes/forum/issues/638
