### ISSUE TITLE
'standard-notes-3.195.1-linux-x86_64.AppImage' Unable to sync. Says "Too many requests"

### ISSUE THREAD

**Issue by jiggneshhgohel** [standardnotes/forum#3699]
While using the latest version of Standard Notes Desktop app from my **Ubuntu 18.04** machine the notes sync doesn't work. It says 

>Too many requests. Please try again later

Please find below the screenshots

![Screenshot from 2024-07-22 16-25-40](https://github.com/user-attachments/assets/823ad38a-e83c-47ab-b132-b14350be1c96)

![Screenshot from 2024-07-22 16-27-10](https://github.com/user-attachments/assets/5c22cfaf-d3ae-4450-95a4-f7b0a8cdaaa0)

When I use the app from my iPhone it works as in what I note in my mobile app that gets synced to the server and on my Desktop app I can see the what I noted on my mobile-app.

Is this a known issue?

Thanks.

**Comment by effieeee** [comment]
Hi @jiggneshhgohel I'm sorry to hear that you're having trouble syncing on Linux, though I noticed that your screenshot had a prompt for an **encryption upgrade**, and this could indicate that we may need to look into this further on your account.

Can I ask you to contact us at help@standardnotes.com using your Standard Notes account email? We can help you troubleshoot this further from there, and we'll also need to check your account status since you're likely still on an older encryption version.

**Comment by jiggneshhgohel** [comment]
@effieeee Thanks for your reply. I rechecked and the sync is now working as expected. Looks like it might have been due to some temporary glitch. Sorry if this has cause any inconvenience. I am closing this. Thanks.
