### ISSUE TITLE
I cannot pay the subscription

### ISSUE THREAD

**Issue by sviii** [standardnotes/forum#376]
Hello, I am a student who want to buy the extension. But after I click the update button, I can't find any bottom allowing me to sign in. Could you help me with that? And how could I use student discount (I have already fill the student account form)?

**Comment by mobitar** [comment]
Hey @sviii, once you're in dashboard.standardnotes.org, enter your email in the lefthand column if you don't have an existing Extended membership, otherwise enter your email in the right column. After that you should see pricing options. The student discount cannot be combined with the current available discount.
