### ISSUE TITLE
Inconsistent tag inheritance behavior

### ISSUE THREAD

**Issue by mmlmrx** [standardnotes/forum#398]
Hello!
   I have noticed that tagging behavior is not consistent in regards to inheritance.  I created a tag called Games.PS4.Played.2018.  If I go there using the Folders extension, any entry I add there (using the +) only gets that particular tag - it does not get separate Games, Games.PS4, and Games.PS4.Played tags as well.  I can see how NOT automatically adding those tags is cleaner, but it also raises some organizational quirks - for example, I can't filter and see a list of all PS4 games.  So I don't know if that is a bug or intentional design.
   That being said, if I am on a particular note, and I use Quick Tags to add a new tag, that DOES add all sub tags.  This inconsistency means I have to pick a particular way to approach tagging, and NEVER do it the other way.  That being said, the tag list area does not grow if there are more than one line of tags, so I am guessing that the Quick Tags way is probably not feasible.

Thanks!

**Comment by mobitar** [comment]
Good point. This needs to be fixed. Currently the problem is that the core SN app takes care of tagging a new note within a tag, but the core SN app isn't aware of the underlying workings of the "Folders" extension, so it doesn't understand things like nesting. I'll have to find a good solution to this.

**Comment by effieeee** [comment]
Parent tag inheritance behavior can now be toggled on latest versions
