### ISSUE TITLE
Delete notes immediately rather than via Trash?

### ISSUE THREAD

**Issue by WritingSolutions2020** [standardnotes/forum#456]
I yesterday discovered that a Trash folder has become part of Standard Notes. Is there a way to bypass that Trash folder and just delete a note straightaway?

I'm missing the old simplicity of just being able to delete a note without then needing to pay a visit to Trash to finalize its deletion...

**Comment by mobitar** [comment]
There isn't a way to bypass it, but agree it would be nice to have an option to force delete. Will keep in mind.

**Comment by WritingSolutions2020** [comment]
OK -- for now.

I see one problem (or should I say _your_ problem? heh, heh) being the difference in u.i. behaviors between web client via browser versus desktop client. All operating systems support the use of SHIFT+DEL to bypass trash. But how can that "standard" be implemented in SN's various forms of access?

My top-of-the-head thought is that a conspicuous Empty Trash button or some such might help. At least I could just jettison the Trash-ed notes in one simpler action...?

**Comment by mobitar** [comment]
Could either be a shortcut like holding alt or shift, or perhaps keeping the note active upon trashing, so you can immediately access the next option of deleting permanently.

**Comment by WritingSolutions2020** [comment]
Just a quick addition. IF one cannot delete notes directly but must send them to Trash, THEN I'd prefer that I don't have to click past a modal "Are you sure?" dialog. It seems to much like a series of "are you sure you're sure that you're sure?" steps simply to jettison a note I no longer want...

**Comment by mobitar** [comment]
That would be ideal, but the scenario I fear is that if someone, especially a newer user, is not familiar with the trash concept, they'll accidentally press to trash a note, and see that their note has disappeared. And then I'd get emails like "my note just disappeared and I can't find it anywhere!" It seems a necessary sacrifice to avoid user panic.

I anticipate this because before the trash concept, people would email me saying they accidentally deleted a note, and if there was any way to get it back. And that was _with_ a confirmation alert.

**Comment by effieeee** [comment]
Closing, already implemented (hold **Alt** while right click context menu is open)
