### ISSUE TITLE
Up/Down arrow keys often don't work in Firefox

### ISSUE THREAD

**Issue by Egor3f** [standardnotes/forum#457]
1) Open web app in latest firefox, enter local password
2) Start editing any note you see at the list (by clicking into editor)
3) Try to use arrow keys on keyboard - up and down. They don't work! Left + right keys are still active.
4) Switch to another note or use any dropdown menu - they start working in the editor until page reload

P.S. I use paid extended version with several plugins. Described behaviour is in default simple text editor.

**Comment by mobitar** [comment]
Strange. I can't replicate this. When you're pressing the up/down keys, are your notes still being populated into the list? Can you try loading the web app, waiting about 30s, then performing the steps, and see if that makes a difference?

**Comment by Egor3f** [comment]
Yes, the app is loaded completely. I mean navigation caret up/down in editor, not in notes list.
Here is the video: https://www.youtube.com/watch?v=T8meYTQ3F1I

**Comment by mobitar** [comment]
Thanks for the video, that's very bizarre. Not quite sure what that could be. We'll have to wait to see if someone else has this issue. Can you try mashing on the keyboard when this issue is happening, by pressing random characters, and see if anything "unlocks" the up/down key? Just press a bunch of random keys on the keyboard and see if something eventually unhinges. Also worth trying are the alt/ctrl + arrow combination.
