### ISSUE TITLE
[Security bug?] Circumvent privileges settings

### ISSUE THREAD

**Issue by quartertone** [standardnotes/forum#477]
This initially seemed like it could be a security issue, but on second viewing I think it's mostly inconsequential.

Steps to recreate:
(Having previously set privileges such that a local passcode is required to change the passcode lock settings)

* Fresh log in (all local data previously deleted)
* Set local passcode while the notes/extensions/preferences are still loading
* Although the local passcode is set, I was able to change the autolock timeout setting without needing to re-enter my local passcode (unexpected behavior).
* Once my notes/settings loaded, the privileges/restrictions were applied properly, and I had to enter my passcode to change the setting again (expected behavior).

I haven't tested it, but I wonder if *Manage Privileges* would be similarly unsecured. I also wonder if this would be the case for privileges secured with the account password.

I'm not really sure this is a big concern, but maybe the one situation where this could be a problem is:

1. Authorized user logs in
2. (Sets local passcode or not)
3. Steps away while notes/extensions/etc load - for this scenario, assuming the number of notes is substantial enough for the loading to take some minutes.
4. Unauthorized user steps in and changes privileges settings, that would normally require authentication, during this vulnerable loading-state.

**Comment by mobitar** [comment]
Privileges are an account item, just like a note. And items are downloaded from the server, with oldest items coming in first. Since privileges are relatively new, then they might come in towards the end of a sign in session. In that case, you're right, you may be able to perform account protected actions while the data is downloading.

Two solutions I can see are:
1. Don't allow protected action while initial download has not completed.
2. Download privileges from the server before downloading anything else.

I'll have to think this one through.
