### ISSUE TITLE
Unable to install AppImage on Ubuntu 18.10

### ISSUE THREAD

**Issue by Max-Hughes** [standardnotes/forum#481]
After I download the App and followed the directions online i get an error message.

"./standard-notes-3.0.6-x86_64.AppImage/tmp/.mount_standaTesdgK/app/standard-notes: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory"

If i run "locate libgtk-x11" it shows 
/snap/gnome-3-26-1604/70/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/snap/gnome-3-26-1604/70/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
/snap/gnome-3-26-1604/82/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/snap/gnome-3-26-1604/82/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
so libgtk seems to be installed OK, I cant see what the problem is.

This is a fresh install of Ubuntu 18.10 running in a virtual Box VM (allocated 4 cores and 8Gb RAM)
Any ideas what I'm missing here?

**Comment by mobitar** [comment]
See if this answer helps: https://askubuntu.com/a/836144

**Comment by Shayhm** [comment]
I had the same problem on Ubuntu 18.10. The libgtk-x11-2.0.so.0 file was present but in a different location. It was installed in a snap. Things are worse under the standard Ubuntu 19.04 install because there is no libgtk-x11 file of any kind.

Per the previous post, I did verify I was running the correct app for my architecture.
