### ISSUE TITLE
Delete note with "delete" button

### ISSUE THREAD

**Issue by izznogooood** [standardnotes/forum#500]
You have a trash bin, congratulations  ;)

So now you can implement deleting notes that is selected when pressing the delete button ?

Pretty please!

**Comment by mobitar** [comment]
Still falls under keyboard shortcuts. https://github.com/standardnotes/forum/issues?utf8=%E2%9C%93&q=keyboard+shortcut

**Comment by yoichi0702** [comment]
Me too.
Please implementation m(__)m

I checked below link. But I cannnot understand. What is the current status of shortcuts?
https://github.com/standardnotes/forum/issues?utf8=%E2%9C%93&q=keyboard+shortcut

**Comment by riverbedlegend** [comment]
What about an icon to delete, like the themes icons at the bottom; this can be at the top of the note like the way we can click 'note locked' at the top to unlock? Or maybe at the location of the 'action bar', just add a 'delete' button to click and maintains same position for all notes.

This can at least save time and steps of clicking then moving the mouse to the delete option?

Then if we want to delete a lot of notes at one go we can just click nonstop while the deleted note changes to the next one. The button stays at the same location and we save clicks.

**Comment by mobitar** [comment]
The way I envision this solution most likely happening is that holding on the alt/option key on the keyboard with the note menu up changes its options. Similar to how on Mac holding alt and showing a menu changes its options. We'd swap trash for permanent delete in this case.

**Comment by yoichi0702** [comment]
Thank for your response. And I have wrong.
I'm apologize.

I request delete with delete-key not a delete-button like a iCloud Notes.

**Comment by izznogooood** [comment]
Can someone throw a line or two as to where this code lives (shortcuts). I had an hour on this but got cut off by packed code in a plugin that was unreadable.

**Comment by mobitar** [comment]
This code doesn't live. Shortcuts don't exist yet..

**Comment by izznogooood** [comment]
I dont get it... You can do basic things line bold text, code formating etc. This is not considered shortcuts ?

**Comment by User593** [comment]
Another vote for a basic function. Right now its 4 clicks/taps to delete a note. I have over 150 notes in another app I was hoping to migrate to SN but this is causing me to hesitate.
A button next to the note title or at least a way to highlight a note (or multiple) to delete immediately with key strokes would be infinitely more efficient. I do love the app otherwise so thank you!

**Comment by mobitar** [comment]
Please see here: https://github.com/standardnotes/forum/issues/288#issuecomment-506744618

**Comment by milynot** [comment]
I came to explore Standard Notes (from Evernote) with high hope.  But I cannot believe I cannot delete note with **del** key (Windows User).  This was discussed in March 2019.  It is now October 2020.  Is this going to be done soon?

**Comment by JaspalSuri** [comment]
Currently the dev team is working on ironing out bugs in the public betas of the desktop and mobile apps, but looking into issues with keyboard shortcuts is something that the dev team plans to look into.

**Comment by Robert-Ernst** [comment]
I'm currently planning to move away from Standard Notes because I still can't use basic shortcuts on the windows client.
I also filed some other simple QoL improvement here: https://github.com/standardnotes/forum/issues/1235

I use SN as my daily driver and using a mouse to click into the search field, click on the note, click into the note to edit or copy some text is bothersome if you do that hundreds of times per day.

@mobitar said he will look into it here: https://github.com/standardnotes/forum/issues/288#issuecomment-506744618

CTRL + F for sure is not working for me. I don't use any extensions. I have the newest version installed.

**Comment by effieeee** [comment]
Tracking here: https://github.com/standardnotes/forum/issues/1511

**Comment by atmoio** [comment]
Keyboard shortcuts are now available: https://github.com/standardnotes/forum/issues/1511#issuecomment-1322276205
