### ISSUE TITLE
Importing Spreadsheets?

### ISSUE THREAD

**Issue by mrmrtn** [standardnotes/forum#510]
I'm wondering if anyone has thoughts about importing spreadsheets into Standard Notes. I'm new to the app (and absolutely loving it so far). One of the most powerful features for me is the spreadsheet editor. If I try to copy and paste, however, I can only figure out how to paste the values, but not retain formulas. Any pro-tips on importing existing spreadsheets into SN? 

Thanks!

**Comment by mobitar** [comment]
Hey @mrmrtn, glad to hear you're enjoying the app! As for importing spreadsheets, it's a tricky topic. In my testing I've found that sheets created in native applications like Excel tend to not be so well optimized when imported into this editor. The spreadsheet editor software is quite intricate, and is not built by us, but by a third-party whom we license the software from. It actually featured an "import from Excel" option, but we had to disable it, because it would create files so large for even simple sheets that it would slow down performance drastically. (This is because if you, say, set a format/color for a row of 200 cells, it wouldn't apply just 1 rule in the code to cover the whole row, but it would individually create a rule for every single cell, causing file sizes to balloon quickly).

For now, until we get this editor out of beta, it's recommended for small to mid-size spreadsheets created inside Standard Notes, and not imported from elsewhere. But, best to do your own testing for that to see what kind of performance you can handle. As for formulas, another one of those tricky issues. I'd have to experiment more but I don't believe there's a good solution for retaining formulas from other spreadsheet editors.

**Comment by mrmrtn** [comment]
Sounds good, @mobitar. Thanks for the response! Loving the app. :)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@moughxyz is it possible to export a spreadsheet to excel?

**Comment by atmoio** [comment]
Yup:

![Screenshot 2023-11-27 at 8 26 43 AM](https://github.com/standardnotes/forum/assets/3277844/afebf814-fbb6-49b4-91fc-df9368a6d989)
