### ISSUE TITLE
Can't screenshot when password or fingerprint lock is set to "Immediately"

### ISSUE THREAD

**Issue by chanclr** [standardnotes/forum#511]
So on the Android app, I can screenshot within the app just fine. However this stops working when either Passcode or Fingerprint Lock is set to "Immediately". When trying to take a screenshot i get the "Taking a screenshot isn't supported by the app or your organization" message. This issue does not happen when they are set to "On Quit".

**Comment by mobitar** [comment]
This is by design. It's so that when you go to your app switcher/multitasking view, it blocks the contents of the app if it's set to Immediately. The feature is known as screenshot privacy in general. Perhaps though in the future it might make sense to decouple this option from the passcode timing and make it its own option.

**Comment by chanclr** [comment]
I see, forgive me this is my first time posting but this is where i close issue?

**Comment by mobitar** [comment]
Ha, on the forum open/close doesn't really matter :)
