### ISSUE TITLE
cannot "scroll" title on locked note on Android

### ISSUE THREAD

**Issue by chanclr** [standardnotes/forum#512]
so on the Android app i sometimes have a note with a particularly long title. the issue is that i can't "scroll" through the title, but only if the note is locked. this isnt that big of an issue since i can still see the full title in the view with all the notes.

**Comment by mobitar** [comment]
Hmm..true that the title only takes up 1 line. We wouldn't want it to take up anymore since every pixel in height we give it is one pixel less height from the editor, which is typically more important. But what do you mean by if the note is locked? I haven't noticed any distinction in this behavior whether the note is locked or not..

**Comment by chanclr** [comment]
oh sorry, i meant horizontal scroll, it takes up one line. Hard to explain but its like if you have a long title and you're viewing a note inside the mobile app, and you drag the title with your finger horizontally

**Comment by mobitar** [comment]
Oh I see. I had taken "the issue is that i can't "scroll" through the title, but only if the note is locked" to mean that you can't scroll it, but you can if it's locked. But you mean the opposite right? In that case, true, when the note is locked, the title field is completely disabled. I don't think there's any good way around this..

**Comment by chanclr** [comment]
ah, okay then
