### ISSUE TITLE
The Android version feels like a slower, unoptimized iPhone port

### ISSUE THREAD

**Issue by Pentaphon** [standardnotes/forum#521]
I want to enjoy Standard Notes for Android but the Android app is so slow and feels like a bad iPhone port. Can we finally get an Android app that is actually 100% Android native?

**Comment by SiGamma** [comment]
The iOS app is not native either, it’s written in React Native and therefore not native to either iOS or Android and the codebase is shared between the two. Considering RN was chosen due to limited resources (only a single developer), I don’t think we’ll see native iOS and Android apps. Although I would love to have a native app, unfortunately, having separate codebases is a lot of extra work and isn’t realistic.

**Comment by mobitar** [comment]
@Pentaphon I'd have to say your outlook is highly subjective and not commonly shared amongst people that use the app.

**Comment by Serkan-devel** [comment]
Porting to React-native seems to be a downgrade most of the time.
Similarly to Electron, it requires more resources mostly requires a newer device considering it being interpreted by a browser, rather than more native implementations.

Maybe on could use the Kotlin codebase, which can be shared between iOS and Android while running more performant

**Comment by Serkan-devel** [comment]
One could also try Flutter with similar results. Might actually be easier than with Kotlin

**Comment by Pentaphon** [comment]
@mobitar With all due respect, the reason why we don't see this opinion more often is because the only place to discuss this app is a Github issue page. There's no actual forum. I think a lot of people would prefer a native Android app over what we currently have, but at stated, if you don't have the resources to create a native app, there's not much that can be done.

**Comment by Serkan-devel** [comment]
But one can develop using [Flutter](https://flutter.io) with similar resources when doing with RN, but with better results.

**Comment by Pentaphon** [comment]
@Serkan-devel I hope the dev takes your advice.

**Comment by myreli** [comment]
Since the creation of this issue, SN mobile has been iterated severely, including the latest big refactor, which solved most performance issues on Android, and the team is now ironing out a few reports and trying to achieve the expected native feel across platforms while maintaining a single, hybrid code-base.

I'm currently triaging older issues, and since this one is more of a discussion than a report/request, I'll close it and leave a few resources on how SN approached the cross-platform development of the apps with a small team for those interested in reading: 

- [React Native is not the future](https://standardnotes.com/blog/react-native-is-not-the-future)
- [Our new mobile experience is launching soon](https://standardnotes.com/blog/our-new-mobile-experience-is-launching-soon)
