### ISSUE TITLE
What does "Optimizing data..." do?

### ISSUE THREAD

**Issue by ddddavidmartin** [standardnotes/forum#537]
Good day,

when I open the web view it shows "Optimizing data..." after the decryption and synchronisation. What does it do? Shall I leave the tab open to let it do its thing?

There is no concern from my side, I'm just curious what's happening.

Thanks!

**Comment by mobitar** [comment]
Hey @ddddavidmartin, we talk about this in the 3.0.8 release notes (last bullet): https://github.com/standardnotes/desktop/releases/tag/v3.0.8

It shouldn't take more than a minute. Is it getting stuck for you? If so, how many note/tags do you have total?

**Comment by ddddavidmartin** [comment]
Hmmm, I just updated the desktop version and I did not see the "optimizing data" notice. On the web though in https://app.standardnotes.org/ it always shows the notice at the bottom.

I have 450 notes and 9 tags.

**Comment by ddddavidmartin** [comment]
So, I logged out and back in again and I think it worked itself out. At least I'm not seeing the notice anymore.

I'm happy to leave it at that.

**Comment by mobitar** [comment]
Hmm strange. I'll have to keep an eye out for more reports regarding this. But glad that a sign out did the trick!

**Comment by bluescreenfun** [comment]
Hi @mobitar , I have the same issue on the windows desktop application. Ever since the update, which I installed multiple weeks ago, the message "Optimizing data…" has not gone away. I have the application open for multiple hours every day, so it has definitely had enough time. 

Since logging out and back in fixed it for ddddavidmartin, I did just that on my desktop app to see if it would also fix it for me. I also opened the web version to see if I had the same problem there. I have the same message in the web version. I left both versions open for about 30min, but the message is still there in both versions. 
It doesn't affect anything while using the application as far as I can tell, but it worries me a bit that I don't know what it's doing in the background. 

I have 330 notes and 14 tags. 

If I go under "Help" -> "Toggle Error Console", I see 5 instances of `Error decrypting item` followed by `Auth hash does not match, returning null. ` messages and one instance of `Uncaught (in promise) TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined at MigrationManager._callee34$`
Full stack trace (I've replaced my username):
`Uncaught (in promise) TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at MigrationManager._callee34$ (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:56579:52)
    at tryCatch (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:64017:40)
    at Generator.invoke [as _invoke] (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:64251:22)
    at Generator.prototype.(anonymous function) [as next] (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:64069:21)
    at step (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:61875:30)
    at file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:61893:14
    at Promise (<anonymous>)
    at F (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:62288:28)
    at Object.<anonymous> (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:61872:12)
    at Object.handler (file:///C:/Users/REDACTED/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/compiled.js:56729:27)`

I have the exact same errors in the web and desktop version.

If there's any other logs that I can send you, I'll gladly help.

**Comment by ddddavidmartin** [comment]
Hmmm, I think I did have a couple of notes that could not be decrypted that I deleted around the same time. Maybe that helped.

**Comment by mobitar** [comment]
@bluescreenfun can you try desktop version 3.0.14?

**Comment by bluescreenfun** [comment]
Some more info: 
I just looked at the desktop version on my home PC and there it did't show "Optimizing data…". There were also no errors in the Error Console. I signed out and back in and now it does show "Optimizing data…" and the errors are also here. This was before I installed the update.

@mobitar I just installed the 3.0.14 update and, oh boy what a sight to be greeted with.

![grafik](https://user-images.githubusercontent.com/47524656/59947719-47987d00-946e-11e9-8a25-63da55fd11bb.png)

It also seems that it has logged me out. One "Clear all local data" and sign-in later and we're back to normal. 

The errors still remain, and it is still showing "Optimizing data…". @ddddavidmartin , how did you find and delete the undecryptable notes?

**Comment by ddddavidmartin** [comment]
>  how did you find and delete the undecryptable notes?

I scrolled through all the notes on the webinterface and manually deleted the ones with errors. I think they stood out in some way so there were pretty obvious. They may have shown an error in red. I'd make a backup of all notes in any case though.

**Comment by mobitar** [comment]
@bluescreenfun does a sign out and and sign in fix the Missing Keys issue? You may have seen that if you upgraded the app but then accidentally access an older version. If you're still seeing this, please email me at mo@standardnotes.org with your account email so I can investigate further.
