### ISSUE TITLE
[Question] Does Standard Notes focus on paring down data usage?

### ISSUE THREAD

**Issue by yingw787** [standardnotes/forum#540]
I've been using Standard Notes for some months now and I love it. One thing that does bug me is how much data I need to send back and forth to the server. I might be an edge case as I cancelled my home Internet and have a small (1GB/mo.) cellular plan, but I watch my data usage closely, and I noticed Standard Notes used about 1-1.5MB over a month. In comparison, Bitwarden used about 150KB per month (although I do reference Standard Notes over cellular much more than BitWarden). Does Standard Notes keep KPIs regarding data usage?

I believe Dan Luu mentioned how reducing app bloat may help reach more customers: https://danluu.com/web-bloat/

Geoff Greer mentioned how optimizing performance gives developers empathy for users who may not be as privileged to afford lots of network or CPU usage: https://geoff.greer.fm

**Comment by mobitar** [comment]
1-1.5MB per month sounds about on par. This is largely use case dependent though. Notes are going to be much larger in size on average than a password, so a comparison between a notes app and a password manager would be mismatched. We don't make unnecessary network requests. The app downloads whatever data has changed since last sync, and uploads data when it changes on the local device. We don't do incremental uploads though when you change a note—the whole thing is encrypted and uploaded every time you make a change. Uploading just deltas might save on bandwidth, but is a trickier design to implement when dealing with encryption and content agnostic servers.

**Comment by yingw787** [comment]
Sounds good; just wanted to make sure this concern was visible. Thanks for the prompt reply!
