### ISSUE TITLE
Images appear to not be synced or stored locally within Bold editor

### ISSUE THREAD

**Issue by scuba-tech** [standardnotes/forum#557]
Screenshot attached: when trying to use inline images with the **Bold Editor** , they only work if I'm connected to the internet!

This means that, yes, I'm unable to work with any of my inline notes, even if they've been synced and viewed previously, unless I'm online.

macOS v. latest.whatever
Bold Editor v. 1.0.3
Standard Notes v. 3.0.9

<img width="1195" alt="Screen Shot 2019-05-21 at 11 22 00" src="https://user-images.githubusercontent.com/35608185/58109042-e0f81900-7bba-11e9-93de-0f9e787868bd.png">

**Comment by mobitar** [comment]
That's correct, as your files are ultimately stored in your Dropbox or Google Drive. When you view a note, we download the files and decrypt them for temporary display. We definitely don't hang on to them across application sessions. File behavior is a speciality of the Bold Editor and not the Standard Notes application, which is by design. So disk caching is currently out of question, and would stand to degrade security were it possible.

However, images do live in memory as long as the Bold Editor is opened. If you switch between notes, and both use the Bold Editor, then the images will display immediately. However if you switch to a plain note and then to a Bold note, since the Bold Editor is now destroyed and recreated, the images will need to be re-downloaded.

Whether we optimize for offline behavior remains to be seen. Ultimately we are still a text-based note-taking app, and not big on files in general.
