### ISSUE TITLE
[Extensions]: Please mark Extensions, that are developed by SN

### ISSUE THREAD

**Issue by hurzhurzhurzhurz-oik** [standardnotes/forum#559]

**Comment by MustachedMario** [comment]
Lost connection while writing this topic...

Please mark all extensions that are developed by SN.
So we can simple identify 3rd-party extention.
(or just give us a filter in the extention overview)

Actually, there is not a single 3rd-party extention, that works/looks/render/behave nearly indentical on mobile/web/desktop. Bug reporting/fixing is also difficult thing. You also never know, how long a 3rd-party extention is maintained or active developed.
This is something, i never seen on 1st-party extentions.

**Comment by mobitar** [comment]
All extensions have some sort of custom work done by us. And most extensions rely on some sort of 3rd party library. This distinction wouldn't be relevant to anyone besides a developer audience, so I don't think we'd call this out in the list of extensions. But for the record, only editors are based on third party components. Other extensions are all first party. Out of the editors, the Simple Task Editor and the Simple Markdown Editor are first party. Most of the rest rely on 3rd party components that we do not like to get into the internals of when contemplating changes or fixes.

**Comment by MustachedMario** [comment]
Ok, calling of 1st and 3rd-party extensions seems not correct, because both maybe use external components.

But yourself called the "Simple Task Editor" and "Simple Markdown Editor" as 1st-party editors, and that is exaclty what I mean. Because this editors (beside plain text) are working flawless on all platforms. All other Editors (i previously called it 3rd-party) degrading the mobile version to a "viewer" only (tested only iOS), because all of these editors have there own problems.

Just a quick example that is representative with tons of issues i have with "3rd party" editors:
- Create a note with the new bold editor
- Note layout should be something like <10 lines text>, <5 colum table>, <10 lines text>
- Fill the table with a few words
- The table should now wider as the mobile screen

Look a this note on mobile (iOS) = **Render issues**
- The first issue i see is, that the table headers background is not rendered completely

Open this note on mobile (iOS) again = **Messed up editor / note**
- Then tap on a header in this table to edit them
- The table now jumps under the editor button row, you can't read anything from table anymore
- You also can't edit anything, because the cursor is now in one of the editor button text
- Yep, you can edit the editor button text
- You also can't leave the edit mode execpt hittting the back button.

Open this note on mobile (iOS) again = **weird behavior**
- just tap the html output button, nothing else
- now, sometimes you are in viewing mode, sometimes you are in edit mode

Open this note on mobile (iOS) again = **weird scrolling**
- just tap the html output button, nothing else
- make sure you are not in edit mode, so you can scroll the html output.
- scroll to the end of the note (scrolling behaves 'sticky')
- if you reaches the end, now scroll the html output down, the complete note is now scrolling including  the editor buttons.

Open this note on mobile (iOS) again = **wrong cursor position while edit**
- scroll to the end of the note
- tap on any text on notes end to edit
- the iOS Keyboard is now over the text part that we would edit
- cursor positinon is lost, you have to scroll down again
- hey guess what? the note is again under the editor buttons

**All this issues i have found in under 3 minutes.**
As i wrote above, this is just representative for other editor. **All** have their own issues. I'ts so frustrating.
This is the reason, why i wished a indicator option, to see if a extension is "1st" ord "3rd" party.

**Comment by mobitar** [comment]
The Bold Editor is a brand new release, so if there are issues, please create them: https://github.com/sn-extensions/bold-editor. I'm actually waiting on issues to be created so we can improve it.

Otherwise, the fact that editors on mobile do not create an experience as powerful as on desktop is embedded in the very nature of the architecture. We actually used to display an alert on mobile saying that these editors are web-based, and thus, your experience will be like rich-text editing with Safari.
