### ISSUE TITLE
Extensions not working "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by sucrose** [standardnotes/forum#56]
All extensions are showing this error: _We're sorry, but something went wrong. If you are the application owner check the logs for more information._

![image](https://user-images.githubusercontent.com/5590958/29259722-ab76a370-8092-11e7-8e24-71044ff7e53f.png)

**Comment by mobitar** [comment]
This must be something with your subscription. Please email me at mo@standardnotes.org with your account email so I can look into this.

**Comment by sucrose** [comment]
Now none of my Theme extension work... nor does my Simple Markdown extension. Were these only working because of a bug?

**Comment by mobitar** [comment]
Hey Jon, yes these were only working due to a bug I'm afraid :/ I hadn't realized you could still access certain extensions without a paid subscription. Apologies for the confusion.

**Comment by sucrose** [comment]
Mind if I ask why I ever had access to begin with?

**Comment by mobitar** [comment]
Extended accounts used to be free to sign up for (although without any extensions, just a sort of placeholder). This system was changed so that you had to go through the paywall to enter the Extended dashboard. However, a few days ago I caught a bug that allowed some extensions to still be accessed. So I just closed that loophole. Sorry about the inconvenience.

**Comment by sucrose** [comment]
I purchased an Extended account and the extensions are now working again -- thanks for your hard work on this utility.
