### ISSUE TITLE
Simple Markdown Editor synced scroll causing lag

### ISSUE THREAD

**Issue by theoosborn** [standardnotes/forum#569]
I've noticed recently that the scrolling (using scroll wheel on my mouse) for the Simple Markdown Editor seems slow and laggy compared to what it used to be and the other editors.

The GIF I made of this was too large to attach, so you can see it [here](https://www.squareearth.net/scrolling.gif).

**Comment by mobitar** [comment]
We did just release an update that adds synced scroll to the Simple MD editor. (So that when you scroll the left panel it scrolls the right). 

@dagjaneiro (who helped make this feature possible):
- I think we should disable synced scroll if only one panel is open
- I believe the scroll listener needs to be handled in a special way, either by debouncing, or using something like [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). This way, if the on scroll event is called 300 times a second, it's only processed a maximum of 60 times.

**Comment by theoosborn** [comment]
Ok, thanks for explaining.

**Comment by mobitar** [comment]
This is now fixed with 1.3.5.
