### ISSUE TITLE
Prompt user to sign out and in again when it is required by software update

### ISSUE THREAD

**Issue by justyn** [standardnotes/forum#58]
Hi,

I just installed the latest version of Standard Notes (1.2.4 from 1.1.1), as an AppImage on Linux.

The new version was already signed in and seemed to be working as before. But then I realised one of my tags had disappeared, and one of my notes was failing to decrypt (the rest were fine).

I read a suggestion that this might be related to an update, and to sign out and sign in again, which did the trick. Everything seems fine now.

This issue is just a suggestion to have a method of recommending to users from within the app that they should sign out and sign in again, when you have made a change that requires it, to prevent any confusion next time something like this happens.

Thanks.

**Comment by mobitar** [comment]
Hey Justyn, totally, I hope to have this process down smoother in the future. It should actually be better with security updates in the future being available through the account menu under "Security Update Available" (once there's one available). That should make it so that a sign out isn't required.
