### ISSUE TITLE
Feature Request: Family/Team Plan

### ISSUE THREAD

**Issue by fivesoftware** [standardnotes/forum#583]
Standard Notes is a great tool. One feature that would make it particularly helpful would be the option a shared folders between accounts.

1Password have a feature like this with their Family Plan and it works really well and is really easy to use. They give you secure password vaults that you can share. Because you've specifically setup your family/team and invited members to your family/team plan there is trust for encrypted data. This hopefully provides a mechanism to share whilst retaining encryption of data.

The current limit to 5 members which is fine I think for a first price point.

**Comment by mobitar** [comment]
Sharing would indeed be great, but it's a little out of scope for us. It would require us to really consider an entire redesign of the structure of the application. It definitely represents a great market opportunity, but it introduces additional complexity that would jeopardize our focus on simplicity. My goal is for the extensions architecture to be fully capable of supporting something like this so that third party developers are free to create something like this on their own.

**Comment by jacobcantele** [comment]
I'd like to second this feature request, even if implemented as an extension as you recommend @mobitar 

Even a super MVP solution of a single note being shared between two accounts, or something like that. Ultimately, I'm looking to be able to share private notes and documents with my colleagues and family.

**Comment by effieeee** [comment]
Subscription sharing with up to 5 accounts now available!
