### ISSUE TITLE
Missing signatures [Windows]

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#602]
On Windows, most files containing executable code (DLLs) have not been signed at all, and some only by the original vendor (not StandardNotes). Also, while the original installer is signed, the built-in updater is directly calling on executable code files which have not been signed. 

This means it is currently not possible to use StandardNotes in environments using signature-based code integrity enforcement.

**Comment by mobitar** [comment]
Can you post specifics? As far as I know the entire package should be signed.

**Comment by nluck** [comment]
Hey, thank your for your response!

There's two points where signatures are missing:

1. Certain third-party files containing executable code (in this case: DLLs) are not signed. For example: _ffmpeg.dll_, _node.dll_, among others.
2. The installer/updater uses an "external" file containing executable code (_nsis7z.dll_) stored in an external folder (_AppData/Local/Temp/_), probably to decompress files.

Both open the user up to the risk of DLL hijacking, especially because the installation directory from where the executable code is sourced is user-writable. Security solutions which use digital signatures to validate or restrict executed code don't rely on the primary executable file (in this case: _Standard Notes.exe_), but also check dynamically loaded code from other files for valid signatures.

**Comment by mobitar** [comment]
We use [electron-builder](https://github.com/electron-userland/electron-builder) to manage executable signing. It's possible however that we're running an older version, and that there are improvements to this area in new releases. Will have to check recent discussions on that repo.

**Comment by nluck** [comment]
Ah, it seems you are using an older version of electron-builder which does not support the (optional) DLL signing feature.

Newer releases do support that feature using the _signDlls_ switch, see [here](https://www.electron.build/configuration/win).

**Comment by mobitar** [comment]
Nice, glad to see that's implemented. Will hopefully enable this when we update electron-builder.
