### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shompoe** [standardnotes/forum#667]
Would it be possible to see a roadmap for forthcoming releases of the project as well as what you are working on at the moment? Perhaps you can put this on the @SN blog? Would be great to find out if our most wanted features will be coming along soon and to make suggestions for anything that is not mentioned.

**Comment by mobitar** [comment]
We do not have a roadmap. Please see here: https://standardnotes.org/longevity

**Comment by oliveconstant** [comment]
While I fully support the philosophy behind the project, I also think there may be users like me who can't decide if it's worth paying for Extended, given that the future of the project is unknown.

As it currently stands, Standard Notes is clearly the most promising open source client-side encrypted notes application that is also cross-platform. But if you look at the features (even when considering extensions), many basic things are still missing. Just take a look at the various feature requests here on GitHub.

Being more transparent about what's next in Standard Notes could actually build more trust in your users. You don't have to publicly announce deadlines, because we all know how difficult it is meeting them (and when this doesn't happen, users complain a lot).

I don't know if my opinion makes sense to you, but I felt the need wanted to share.

**Comment by JaspalSuri** [comment]
I completely understand. I think it's best to purchase Extended only if you're happy with the current set of features that the Standard and Extended plans offer, given that we can't predict when certain features will arrive as plans can change or work in other areas needs to be prioritized over them. (You can still support our work by sponsoring us on GitHub in the meantime. 🙂) By providing a public roadmap, we might cause users to subscribe and wait for a feature that needs to be postponed and would hate to do that. 

That said, here are a few features that the dev teams plans to work on (in no particular order):

- The ability to select and batch-manage multiple notes outside of the batch manager
- The ability to natively upload files and upload images within the apps
- The ability to remotely terminate sessions 
- The simplification of privileges and protections

**Comment by chriswayg** [comment]
> * The ability to natively upload files and upload images within the apps

Will this include the ability to insert uploaded images directly inside Markdown text (similar to Bear Notes or Typora)?

I would love to fully switch to Standard Notes, but not being able to insert images inside markdown text is still a deal breaker.

**Comment by effieeee** [comment]
Closing this by mentioning that another way to get some updates on what we're planning to work on is to subscribe to our blog in the link below!
https://blog.standardnotes.com/
