### ISSUE TITLE
[Bug] File can be attached to a locked note

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/forum#671]
I have locked a note for testing. I cannot modify the note content itself, which is expected, but I'm still able to attach or delete a file. I was expecting an error when trying to attach a file.

**Comment by mobitar** [comment]
Hmm..the thing is, attaching a file doesn't modify the note directly. It creates a separate file object that points to the note. So the note is completely untouched. But I can see how this can be confusing. I think for consistency we should indeed add a check so that attachments aren't allowed on locked notes.

**Comment by MorgothSauron** [comment]
> Hmm..the thing is, attaching a file doesn't modify the note directly. It creates a separate file object that points to the note. So the note is completely untouched. But I can see how this can be confusing. I think for consistency we should indeed add a check so that attachments aren't allowed on locked notes.

You got a good point: the content of the note itself is not modified. Maybe I was a little too quick with the "bug" label. I was just testing locked note and I wanted to see what happens when adding file ;)
