### ISSUE TITLE
[Feature Request] Pop out a note into a dedicated window

### ISSUE THREAD

**Issue by raphmim** [standardnotes/forum#677]
One thing that is a bit frustrating with the current UX is when working on several notes at once or when working on one note when needing to check things in other notes. Currently, we need to constantly go back and forth between the "main" note we're working and the other ones we need material from. If we are working in No Distraction, it's basically hell. 

It would be amazing if we could pop out an unlimited number of notes, each into a dedicated window, as well as have the "main" window (with the list of notes) separate, so that we can resize and move those around easily and work simultaneously on many notes, or work on a note while simultaneously browse through the list of notes, etc.

Thanks

**Comment by bschlagel** [comment]
I like this idea! But also want to note a few things I think might be simpler and help with achieving a similar goal of making it easier to switch between editing multiple notes.

One:
Most important and crucial for further enhancements here is saving your position in a note. Related request here re: remembering scroll position on a per-note basis: https://github.com/standardnotes/forum/issues/276
Also strikes me that you'd need to save *cursor position* as well, to be able to quickly toggle between notes and copy/paste, resume typing, etc. This alone would go a long way to improving the experience of working with multiple notes

Two:
Next simplest (at least I'm guessing) and related to longstanding requests for keyboard shortcuts — would be great to have keyboard shortcuts for navigating back/forward in your note-viewing history. Just like web browser history, basically. In Scrivener, for example, cmd+[ and cmd+] navigate forwards/backwards enabling you to quickly navigate to your previously viewed note, and back again. Or, simpler approximation, one shortcut to toggle between current and last-viewed note (without full history) could also be useful.

Three:
A splitscreen view would be very useful — could basically be a button somewhere in the menu bar or action bar that would toggle showing a two-column editor view, with each one displaying its own editor independently. Scrivener, again, does this very well.

Four:
Then finally the ability to open an arbitrary number of notes as separate windows seems like it'd be similar to the above but quite a bit more complex, and wouldn't really work on the mobile or web apps. Which is why I'm thinking the other things listed above would probably be a more realistic place to start :)

**Comment by Raph33** [comment]
Thanks @bschlagel! Here are some comments:

> One: remembering scroll position on a per-note basis: #276
Also strikes me that you'd need to save cursor position as well, to be able to quickly toggle between notes and copy/paste, resume typing, etc. This alone would go a long way to improving the experience of working with multiple notes

Yes, absolutely!

> Two: keyboard shortcuts for navigating back/forward in your note-viewing history

I don't work with keyboard shortcuts much, but interesting idea. But it wouldn't do the trick as soon as you start working with more than two notes

> Three: splitscreen view 

That could be interesting, but again, once you're working with more than two notes, this isn't good enough.

> Four:  the ability to open an arbitrary number of notes as separate windows seems like it'd be similar to the above but quite a bit more complex, and wouldn't really work on the mobile or web apps.

I beg to disagree :) I think opening notes as separate windows gives users the freedom to organize as their wish, accommodate basically all use cases. 
Re: web app: this issue isn't as relevant, as you can simply open SN in two different browser windows and work with those/resize/move as you wish
Re: mobile apps: I don't think this should be a focus for mobile apps; showing two notes at once _plus_ the keyboard is never going to render a decent user experience (as we can see on split-screen mode on Android)

**Comment by bschlagel** [comment]
Totally agree there are lots of different use cases here! My comment is partly based on my own experience and thoughts for what would be useful, but also based on seeing how @mobitar tends to think about feature requests and building things in a sustainable approach with cross-platform support.

My main experience using an editor with multiple editor windows comes from Scrivener, as well as code editors like Atom / Sublime Text. For me personally, even on a large 27" monitor, I very frequently have split-pane view (two column) but almost never have 3+ editor windows open at once.

Same even with other apps that allow multiple windows, like web browser, or Finder on MacOS, I like to have two windows side by side (or full screen and switch using cmd+`). In my experience it's hard to really use more than that productively at the same time. Also, to keep things clean I use Spectacle, an app that lets you use shortcuts to snap windows to precise parts of the screen (e.g. 1/2 or 1/3); I never want to manually drag multiple windows around. So from my POV, having a split view would get me 90% of the way there.

But I understand that's personal preference and it may be useful to specify other scenarios where multiple editor windows would come in handy. I'd typically be using one doc for reference and one for writing, or copying things from one doc to another. In those cases two works, but I'd be curious e.g. what the max # of windows you could see opening simultaneously might be.

To reference Scrivener again, they do have a feature where you can open docs as a sort of quick reference pane, in a lightweight way separate from the main editor (where you'd have one or two docs open in a more permanent layout). Maybe there'd be a relatively lightweight way of enabling that via a plugin.

Anyway I think all this could be great, just thinking pragmatically about what might be realistic to add, and whether there could be a solution that would work for most use cases with a much smaller engineering effort than full multi-window support. Again I too am just speculating so far :)

**Comment by Raph33** [comment]
You're right, I'm not sure how much work it would be to add full multi-window support. But I do believe it would be a game changer in terms of productivity... 

Here are some examples of my use cases, just from my 13" inch laptop:
- the main note I'm working on is on the right half of the screen, and two other notes I'm using as reference are in the top left and bottom left corners
- a video conferencing window on the left half, a note on the top right corner to take notes and a note on a past meeting/other thing I need to have access to on the bottom right corner
- the main note I'm working on is on the right half of the screen, and the "main" window is on the left half, where I browse through different notes in different folders
- I sometimes have four notes opened simultaneously, one in each corner...

(PS: I use BetterSnapTool to easily snap windows to parts of the screen, but glad to learn about an open-source alternative like Spectacle :) though in my opinion that doesn't impact the need for multi-window support)

**Comment by bschlagel** [comment]
Gotcha :) I've been using iA Writer today and they have both 1) ability to open multiple windows that are basically complete self-contained instances of the app, and 2) ability to open documents as new tabs, using the native Mac UI, that can be switched to via keyboard shortcut

I think that'd definitely be cool to have. The tab thing does seem more OS-specific so not sure how it would translate cross-platform. But maybe there's a simpler way to just allow multiple windows that each appear almost as full instances of the app as iA Writer seems to do. Really not sure what would be easiest to implement here; maybe @mobitar will chime in.

At any rate, I think whatever approach may end up being best for supporting multiple windows/editor panes, an awesome start would be saving per-note scroll and cursor positions. That alone would be super helpful since right now even manually switching back and forth to edit between multiple notes is kind of impossible.

**Comment by Raph33** [comment]
@mobitar did you have a chance to think about this? Would love to hear your thoughts

**Comment by mobitar** [comment]
My thoughts on this vs when I expect we can execute this are years apart :) I agree it would be useful.

**Comment by brandontle** [comment]
Would love to see multi-window support on the desktop app. For reference, my primary use case is privacy when taking notes at work (or with other people). Currently, unless I drag the notes list to the left side to hide, the preview of my other notes are viewable by those who are sharing my screen.

**Comment by effieeee** [comment]
Tracking here https://github.com/standardnotes/forum/issues/958
