### ISSUE TITLE
Markdown standards are not always supported 

### ISSUE THREAD

**Issue by J10ne** [standardnotes/forum#701]
Hello guys,

First of all I really love standard notes!
The only things that's frustrating me -and preventing me from subscribing yearly- is the fact that SN is not 100% compatible with markdown.

Example:

==example1== doesn't show up like it should.

[example2][example2] - doesn't work at all
[example2](example2) - opens a new empty window

Tried this with simple and advanced markdown editors. Both the same result.
I'm using Linux.

**Comment by J10ne** [comment]
Anyone?

**Comment by J10ne** [comment]
Hi, sorry for the late reply.

When I try to link to a header like in the example below, SN always opens a new browser window. I expect SN to jump straight to the header..


[note](#note)
some text
some text
some text
#### note 

The example below should (at least in other MD editors) highlight text:
==notes==

**Comment by JaspalSuri** [comment]
I've taken note of this. Thanks for clarifying!

>The example below should (at least in other MD editors) highlight text:
>==notes==

Can you give an example of an editor which will highlight text with that syntax?

**Comment by J10ne** [comment]
Typora has this option.

![sn1](https://user-images.githubusercontent.com/55854066/76943796-3b0f5b00-6900-11ea-876e-713cff17d5db.PNG)
![sn2](https://user-images.githubusercontent.com/55854066/76943810-3ea2e200-6900-11ea-928c-df1cd5529592.PNG)
![sn3](https://user-images.githubusercontent.com/55854066/76943814-41053c00-6900-11ea-89d9-8fdc5ccc3f0b.PNG)

**Comment by baptiste-grob** [comment]
Because of Markdown's nature as a set of loosely-defined conventions rather than specific rules there are a lot of different implementations and unless you follow a popular spec like (CommonMark)[https://commonmark.org] you are bound to have some incompatible things… `==text==` isn't in CommonMark for example, near as I can tell 😕
Thanks for letting us know about this syntax though! We'll keep it in mind.
