### ISSUE TITLE
Potential issue with notes replacing other notes?

### ISSUE THREAD

**Issue by da2x** [standardnotes/forum#716]
I keep the Standard Notes webapp open on several computers. They sometimes go to sleep and resume their session from hibernation hours later. I also use the Android app.

I’ve frequently (like once a week for the last four months) experienced that the note at the top of the list simply disappears. This will often be a pinned or frequently modified note. It’s not in trash, it’s just gone. I’ve had this happen when moving another note to trash. Both the intended note and the top note will completely vanish (they’re not in the trash folder).

I’ve also frequently experienced (like twice a week for the last four months) issues where the note I’m editing replaces the top note. The top note, often a pinned note, will be replaced by a snapshot of the note I’m editing from the moment I started editing it. The replaced note’s revision history will show the time stamp that I expect for that note, and not reflect that its content was replaced/updated.

https://www.ctrl.blog/entry/standard-notes-dataloss.html

I can’t reproduce this issue on demand. I’ve tried paying close attention to my notes and what I’m doing to try and nail down this issue. However, I use the service several times per hour and can’t really think of anything that stands out when this happens.

I’m greeted by “The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note.” about 50% of the time I open the webapp.

**Comment by da2x** [comment]
> If you were to sign into your account in a new incognito window, do the notes reappear?

No. When I open up Standard Note on another PC or my phone I don’t see the missing notes either.

> The issue of "The note you are attempting to save can not be found or has been deleted" has I believe occurred in the past with users of Firefox who leave a pinned tab opened all the time, and Firefox does not properly reload state upon the opening of the tab. Are you using Firefox by any chance?

I’m using Firefox and I leave Standard Note open as a background tab. Background tabs lazy-load when restoring sessions. This is indeed when I get that error. I usually dismiss the error and reload proper. However, I haven’t noticed any notes disappearing after reloading.

> The only other time a note will seemingly just vanish from your list is when you delete a note on another device, such as Android, then on web, when it performs a sync for the first time, it will delete any notes pending deletion from the server. The initial sync can happen when you make your first change in a session, such as deleting another note. In that case, 2 notes will be deleted at the same time (the one you're trying to delete now and the pending deletion from the server).

The notes that get deleted haven’t been marked for deletion on any client. As far as I can tell, it’s always the topmost note that disappears.

> Sometimes,  the sort order of your notes may change, or sync from another device,  which could immediately cause your notes list to shift around,  potentially causing a user to assume a note has gone missing, even  though its sort order has just changed to somewhere else in the list.

This isn’t the issue here. The notes haven’t just been moved around in the list, they’re gone proper.

**Comment by da2x** [comment]
> and Firefox does not properly reload state upon the opening of the tab

Here’s a black magic that will disable this feature in Firefox and WebKit-based browsers:

    window.onbeforeunload = (ev) => {return null};

(Registering any event handler on the `beforeunload` event will mark the page and its state as uncachable. This will of course have a negative impact on performance when people move back and forth in their history or when they restore sessions. It should get rid of the issue, though.)

**Comment by da2x** [comment]
Here is another possibly related issue:

Clicking the + button next to “All notes” (at `/html/body/div/div/div[1]/div[2]/div/div[1]/div[1]/div[1]/div[2]/div`) will add a new note to the top of the tab list. Clicking it again will remove the new note from the note list, but the editor will increment the `Note {int}` in the editor’s title field showing you’ve indeed made another note. The first note will just be gone forever. However, the second note won’t be listed in the notes list on the current device before I reload the tab.

**Comment by mobitar** [comment]
> Here is another possibly related issue

What's happening here is that the dummy note always appears on top of the list (even above pinned notes). If you press + again, it will persist that note, and move it under any pinned notes you have.

**Comment by mobitar** [comment]
> No. When I open up Standard Note on another PC or my phone I don’t see the missing notes either.

Just to be sure, I mean signing into a new account session from scratch. We want to see what the server sends back when starting from a blank slate. Also, do you have any backup files? I'd be curious to get the UUID of the deleted item and see if the server reports it as being deleted. The desktop app creates backups automatically via the top level Backups menu.

**Comment by da2x** [comment]
> What's happening here is that the dummy note always appears on top of the list (even above pinned notes). If you press + again, it will persist that note, and move it under any pinned notes you have.

That’s not what’s happening. This is what’s happens.
[screenrecording.zip](https://github.com/standardnotes/forum/files/3693639/screenrecording.zip) (horrible quality but you can see the note disappears when I repeatedly click Add)

> Just to be sure, I mean signing into a new account session from scratch.

I opened up a new web browser that I’ve never logged in to Simple Note from. I logged in, and there is no sign of any of the missing notes there either. The list of notes is the same as my other instances.

> The desktop app creates backups automatically via the top level Backups menu.

I only use the web-browser version and the Android app.

**Comment by mobitar** [comment]
Are you using any of the editor extensions, or just the plain editor?

**Comment by da2x** [comment]
> Are you using any of the editor extensions, or just the plain editor?

No extensions, just the default plain text one.

**Comment by mobitar** [comment]
Ok, thanks for the info. I've spent the last several hours trying to replicate any similar behavior based on the context here and in your blog post, but am unable to do so. I've also created a [public bounty](https://github.com/standardnotes/bounties/issues/45) in case anyone else wants to take an attempt at replicating your scenario or any similar scenario.

**Comment by bryvin** [comment]
I can also replicate the adding of a dummy notes and clicking plus again to see it remove and increment on the next press of plus. What's happening is they are actually being created as a note and synced to your account. The modified date on the dummy note for my tests shows as: December 31, 1969 6:00PM. Since my list is sorted by Date Modified they are being added to the bottom of your Note list (scroll all the way down for it to load in more into view until you get to the bottom; they will all be stacked up there). 

![2019-10-07 13_49_57-Notes](https://user-images.githubusercontent.com/5969300/66339751-66315f80-e909-11e9-9cae-121adea31f3a.png)


Regarding the duplication I also haven't seen this in my usage, but I will open it on multiple devices when I get a chance and give that a shot to see if I can replicate your issue.

**Comment by mobitar** [comment]
@da2x could you also describe what Firefox addons you have enabled? And if there's anything else peculiar about your environment please do share.

**Comment by mobitar** [comment]
@bryvin good catch re 1969 date modified. Should not default to that.

**Comment by da2x** [comment]
> @da2x could you also describe what Firefox addons you have enabled? And if there's anything else peculiar about your environment please do share.

That could be difficult. I’ve got different add-ons on four different installations on four different operating systems. I also use a few different Chromium based browsers. Most of the time, I use Firefox, however.

**Comment by da2x** [comment]
I’ve emailed @mobitar some identifiers for notes I’ve been able to confirm have been overwritten while I was editing another note. (So note a draft of Note A have overwritten Note B, causing Note B to be lost.) Hopefully he can look these up and find something useful in the server logs.

**Comment by mobitar** [comment]
After speaking more with @da2x and investigating his account, it's clear that no notes have been deleted that should not have been deleted. The only remaining theory is that editing some note overwrote the contents of another note. However, I'm fairly certain that there is no such bug in the app that would write contents of one note onto another, especially using just the plain editor. Any such incident would have been reported in mass if encountered, and the core editing code of the app has not been modified in several months.

I would put my confidence at 99% that there is some UX confusion here that could have possibly resulted in accidental overwriting of notes, and this UX confusion being caused by us. For example, pressing the + button many times can cause notes to appear in unexpected orders, due to a date mismatch. This is relevant because @da2x mentioned many times it has to do with a note "at the top", which is where dummy notes like to nestle. Combined with @da2x's rapid usage of the app on multiple platforms using a myriad of Firefox configurations (that would cause the rare and not-supposed-to-be-seen "this note can not be found" error alert), there's definitely room for unlucky UX interactions.

I've spent the better part of 2 days digging into the details here, but just cannot find anything. It would not be the first time that UX caused unintended behavior. But I do have to come to a conclusion regarding this issue, and that is that I do not believe there are inherent logic bugs causing the app to mismatch notes. If I end up being wrong and there is indeed a severe bug causing note conflation, then I'd owe you the biggest apology @da2x.

I'll be making updates to the web app that should fix a few areas of dummy note behavior. I did also find an issue where trashing/deleting one note would trigger a save event on the note next to it in the list. This event looks harmless, but it's possible that egregious use of this behavior could cause unintentional behavior. 

And if I do hear more reports of a similar issue, I'll be sure to re-open and update this thread.

**Comment by da2x** [comment]
> And if I do hear more reports of a similar issue, I'll be sure to re-open and update this thread.

I don’t think you’ll hear any reports. Most users don’t use GitHub and wouldn’t file one. It’s more likely that people would just abandon the service when faced with such issues.
https://twitter.com/BrideOfLinux/status/1181570146881740803

**Comment by mobitar** [comment]
I think we would. Users who have been using us for a few months with no issue, who then suddenly experience this issue, would definitely reach out. GitHub isn't the only support medium. We hear endless feedback regarding a lot less important things.

**Comment by mobitar** [comment]
Better late than never, but we finally found the cause of and fixed this issue a few versions ago :) It was a race condition where switching editors quickly while a sync save was in progress could have a chance of overwriting one note with another if the timing stars aligned.
