### ISSUE TITLE
Unable to install Standard Notes on Debian Buster

### ISSUE THREAD

**Issue by linzinha** [standardnotes/forum#733]
I've tried everywhere including asking on the Slack before posting here:

If I follow the instructions, when I get to
`./standard-notes.AppImage`
I get 
`dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. `

`apt-get install fuse` tells me that fuse is already installed at the latest version (2.9.9-1)

I'm elevated to root, with su, but read that su works differently with Buster re: file paths? So I've tries with/without sudo before the commands.

`./standard-notes.AppImage --appimage-extract` seems to do _something_? But I don't know where to go after that.

Thank you, I'm new to linux so sorry if its just that I don't know what I'm doing!

**Comment by zedgoat** [comment]
Howdy. Not super familiar but would this be `libfuse2` or `fuse2` not `fuse` as the dependency here? Googling around I'm seeing:

- <https://packages.debian.org/stable/fuse> - for the app
- <https://packages.debian.org/stable/libfuse2> - for the lib.

**Comment by kaeptnkrunch** [comment]
After Installing the newest Version of fuse and libfuse2, the application still doesn't run. Is there any solution for this Problem?

**Comment by jrabensc** [comment]
Try running it with the --no-sandbox option, worked for me.

**Comment by aa153** [comment]
@jrabensc I had an error:
--------
[27201:0606/133524.842263:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_StandabKZriE/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
---------
and running "./Standard-Notes-3.4.1.AppImage --no-sandbox" worked! 
Thank you ;)
