### ISSUE TITLE
Extension Documentation Missing Info on windows

### ISSUE THREAD

**Issue by agundy** [standardnotes/forum#739]
I've been playing with writing my own extension and having trouble getting on boarded. The documentation is pretty sparse. 
Two biggest things getting started:

- It's not clear what methods are available on the bridge or how to use it
- Unclear how to have my extension open a window

An idea of what I'm trying to do: I want to make a custom tag managing extension and I am trying to have an open page like the batch manager does. Can't figure out how that plug in works. Especially confused since other docs point to an ext.json file but that repo doesn't.

**Comment by mobitar** [comment]
The Batch Manager is an extension of type "modal". This instructs SN to open it in a popup-like window. That's all you would need to specify in your .json file. Our repos don't have .json because we serve the extensions from a custom server. You should follow the [publishing](https://docs.standardnotes.org/extensions/publishing) instructions for how to handle that.

You can take a look at the available bridge methods via:

- How the app receives the messages: https://github.com/standardnotes/snjs/blob/master/lib/services/componentManager.js#L385
- The actual bridge source: https://github.com/sn-extensions/components-api/blob/master/src/componentManager.js#L199

**Comment by agundy** [comment]
Thanks for the links, I'll try to check these out.
