### ISSUE TITLE
Spellcheck dictionaries

### ISSUE THREAD

**Issue by wonderfullyrich** [standardnotes/forum#745]
On the desktop client (MacOS in my case) how do I modify the dictionary that it uses?  I'm thinking about new words, as well as technical word additions, etc.

**Comment by mobitar** [comment]
No way to do this currently..

**Comment by BillTheBum** [comment]
This is an issue for anyone working in specialized STEM, law, or medical fields. Is there a plan or timeline for this?

**Comment by pretendasaur** [comment]
Would also love a way to add something to a dictionary.

**Comment by baptiste-grob** [comment]
The app currently reads from your mac's preferences to determine which dictionary to use. In version 3.5 (currently in development) it will also respect your existing word additions as well as let you add new spellings directly from the app 👍

**Comment by BillTheBum** [comment]
Great. I hope the V3.5 feature works in Windows also.

**Comment by baptiste-grob** [comment]
It will :)

**Comment by BillTheBum** [comment]
Great!

**Comment by TheodoreChu** [comment]
It looks like the latest versions of the Desktop app (v3.5+) have a "Learn Spelling" feature. Is there a way to tell the dictionary to un-learn a learnt spelling? I would like to document this

**Comment by baptiste-grob** [comment]
There is currently no way to un-learn a spelling from within the app, though on Windows and macOS the words get added to the system dictionary so you _could_ remove them using another program (I'm not saying that's a good workaround 😅)
It's something I'd like to get to at some point 👍

**Comment by JaspalSuri** [comment]
Hello everyone,

While I don't recall which update this was introduced in, learned words can be manually removed from the `Custom Dictionary.txt` file. 🎉 🙂 

In order to do this, launch the desktop app, unlock it if needed, click on the menu button (located at the top-right corner of the app) or navigate to the top-level menubar, click **Help**, click **Open Data Directory**, locate the `Custom Dictionary.txt` file & open it, remove the words you would like for the app to unlearn, save the file, and then restart the application.

Please note that you do not have to modify anything else (particularly the last line) in the file.
