### ISSUE TITLE
Linux installation problem on chromebook

### ISSUE THREAD

**Issue by collinvine** [standardnotes/forum#782]
I'm running a debian distro on a Pixelbook Go.

When following installation instructions from [this page](https://standardnotes.org/download/linux), I can't get the app to complete installation.

**Steps Taken**

1. Download the file standard-notes-3.0.23.AppImage
2. Add a+x permissions
3. Run the program using `./standard-notes-3.0.23.AppImage` command
4. App opens and terminal keeps running...

While the terminal runs, the app opens and an icon is placed in the shelf, but it's a penguin icon vs. the standard notes icon.

![image](https://user-images.githubusercontent.com/15755488/69585570-fb111a80-0f94-11ea-81d2-6f11612f9b10.png)

This has been running for ~10-min.

Once I stop the terminal (ctrl+C), the app also closes. The app icon is not added to my applications folder. The only way for me to re-open it is by opening terminal and executing the AppImage file again.

How can I get this to complete installation, and get the icon to permanently appear?

**Comment by bryvin** [comment]
Unfortunately due to a recent update to the Electron packager that SN uses (electron-builder) the generated AppImage no longer includes the desktop integration portion. 

There has been a discussion here: https://github.com/standardnotes/desktop/issues/430

[AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) seems to be the recommended solution for this which you should be able to install; then reopen Standard Notes and you will be prompted if you would like to integrate it with your system.

_Note I am not sure if the same applies for Chromebooks so please let us know if you have any issues with the above solution._

**Comment by collinvine** [comment]
Thanks for the quick response. I'm going to give that a shot and I'll report back.
