### ISSUE TITLE
Ability to underline words in Markdown

### ISSUE THREAD

**Issue by Ruin0x11** [standardnotes/forum#794]
Would it be reasonable to add the ability to <u>underline</u> things in the Markdown editors?

I understand that in some dialects of Markdown you can use `<u></u>` as inline HTML tags to underline words. Discord uses `__` for underlining (which does bolding in Standard Notes instead). Markdown itself does not have an official syntax for underlining words.

I can do this in Google Docs, which was where I was migrating from, but cannot in Standard Notes.

I understand it's a feature request which may compromise the longevity of the platform, but was wondering if it was ever going to be considered.

**Comment by bryvin** [comment]
The Standard Note Markdown extensions are 3rd party editors that I believe are all based on CodeMirror. It doesn't look like even any of the new versions of CodeMirror support this and adding this to the existing extensions may be difficult because of this.

New extensions that are based on another 3rd party editor that does support underlining is not out of the question and the community can even develop their own extensions to fit their needs accordingly. If you'd like to read up on developing Standard Notes extensions you can visit the docs: https://docs.standardnotes.org/extensions/intro-to-extensions

**Comment by Ruin0x11** [comment]
Understood, thanks.
