### ISSUE TITLE
Best way to mass-delete or mass-archive a lot of notes

### ISSUE THREAD

**Issue by dietervds** [standardnotes/forum#796]
Hey there!

I have >2000 notes, and want to tune this down to about ~500 for faster loading times.  

Some questions on this:

- Is the batch manager extension the best way to do this? Or is there some other way, like dumping them onto the file system, deleting them, and then re-importing?
- Does the batch manager allows you to archive a note? I think I just see a delete button but I might be missing something.
- Do archived items get loaded/synced as last? Or does that not enter into the syncing logic?

As always, thanks for an amazing product :-)

Cheers!

Dieter

**Comment by bryvin** [comment]
- Mass deleting notes is a little cumbersome at the moment and your suggestions are both valid. If you choose to do it via files; I would suggest saving an extra exported backup on the side before trying to delete any files.

- The batch manager currently doesn't offer any way to archive the selected items. The ability to archive notes was created after the batch manager and there just hasn't been any updates yet. We hope to add some improvements to the UI to make this process a bit easier.

- The archive status of a note is not available to help sort the order at which items are pulled in off the server. This data is held within the encrypted content of the note as is all relative data to a note so that nothing can be identified by an outsider.

Hope this helps and we're glad you're enjoying Standard Notes! 😄

**Comment by joshcsullivan** [comment]
@dietervds Out of curiosity, how long does it usually take those 2000 notes to load?

**Comment by jacktuck** [comment]
Also curious why you have so many notes.

**Comment by dietervds** [comment]
@bryvin It helps indeed! Thank you sir :)

@joshcsullivan About 10-15 seconds I'd say on my phone. Which isn't -that- horrible, but just annoying enough :D Causes quite a few conflicted copies each week just because of my impatience ^^ It's an old phone though. iPhone 6S Plus, not sure what difference it would make when I upgrade. 

@jacktuck I'm not sure really. I've been taking notes for many years now, and for most of that time I made a new note every day with my todo's, which ones I finished and any things I had to write down along the way. Kind of like a work-journal. Although I've stopped that habit to try and get the note count down :D
I also write down notes for most of the technical bits I'm working on, which have proven their worth over and over again when I search for them again a year later :)

**Comment by riverbedlegend** [comment]
Totally get you, I had to manually delete over a thousand notes one time and it was so tedious. I still have over 2000 notes now but I wish I don't have to be so conscious about making new notes every time as they might slow down loading time.

**Comment by lukf** [comment]
I currently have >5000 notes in Bear on iPhone with no performance issues whatsoever. Will Standard Notes ever reach comparable performance when it’s using non-native frameworks on iOS?

**Comment by mobitar** [comment]
This has little to do with native/non-native, and more to do with encryption/decryption.

**Comment by dietervds** [comment]
Follow-up question on this one: 

I dumped all my notes, cleaned them out, and got them back into a SN file format with the SN plain-text convertor tool.  

How should I go about replacing -all- my existing notes with the new import file that I have at the ready?

Cheers!

**Comment by mobitar** [comment]
Try standardnotes.org/reset.

**Comment by dietervds** [comment]
Works like a freakin' charm. Sorry, I should have found that on my own.
Thanks!
