### ISSUE TITLE
Does archiving help with performance

### ISSUE THREAD

**Issue by chanclr** [standardnotes/forum#799]
Over on this page https://standardnotes.org/help/55/how-can-i-optimize-the-performance-of-standard-notes
there are some suggestions to optimize performance of SN. I was wondering if archiving would also help?

**Comment by bryvin** [comment]
Archiving notes does not help with performance on startup due to the archiving status of a note being encrypted along with the rest of the content for the note. SN (also everyone else who may have an encrypted copy of your backups) doesn't know which notes may be important; ie: one's that have been password protected, in certain tags or not archived. The entirety of a note is encrypted and this ensures the highest level of security for your notes even if it means having to first decrypt a note to be made aware of the status.

With that being said, it will however help; even if only slightly in the same way not scrolling your entire list of notes on the desktop will help. If you keep those notes out of the rendered UI view by being archived they will not degrade the performance of the UI.
