### ISSUE TITLE
New editor that supports pen input

### ISSUE THREAD

**Issue by BuzzKnightbeer** [standardnotes/forum#820]
I'm on a Surface Pro and it would be awesome if I could use SN to quickly note down scribbles or other details via the Surface Pen.

**Comment by bryvin** [comment]
The tricky thing with drawings is their size in terms of data. Unfortunately due to how Standard Notes works with encryption taking place on the device every time it syncs your newest change, the size of the data is critical to keep to a relatively small size. Especially when all of your notes combined, it adds up quickly.

With that being said, Mo did look into this a while back and it just wasn't feasible at the time due to the size. We will have to experiment some more here in the future and see if there are any good editors out there that may be viable to embed as an SN editor that exports the data as an SVG or something rather than a typical image. That type of data could definitely be a valid option as it would be essentially saving text of the shapes.

If we make progress on this we will definitely be sure to let the community know, thank you for the suggestion!

**Comment by effieeee** [comment]
Check out the Free Draw extension mentioned in this comment! https://github.com/standardnotes/forum/issues/1488#issuecomment-1307469887
