### ISSUE TITLE
iOS App Crashes while adding photo 

### ISSUE THREAD

**Issue by mrtargaryen** [standardnotes/forum#822]
iOS: 13.3
SN: 3.0.17
Editor: Plus Editor 

Every time I attempt to add a photo from the photos app to a note in SN using the Plus Editor the iOS app crashes. I don't know if this is a common issue or not, but I thought I'd just make this post just in case. Thanks.

**Comment by mobitar** [comment]
The Plus Editor doesn't support adding photos (unless you mean embedding a photo from a link). Only the Bold Editor supports attachments (although that too will crash if you attempt to access the camera from the editor; this is an issue we haven't found a fix for.)

**Comment by kmholzem** [comment]
Has this issue been resolved. I literally purchased an account such that I can embed images from my phone into encrypted notes. I have no use for this app if it can't do this.

**Comment by JaspalSuri** [comment]
This shouldn't be an issue with the Bold Editor and FileSafe extension. Is it crashing for you when you use them?

**Comment by kmholzem** [comment]
Yes it is crashing with the Bold Editor. What is the FileSafe extension?

**Comment by JaspalSuri** [comment]
> Has this issue been resolved?
Currently it has not been fixed, but you can still upload photos to notes by using the FileSafe extension.

> What is the FileSafe extension?
The [FileSafe extension](https://standardnotes.org/extensions/filesafe) allows you to attach files to your notes and have them automatically encrypted and uploaded to your Dropbox, Google Drive, WebDAV server, or AWS S3.

Currently it only works with the Bold Editor, but you can attach files through it at any time and insert them into your note later; simply click on "Copy Insert Link" and paste it into the note using the Bold Editor. 

> Yes it is crashing with the Bold Editor. 
Can you provide a link (that you would be willing to share) of an image that you were trying to embed? Are you sure you weren't referring to the Plus Editor? (I just want to double check, since it doesn't crash on my end.)

**Comment by kmholzem** [comment]
This issue needs to be resolved. Having the images in a different cloud file save was exactly what I would like to avoid as I want to keep these images secure. I want them imported directly from my encrypted phone. Why can't this be fixed?

**Comment by JaspalSuri** [comment]
> Having the images in a different cloud file save was exactly what I would like to avoid as I want to keep these images secure.

While the images are stored with different cloud providers, they are encrypted, so they are unreadable. 

> I want them imported directly from my encrypted phone. Why can't this be fixed?

It's a non-trivial technical problem and having existing providers store files helps make things a lot easier. We do have plans on making this process seamless, but it will take some time to work on.

**Comment by effieeee** [comment]
Bold Editor and FileSafe are currently deprecated
