### ISSUE TITLE
issue: duplicated note

### ISSUE THREAD

**Issue by guydog** [standardnotes/forum#88]
I experience this issue:
I have 2 copies of the same note (same title, same date/time of creation); the problem is I noticed it after I edited one of them (thinking it was the only one).

I have two questions:
- what could have caused the duplication?
- is it safe to delete one of them (the oldest in terms of content updating), or the fact they have the same title could result in a bad server syncing and a subsequent loss of both notes?
(I will probably rename one of them to remain on the safe side)

Accidentally: it would be nice to add the note title in the "confirm delete" dialogue, so that is clear what note one is going to delete. 

Thank you for your attention

**Comment by mobitar** [comment]
Duplication is caused by a sync conflict: you edit a note that has unsynced changes. On web/desktop, it will say "Conflicted copy". On mobile, it won't say that (yet. It will in an upcoming update).

It's safe to delete one of them, you just need to look at them and figure out which is the copy you want to keep.

**Comment by mobitar** [comment]
Update: You can now use the Batch Manager extension for this.

Extensions -> Batch Manager -> Open.

(Only on web as of 2/28/18, coming to desktop soon.)
