### ISSUE TITLE
How would I install this on Arch-based Linux?

### ISSUE THREAD

**Issue by Joe23232** [standardnotes/forum#906]
I don't wish to use appimage to install the package (due to how bloated app images can get) so is it in the AUR or something? What is the package name of Standard notes?

**Comment by JSkier21** [comment]
There is also an AUR package available:
[AUR Package](https://aur.archlinux.org/packages/standardnotes-desktop/)

**Comment by x80486** [comment]
I think you should try to make a Flatpak out of this. I've tried several times, but there are issues in the way the application is packaged; if application's owner(s) decide to move ahead and fix those, building this into a Flatpak should be doable.

I don't use AUR and Snaps don't work quite well (read integrate) with the operating system...I guess only if you are in Ubuntu.

**Comment by JaspalSuri** [comment]
> I've tried several times, but there are issues in the way the application is packaged; if application's owner(s) decide to move ahead and fix those, building this into a Flatpak should be doable.

Any details from your experience might be helpful!

May I ask why you chose not to use the [AppImage](https://standardnotes.org/download/linux)? You might be able to use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) to install it.

**Comment by Joe23232** [comment]
@JaspalSuri Afaik AppImage and FlatPak both bloat up your disk space as they do not share dependencies like Pacman does.

**Comment by x80486** [comment]
@JaspalSuri, I still have the branch [here](https://github.com/x80486/flathub/tree/org.standardnotes.standardnotes/). The problem is mainly with some dependency around spellchecking or something like that. Probably you can't change that, but if you are interested, I can give it another whirl and provide more details.

AppImage is basically a broken format. You expect it to work because you make assumptions around the libraries that should be installed on the host; that doesn't work in rolling releases where sometimes a not-so-old dependency is obsolete. The other side is the way you install, update them, sandboxing – which you can work out to some extent with `Firejail`, but every time I've tried that, there is one thing or two that doesn't work out-of-the-box, so I don't spend time on it.

On the other hand, Flatpak solved almost all of that. It's true that you have to install "runtimes" but those are shared between applications, and space is cheap these days, so who cares about it on a desktop. Think of them like _base containers_ that guarantee your app is going to work regardless of where it's executed, in exactly the same way. In that sense, like any other container technology, you trade space for part of those guarantees. I can't really tell you all the benefits because I just use it, and from time to time package one application, but you can read more about it.

**Comment by baptiste-grob** [comment]
@x80486 In an upcoming version of the app we won't be relying on an external dependency for spellchecking so if that was your only blocker you can fork the dev branch right now and give it another whirl!

**Comment by uncivilgentleman** [comment]
> We're on the Snap store: https://snapcraft.io/standard-notes

Would you consider packaging as a Flatpak as well? Snaps are kind of Canonical's proprietary thing so I'd rather not use it and I don't think I'm the only one that feels that way.

I know your time is limited but I think having StandardNotes on Flathub would be worth it.  I've been eyeing StandardNotes but don't like the mess of manually downloading and updating an appimage or want to adopt Snap packages.

**Comment by JaspalSuri** [comment]
AppImages offer somewhat seamless updates, just like our other desktop apps for other platforms do, and you can use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) to resolve the issue with the icon not appearing when you install it the first time.

>I know your time is limited but I think having StandardNotes on Flathub would be worth it.
I'm afraid that we currently can't maintain a Flatpak, but hopefully we can in the future.

**Comment by effieeee** [comment]
Tracking flatpak request here: https://github.com/standardnotes/forum/issues/1587
