### ISSUE TITLE
Notes not showing in desktop app

### ISSUE THREAD

**Issue by mheder** [standardnotes/forum#95]
Symptoms
I have some notes that:
* show on the android app 
* show on the web data dashboard
* desktop app DOES NOT show them
* desktop app decrypted data archive DO contain them. 

In these cases the desktop app show a false number of notes next to the tag - the number equals the notes it can show, that is less than all the notes in that tag.

Deleting the local data and signing in again does not make a difference.

If I recall correctly all these notes were created on the desktop app.

Editing these notes, even adding some white spaces (using the android app) makes them reappear on the desktop too. 

My speculations
- some sequential loading fails at some item and then the remaining notes in that tag fail to load. Actual example: on the desktop I had a category showing 32 notes, while on the mobile 36. I edited one of the four missing notes and the number jumped up to 36 immediately on desktop too. 

- although the notes are heavy on accented Hungarian characters like őűáúő, etc and I also use strings like "->" and even ascii-art heavily this seems to be no problem. If I add a single whitespace to a missing note in android and then delete it, the note first appears and then remains. A diff in the archive show no difference in the contents.

- the problem seems to be related to tags and the contents of the "references" section of the data model. When the note is missing I have 

`"references": []`

while after it has been restored:

```
"references": [
           {
             "uuid": "(value redacted from this github issue)",
             "content_type": "Tag"
           }
         ]
```

I assume a save in the android app somehow makes the desktop app re-sync and restore the tags of these notes. I inferred that then these missing notes still show up in "all notes", but no, they show nowhere in the desktop app while the problem persists.

I cannot reproduce this in the sense that I cannot create notes that disappear. After I make them reappear they will remain. So I hold on to some that are still missing from desktop in case it helps debugging.

**Comment by mobitar** [comment]
That's very strange. It's made tricker by the fact that we only have a limited supply of notes to test this on. Can you try signing out then signing back in with the JavaScript console open, and see if it reports any errors?

**Comment by mobitar** [comment]
Another thing you can test: can you try importing your export file into a blank session (you don't have to be signed in), and see if the notes show up then? If they don't show up, then that's good reproducibility that I can work with.

**Comment by mheder** [comment]
The only issue I get in the console is
"Error while parsing the 'sandbox' attribute: 'allow-top-navigation-by-user-activation' is an invalid sandbox flag."
This seems to be unrelated. 
Importing to a blank session reliably reproduces the problem. How can I dig further?

**Comment by mobitar** [comment]
Well, that's good that it's reproducible. Let's try to figure this out. 

Are you able to dummify the decrypted archive file with dummy text so that you can share it with me? I'd love to get my hands on this file to diagnose it myself. If there's too many items, perhaps you can delete as many items as you can while still being able to reproduce the issue.

**Comment by mheder** [comment]
Okay, I started digging in the JSON and quickly realized the problem is not there, also, my initial reporting was inaccurate. The missing notes DO show in "All notes", but they are not enumerated in their proper tag. 

However, there is nothing wrong with the desktop app per se. It shows what it gets from the server. So this is how I realized that the view I have on mobile - with all the notes in the tags I put them - only shows in the mobile. The phenomena is simply caused by concurrent modifications to the tag node and some inconsistend behavior between mobile and desktop in handling that.
-----------------------------------------
To reproduce:
0) NTP-sync your clocks

1) Create Notes N1 N2 N3 N4 N5 on desktop
2) Create tag T1 on desktop
3) Have your mobile app synced everything
4) Go offline with your mobile 
5) Add notes N1-N3 to T. Now on your mobile  you have unsynced changes
6) On your desktop create add N4 to T

at this point you have two versions of tag T, on the mobile, it contains 3 elements (N1, N2, N3), on the desktop, only 1 (N4)
Here it gets interesting

7) go online with your mobile and sync

At this moment on your mobile you have two T tags next to each other. One has 0 elements, the other has 4 elements: N1, N2, N3

8) Wait a bit. Soon your desktop app will sync. 

When the dekstop app syncs, it will have also two T tags, one with 0 elements, the other with 3: N1, N2, N3. On desktop, N4 is now not in T, on mobile it is in T. 

9) I create notes mainly on desktop, so the next step simulates that. On your desktop add N5 to T. Now you have 4 elements here, N1, N2, N3 and N5. On mobile the list contains all 5 notes and the difference is conserved as long as you don't modify T on your mobile. 

10) On your mobile create N6 in T and sync. Wait your desktop to sync. 

Now you have all 6 Notes on both platforms, in perfect sync, plus one empty T on both platforms. 
----------------------

When I moved over from diaro, I brought 100-200 notes. I did not bother understand tagging in the JSON format, so I added tags on my mobile in my spare time when commuting. Apparently I was not online and apparently managed to create a "Research" Tag with 56 notes on mobile and 33 on desktop with the method above and that scared me, where that 22 notes are? Also I remember deleting those empty tags, thinking it is just some harmless glitch.

I assume Tag nodes in the data are in many ways just like regular content. Maybe the system makes duplicate tags when there are two concurrent versions in order not to lose data?

This made me think trying the following. 

1) go offline on your mobile and write the string "foo" to N1 as content
2) on your desktop app write "bar" to N1
3) go online on your mobile

Your N1 will show "foo" everywhere, even though that content was created earlier. "bar" is not found in the dump either. This is very scary and indeed explains a case where I lost some lines from the end of  a meeting minutes and then I doubted myself about writing it in the first place - and decided probably my mind slipped :)

My take-away messages from this: 
I) The issue can be worked around if you add something to all of your Tags on mobile. Those nodes can be later deleted

II) When using the mobile I never modify tags and notes, only create new ones. For me this is the safest, as I don't want to rely on my awareness and presence and not forget on desktop that my mobile might contain unsynced changes.

III) There is definitely an issue here around managing conflicts.
III/a) apparently not the newer "is modified" timestamp wins, but somehow the platform that pushes first?
III/b) if III/a) is true then this is a kind of race condition, and maybe the roles of desktop and mobile could be reversed. 
III/c) on the server conflicts like this are hard to solve as the data is encrypted. But the client could do something about it, e.g. pulling changes before pushing,  detecting the conflict there and merge or simply duplicate.

**Comment by mobitar** [comment]
Wow, excellent investigative work. So, as you caught on to, handling sync conflicts server side is impossible due to encryption, so we do this client-side. 

For pushing and receiving changes, we use a single endpoint called `sync`. `sync` takes in items via `items`, and also sends back items via `retrieved_items`. The simple rule is, if you're trying to save an item, and that item has a pending change, then a conflict occurs. In case of a conflict:

1. If the changes between the two items are 20 seconds apart, then we treat the difference as negligible/network issue, and do not duplicate the item, and instead choose the one that was last received (the one the user initiated contact with most recently).
2. If the changes are greater than 20 seconds apart, the server does not save the incoming item, and instead instructs the client to duplicate it and push up a new item.

I tested your last set of steps (foo/bar in mobile/desktop) and confirm that it does seem to be working as intended:

- If the changes are within 20 seconds of each other, you'll see that both notes will now say "Foo", which is the last user contact event.
- If you wait over 20 seconds, then make the last change, you'll see that on desktop the note will be duplicated and will say "Conflicted copy" on top, while the desktop also receives the duplicated item (but does not show "Conflicted copy" since that flag is not synced across devices).

That's sort of the best solution I've found to the sync conflict issue. I'm definitely open to hearing suggestions for ways it can be improved. I like the idea of first retrieving changes before pushing, but it might be the same result as what we have now: the user will eventually need to choose between two copies.
