### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by maudam** [standardnotes/forum#97]
Hi,
I'm testing the android app. i have android 4.4 so i have to install the unreleased app on the store.

As soon as i try to add a note the app crash.

When i try to register an account, on "generating crypto keys" the app crash,

Are you going to fix this version or you are working only on the android 5+ version ?

Thanks

**Comment by mobitar** [comment]
Hey, sorry, 5.0 will be the minimum supported for release. It just hasn't been set yet on the beta. Is 4.4 still common among Android users?

**Comment by maudam** [comment]
Hi mobitar,
yes it is in use by some people.
Kitkat is now ad 14.5% of users.
For all 4.x are more than 20%

You can see google's play stats here:
https://developer.android.com/about/dashboards/index.html

**Comment by mobitar** [comment]
Interesting, thanks for the info. I tried testing with 4.4 myself now and the app is technically incompatible due to some of the code we use. So it will be unlikely that we will support this. Apologies for the false hope. I'll definitely be keeping an eye out to see if we can make changes that allow us to support 4.4.
