### ISSUE TITLE
Protected notes in Trash do not ask for passwords

### ISSUE THREAD

**Issue by mjdwyc** [standardnotes/forum#980]
**Describe the bug**
I think this is a bug: notes in Trash that are protected are revealing themselves without asking for passwords/local passwords.

**To Reproduce**
1. Go to a note
2. Protect it
3. Trash the note
4. Go to trash
5. Select the protected note

**Expected behavior**
The password input window should pop up after step 5.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.4.1

**Note:** If it's not a bug but intended... I'd like to request password protection for protected notes even inside the trash, please! Would give me peace.

**Comment by mobitar** [comment]
I'm unable to reproduce this. You might be seeing this due to two reasons:

1. You have an authenticated Privileges session being remembered (can verify via Account > Manage Privileges > Clear Session)

2. You haven't configured your Privileges to require authentication for viewing Protected notes (can also be configured via Account > Manage Privileges)

**Comment by mjdwyc** [comment]
Thanks for the fast reply! The reason was the first one. Now it works normally. Thank you so much.
